### ISSUE TITLE
Torrent not being added after upgrading to 2.0.3

### ISSUE THREAD

**Issue by handshake87** [rogerfar/rdt-client#100]
So I recently upgraded rtd-client from 1.8.3 to 2.0.3. After the upgrade I noticed no torrents are being sent to rtd-client. In the log of Sonarr it states:```
 HTTP` Error - Res: [POST] http://127.0.0.1:6500/api/v2/torrents/add: 500.InternalServerError
Bad token
```

I have no changed any setting in Sonarr following the upgrade. I also deleted it and re-added the Download client as qbittorent and it still did not solve the issues. Any ideas for a resolution would be greatly appreciated!!

**Comment by rogerfar** [comment]
Are you sure you entered the correct password in Sonarr? Can you show the rdt-logs.

**Comment by handshake87** [comment]
Sorry

> Are you sure you entered the correct password in Sonarr? Can you show the rdt-logs.

Sorry for the delay. I have confirmed that nothing is different and have readded real-client in sonarr. If I add with incorrect information it errors out stating authentication error. When I enter in the correct username and password it allows me to add it to sonarr no problem.

I am unsure of how to find the logs. Any help with that would be greatly appreciated.

**Comment by handshake87** [comment]
I think this is what you are looking for:

> 2022-01-18 16:20:29.896 +00:00 [ERR] Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware: An unhandled exception has occurred while executing the request.
RDNET.Exceptions.RealDebridException: Bad token
   at RDNET.Apis.Requests.Request(String baseUrl, String url, String headerOutput, Boolean requireAuthentication, RequestType requestType, HttpContent data, CancellationToken cancellationToken)
   at RDNET.Apis.Requests.Request[T](String baseUrl, String url, Boolean requireAuthentication, RequestType requestType, HttpContent data, CancellationToken cancellationToken)
   at RDNET.Apis.Requests.PostRequestAsync[T](String url, IEnumerable`1 data, Boolean requireAuthentication, CancellationToken cancellationToken)
   at RDNET.Apis.TorrentsApi.AddMagnetAsync(String magnet, CancellationToken cancellationToken)
   at RdtClient.Service.Services.TorrentClients.RealDebridTorrentClient.AddMagnet(String magnetLink) in /appserver/server/RdtClient.Service/Services/TorrentClients/RealDebridTorrentClient.cs:line 113
   at RdtClient.Service.Services.Torrents.UploadMagnet(String magnetLink, Torrent torrent) in /appserver/server/RdtClient.Service/Services/Torrents.cs:line 117
   at RdtClient.Service.Services.QBittorrent.TorrentsAddMagnet(String magnetLink, String category, Nullable`1 priority) in /appserver/server/RdtClient.Service/Services/QBittorrent.cs:line 449
   at RdtClient.Web.Controllers.QBittorrentController.TorrentsAdd(QBTorrentsAddRequest request) in /appserver/server/RdtClient.Web/Controllers/QBittorrentController.cs:line 279
   at RdtClient.Web.Controllers.QBittorrentController.TorrentsAddPost(QBTorrentsAddRequest request) in /appserver/server/RdtClient.Web/Controllers/QBittorrentController.cs:line 316
   at lambda_method186(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at RdtClient.Web.Startup.<>c__DisplayClass5_0.<<Configure>b__0>d.MoveNext() in /appserver/server/RdtClient.Web/Startup.cs:line 112
--- End of stack trace from previous location ---
   at RdtClient.Service.Middleware.AuthorizeMiddleware.Invoke(HttpContext context) in /appserver/server/RdtClient.Service/Middleware/AuthorizeMiddleware.cs:line 30
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
