### ISSUE TITLE
New streams ID with alldebrid

### ISSUE THREAD

**Issue by Tsuna77** [rogerfar/rdt-client#102]
**What version are you using?**
2.0.3 Docker (latest when I write this ticket)

**Wat OS are you running?**
Fedora Server

**Are you using Docker or as a service?**
Docker

**Please attach a log file here with the log setting set to debug**
```
[21:27:22 ERR] Cannot unrestrict link: Unable to deserialize AllDebrid API response to DownloadLink. Response was: {
    "status": "success",
    "data": {
        "link": "******",
        "host": "uptobox",
        "filename": "****.mkv",
        "streaming": [],
        "paws": false,
        "filesize": 1144017740,
        "streams": [
            {
                "quality": "360",
                "ext": "m3u8",
                "filesize": 332386304,
                "name": "m3u8",
                "link": "https:\/\/www97.uptostream.com\/stream\/*****\/_m_main_0.m3u8",
                "id": "hls"
            },
            {
                "quality": "360",
                "ext": "mpd",
                "filesize": 332386304,
                "name": "dash",
                "link": "https:\/\/www97.uptostream.com\/stream\/******\/_m_main_0.mpd",
                "id": "dash"
            }
        ],
        "id": "2bb9u1ib666",
        "hostDomain": "uptobox.com"
    }
}
Newtonsoft.Json.JsonSerializationException: Unable to deserialize AllDebrid API response to DownloadLink. Response was: {
    "status": "success",
    "data": {
        "link": "***************",
        "host": "uptobox",
        "filename": "***.mkv",
        "streaming": [],
        "paws": false,
        "filesize": 1144017740,
        "streams": [
            {
                "quality": "360",
                "ext": "m3u8",
                "filesize": 332386304,
                "name": "m3u8",
                "link": "https:\/\/www97.uptostream.com\/stream\/****\/_m_main_0.m3u8",
                "id": "hls"
            },
            {
                "quality": "360",
                "ext": "mpd",
                "filesize": 332386304,
                "name": "dash",
                "link": "https:\/\/www97.uptostream.com\/stream\/******\/_m_main_0.mpd",
                "id": "dash"
            }
        ],
        "id": "2bb9u1ib666",
        "hostDomain": "uptobox.com"
    }
}
 ---> Newtonsoft.Json.JsonSerializationException: Error converting value "hls" to type 'System.Int64'. Path 'data.streams[0].id', line 17, position 27.
 ---> System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.String.System.IConvertible.ToInt64(IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at AllDebridNET.Apis.Requests.Request[T](String url, Boolean requireAuthentication, RequestType requestType, HttpContent data, IDictionary`2 parameters, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at AllDebridNET.Apis.Requests.Request[T](String url, Boolean requireAuthentication, RequestType requestType, HttpContent data, IDictionary`2 parameters, CancellationToken cancellationToken)
   at AllDebridNET.Apis.Requests.GetRequestAsync[T](String url, Boolean requireAuthentication, IDictionary`2 parameters, CancellationToken cancellationToken)
   at AllDebridNET.Apis.LinksApi.DownloadLinkAsync(String link, String password, CancellationToken cancellationToken)
   at RdtClient.Service.Services.TorrentClients.AllDebridTorrentClient.Unrestrict(String link) in /appserver/server/RdtClient.Service/Services/TorrentClients/AllDebridTorrentClient.cs:line 145
   at RdtClient.Service.Services.Torrents.UnrestrictLink(Guid downloadId) in /appserver/server/RdtClient.Service/Services/Torrents.cs:line 321
   at RdtClient.Service.Services.TorrentRunner.Tick() in /appserver/server/RdtClient.Service/Services/TorrentRunner.cs:line 337
[21:29:46 WRN] 101: /hub
[21:30:50 WRN] 304: /index.html
```

As you can see in logs, now we have two new types of download, m3u8 and dash, and they have non int64 Ids :(

**Comment by Tsuna77** [comment]
fix in 2.0.5, thanks :)
