### ISSUE TITLE
Alldebrid - Unexpected character encountered while parsing value: <. Path '', line 0, position 0

### ISSUE THREAD

**Issue by famaTV** [rogerfar/rdt-client#123]
Hello,

I can't get it to download any files despite the use of Simple, Multi Downloader or even Aria2.

Thanks in advance,

**What version are you using?**
Version 2.0.8

**What OS are you running?**
Docker in Ubuntu 18.04.6 LTS, using Portainer.io

**Are you using Docker or as a service?**
Docker. Is there a guide you can share to install it as a service in Ubuntu?

**Please attach a log file here with the log setting set to debug**
`[17:53:11 ERR] Cannot unrestrict link: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at AllDebridNET.Apis.Requests.Request[T](String url, Boolean requireAuthentication, RequestType requestType, HttpContent data, IDictionary`2 parameters, CancellationToken cancellationToken)
   at AllDebridNET.Apis.Requests.GetRequestAsync[T](String url, Boolean requireAuthentication, IDictionary`2 parameters, CancellationToken cancellationToken)
   at AllDebridNET.Apis.LinksApi.DownloadLinkAsync(String link, String password, CancellationToken cancellationToken)
   at RdtClient.Service.Services.TorrentClients.AllDebridTorrentClient.Unrestrict(String link) in /appserver/server/RdtClient.Service/Services/TorrentClients/AllDebridTorrentClient.cs:line 148
   at RdtClient.Service.Services.Torrents.UnrestrictLink(Guid downloadId) in /appserver/server/RdtClient.Service/Services/Torrents.cs:line 326
   at RdtClient.Service.Services.TorrentRunner.Tick() in /appserver/server/RdtClient.Service/Services/TorrentRunner.cs:line 371`

**Comment by rogerfar** [comment]
Can you send me the torrent file in a pastebin?

**Comment by famaTV** [comment]
Hello,

Sorry for the late response. It happens with all kind of torrent files. I noticed that Alldebrid will prepare the torrent for direct link from their website but when checking the app here, it give this error message above. I am not sure if it's Alldebrid or docker compatibility issues as this was initially developed for Real-Debrid.

You can download any file, for example this one http://www.legittorrents.info/index.php?page=torrent-details&id=7f34612e0fac5e7b051b78bdf1060113350ebfe0

Thanks again.

**Comment by rogerfar** [comment]
I don't have an Alldebrid sub anymore so can't test that easily. I have improved some logging for the providers to add the raw request data.

Can you try again in 2.0.9 and post the debug result again? It should show the raw JSON that came from AllDebrid.

**Comment by famaTV** [comment]
Hi again,

I updated to version 2.0.11 and re-test the download. It's now not showing any meaningful messages. Even the log doesn't show much: 

'[14:27:58 DBG] Processing 1 torrents

[14:27:58 DBG] Processing for torrent  (0 -  0%) (c8b69042-7713-493e-8da6-05ba03ca33cc)'

Any suggestion please?

![image](https://user-images.githubusercontent.com/6208778/159167233-d6986c05-ccb2-4722-b9b2-e25b58554565.png)

**Comment by rogerfar** [comment]
Looks like either something broke in their API or this was always an issue. Anyway, the API returns an ID of 0 when the torrent is already available. I fixed the AllDebrid API module to find the ID by hash when it's 0.

Should be good in the next version.

**Comment by rogerfar** [comment]
Can you post the full log as an attachment? Because this should not be the case. It sends an API call with the unrestricted link to alldebrid, it then gets unrestricted and downloaded.

For example a torrent I uploaded:

```
2022-03-21 11:28:45.269 -06:00 [DBG] RdtClient.Service.Services.Torrents: Unrestricting link for download **https://uptobox.com/jvhvatbyorba** 0% (927545bb-f1de-4278-ac0a-4446cd0fb802) for torrent Big Buck Bunny (139417933 - Ready 100%) (aa2c0987-ea4a-494d-a645-09f0986bac25)
2022-03-21 11:28:45.781 -06:00 [DBG] RdtClient.Service.Services.TorrentRunner: Marking download as started for download Big Buck Bunny.en.srt 0% (927545bb-f1de-4278-ac0a-4446cd0fb802) for torrent Big Buck Bunny (139417933 - Ready 100%) (aa2c0987-ea4a-494d-a645-09f0986bac25)
2022-03-21 11:28:45.785 -06:00 [DBG] RdtClient.Service.Services.TorrentRunner: Setting download path to C:\Temp\rdtclient for download Big Buck Bunny.en.srt 0% (927545bb-f1de-4278-ac0a-4446cd0fb802) for torrent Big Buck Bunny (139417933 - Ready 100%) (aa2c0987-ea4a-494d-a645-09f0986bac25)
2022-03-21 11:28:45.786 -06:00 [DBG] RdtClient.Service.Services.TorrentRunner: Starting download for download Big Buck Bunny.en.srt 0% (927545bb-f1de-4278-ac0a-4446cd0fb802) for torrent Big Buck Bunny (139417933 - Ready 100%) (aa2c0987-ea4a-494d-a645-09f0986bac25)
2022-03-21 11:28:45.788 -06:00 [DBG] RdtClient.Service.Services.Downloaders.SimpleDownloader: Starting download of **https://8sio2e.debrid.it/dl/2dldh6yf7fd/Big%20Buck%20Bunny.en.srt**, writing to path: C:\Temp\rdtclient\Big Buck Bunny\Big Buck Bunny.en.srt
```

This is the actual download link:
https://8sio2e.debrid.it/dl/2dldh6yf7fd/Big%20Buck%20Bunny.en.srt
and not
https://uptobox.com/jvhvatbyorba

So 2 things could be happening here:
1. Your ISP blocks the `debrid.it` domain too
2. The API call to real debrid gets blocked because it has the parameters `uptobox.com` in it.

In both cases there's nothing we can do except try RealDebrid or use a VPN.

**Comment by famaTV** [comment]
Hello again and thank you so much for putting some thoughts and efforts in this issue.

Please find attached the full log. Later today, I will use one of my friends' Real-Debrid account and check if it's the same issue or not. By the way, Alldebrid.com and debrid.it domains are accessible directly with the browser without any issues (they are not blocked).

[_rdtclient_logs.txt](https://github.com/rogerfar/rdt-client/files/8340206/_rdtclient_logs.txt)

**Comment by famaTV** [comment]
Hi again,

In continuation to the above explanation. I tried Real-Debrid and it worked without any issues. I am not sure if it's an ISP bock issue. Could be the way the API handles / works with Alldebraid compared to Real-Debrid.

![image](https://user-images.githubusercontent.com/6208778/159936068-0af91205-30d0-4846-aa2d-b2369b4eefba.png)

**Comment by famaTV** [comment]
By the way,

When I test alldebrid from settings, all was green (ok). Anyhow, please find attached the entire log for the docker.

Thanks again,

[_rdtclient_logs.txt](https://github.com/rogerfar/rdt-client/files/8342536/_rdtclient_logs.txt)

**Comment by rogerfar** [comment]
Thanks for the logs. It looks like it fails when trying to unrestrict the link from AllDebrid.

It looks like because the URL request to AllDebrid contains `https://uptobox.com/` it gets blocked right away.

Unfortunately AllDebrids API only accept GET methods and not POST, so we can't try to circumvent it as this point.

Glad that RealDebrid works though!

**Comment by famaTV** [comment]
Hello,

When i try to manually unrestric and then download a ready file from Alldebrid file, it will take me to this URL `https://alldebrid.com/service/?url=https://uptobox.com/21x0f4zxxxxx` which is working fine and not blocked by my ISP.

I am not sure how you are processing the request through the API that made it fail.

**Comment by rogerfar** [comment]
That's not the API, you have to test with the API calls:
https://docs.alldebrid.com/#download-link
