### ISSUE TITLE
Problem when upload a torrent from a specific website

### ISSUE THREAD

**Issue by Pommefrais3** [rogerfar/rdt-client#127]
**What version are you using?**
Docker version - 2.0.9

**Wat OS are you running?**
Synology NAS

**Are you using Docker or as a service?**
Yes

NOTE : this error only occurs when I download from yggtorrent.re and via FlareSolverr a proxy server to bypass Cloudflare protection

**Please attach a log file here with the log setting set to debug**
System.ArgumentNullException: Value cannot be null. (Parameter 'path2')
   at System.IO.Path.Combine(String path1, String path2)
   at RdtClient.Service.Services.Torrents.Delete(Guid torrentId, Boolean deleteData, Boolean deleteRdTorrent, Boolean deleteLocalFiles) in /appserver/server/RdtClient.Service/Services/Torrents.cs:line 278
   at RdtClient.Service.Services.Torrents.RetryTorrent(Guid torrentId, Int32 retryCount) in /appserver/server/RdtClient.Service/Services/Torrents.cs:line 447
   at RdtClient.Web.Controllers.TorrentsController.Retry(Guid torrentId) in /appserver/server/RdtClient.Web/Controllers/TorrentsController.cs:line 174
   at lambda_method3208(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at RdtClient.Web.Startup.<>c__DisplayClass5_0.<<Configure>b__0>d.MoveNext() in /appserver/server/RdtClient.Web/Startup.cs:line 112
--- End of stack trace from previous location ---
   at RdtClient.Service.Middleware.AuthorizeMiddleware.Invoke(HttpContext context) in /appserver/server/RdtClient.Service/Middleware/AuthorizeMiddleware.cs:line 30
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
2022-03-19 16:49:45.083 +01:00 [DBG] RdtClient.Service.Services.Torrents: Adding 3E87786A21DAAED33B481672B74437A61A85C1ED torrent file ZDg6YW5ub3VuY2U3NTpodHRwOi8vY29ubmVjdC5wMnB0cmFja2VyLmNjOjgwODAvMmZWVjVFMmFoak1mc0t1cGJ3UGwySEtueUlXR3R5V3MvYW5ub3VuY2UxMDpjcmVhdGVkIGJ5MTA6WWdnVG9ycmVudDEzOmNyZWF0aW9uIGRhdGVpMTY0NzcwNDk4M2U0Omlu

2022-03-19 16:49:45.527 +01:00 [DBG] RdtClient.Service.Services.TorrentRunner: Updating torrent info from Real-Debrid
2022-03-19 16:49:45.643 +01:00 [DBG] RdtClient.Service.Services.TorrentRunner: Finished updating torrent info from Real-Debrid, next update in 10 seconds
2022-03-19 16:49:45.643 +01:00 [DBG] RdtClient.Service.Services.TorrentRunner: Processing 1 torrents
2022-03-19 16:49:45.643 +01:00 [DBG] RdtClient.Service.Services.TorrentRunner: Processing for torrent  (0 -  0%) (d0714f1c-c51c-4b9e-b29e-5171da364c90)
2022-03-19 16:49:46.646 +01:00 [DBG] RdtClient.Service.Services.TorrentRunner: Processing 1 torrents
2022-03-19 16:49:46.646 +01:00 [DBG] RdtClient.Service.Services.TorrentRunner: Processing for torrent  (0 -  0%) (d0714f1c-c51c-4b9e-b29e-5171da364c90)
2022-03-19 16:49:47.648 +01:00 [DBG] RdtClient.Service.Services.TorrentRunner: Processing 1 torrents
2022-03-19 16:49:47.648 +01:00 [DBG] RdtClient.Service.Services.TorrentRunner: Processing for torrent  (0 -  0%) (d0714f1c-c51c-4b9e-b29e-5171da364c90)
2022-03-19 16:49:48.650 +01:00 [DBG] RdtClient.Service.Services.TorrentRunner: Processing 1 torrents
2022-03-19 16:49:48.651 +01:00 [DBG] RdtClient.Service.Services.TorrentRunner: Processing for torrent  (0 -  0%) (d0714f1c-c51c-4b9e-b29e-5171da364c90)
2022-03-19 16:49:49.652 +01:00 [DBG] RdtClient.Service.Services.TorrentRunner: Processing 1 torrents
2022-03-19 16:49:49.652 +01:00 [DBG] RdtClient.Service.Services.TorrentRunner: Processing for torrent  (0 -  0%) (d0714f1c-c51c-4b9e-b29e-5171da364c90)
2022-03-19 16:49:50.654 +01:00 [DBG] RdtClient.Service.Services.TorrentRunner: Processing 1 torrents
2022-03-19 16:49:50.654 +01:00 [DBG] RdtClient.Service.Services.TorrentRunner: Processing for torrent  (0 -  0%) (d0714f1c-c51c-4b9e-b29e-5171da364c90)
2022-03-19 16:49:51.656 +01:00 [DBG] RdtClient.Service.Services.TorrentRunner: Processing 1 torrents
2022-03-19 16:49:51.656 +01:00 [DBG] RdtClient.Service.Services.TorrentRunner: Processing for torrent  (0 -  0%) (d0714f1c-c51c-4b9e-b29e-5171da364c90)
2022-03-19 16:49:52.658 +01:00 [DBG] RdtClient.Service.Services.TorrentRunner: Processing 1 torrents
2022-03-19 16:49:52.658 +01:00 [DBG] RdtClient.Service.Services.TorrentRunner: Processing for torrent  (0 -  0%) (d0714f1c-c51c-4b9e-b29e-5171da364c90)
2022-03-19 16:49:53.659 +01:00 [DBG] RdtClient.Service.Services.TorrentRunner: Processing 1 torrents
2022-03-19 16:49:53.660 +01:00 [DBG] RdtClient.Service.Services.TorrentRunner: Processing for torrent  (0 -  0%) (d0714f1c-c51c-4b9e-b29e-5171da364c90)
2022-03-19 16:49:54.662 +01:00 [DBG] RdtClient.Service.Services.TorrentRunner: Processing 1 torrents
2022-03-19 16:49:54.662 +01:00 [DBG] RdtClient.Service.Services.TorrentRunner: Processing for torrent  (0 -  0%) (d0714f1c-c51c-4b9e-b29e-5171da364c90)
2022-03-19 16:49:55.664 +01:00 [DBG] RdtClient.Service.Services.TorrentRunner: Updating torrent info from Real-Debrid
2022-03-19 16:49:55.719 +01:00 [DBG] RdtClient.Service.Services.TorrentRunner: Finished updating torrent info from Real-Debrid, next update in 10 seconds
2022-03-19 16:49:55.719 +01:00 [DBG] RdtClient.Service.Services.TorrentRunner: Processing 1 torrents
2022-03-19 16:49:55.719 +01:00 [DBG] RdtClient.Service.Services.TorrentRunner: Processing for torrent  (0 -  0%) (d0714f1c-c51c-4b9e-b29e-5171da364c90)
2022-03-19 16:49:56.721 +01:00 [DBG] RdtClient.Service.Services.TorrentRunner: Processing 1 torrents
2022-03-19 16:49:56.722 +01:00 [DBG] RdtClient.Service.Services.TorrentRunner: Processing for torrent  (0 -  0%) (d0714f1c-c51c-4b9e-b29e-5171da364c90)
2022-03-19 16:49:57.724 +01:00 [DBG] RdtClient.Service.Services.TorrentRunner: Processing 1 torrents
2022-03-19 16:49:57.724 +01:00 [DBG] RdtClient.Service.Services.TorrentRunner: Processing for torrent  (0 -  0%) (d0714f1c-c51c-4b9e-b29e-5171da364c90)
2022-03-19 16:49:58.726 +01:00 [DBG] RdtClient.Service.Services.TorrentRunner: Processing 1 torrents
2022-03-19 16:49:58.726 +01:00 [DBG] RdtClient.Service.Services.TorrentRunner: Processing for torrent  (0 -  0%) (d0714f1c-c51c-4b9e-b29e-5171da364c90)
2022-03-19 16:49:59.728 +01:00 [DBG] RdtClient.Service.Services.TorrentRunner: Processing 1 torrents
2022-03-19 16:49:59.728 +01:00 [DBG] RdtClient.Service.Services.TorrentRunner: Processing for torrent  (0 -  0%) (d0714f1c-c51c-4b9e-b29e-5171da364c90)
2022-03-19 16:50:00.730 +01:00 [DBG] RdtClient.Service.Services.TorrentRunner: Processing 1 torrents
2022-03-19 16:50:00.730 +01:00 [DBG] RdtClient.Service.Services.TorrentRunner: Processing for torrent  (0 -  0%) (d0714f1c-c51c-4b9e-b29e-5171da364c90)
2022-03-19 16:50:01.732 +01:00 [DBG] RdtClient.Service.Services.TorrentRunner: Processing 1 torrents
2022-03-19 16:50:01.733 +01:00 [DBG] RdtClient.Service.Services.TorrentRunner: Processing for torrent  (0 -  0%) (d0714f1c-c51c-4b9e-b29e-5171da364c90)
2022-03-19 16:50:02.735 +01:00 [DBG] RdtClient.Service.Services.TorrentRunner: Processing 1 torrents
2022-03-19 16:50:02.735 +01:00 [DBG] RdtClient.Service.Services.TorrentRunner: Processing for torrent  (0 -  0%) (d0714f1c-c51c-4b9e-b29e-5171da364c90)
2022-03-19 16:50:03.737 +01:00 [DBG] RdtClient.Service.Services.TorrentRunner: Processing 1 torrents
2022-03-19 16:50:03.737 +01:00 [DBG] RdtClient.Service.Services.TorrentRunner: Processing for torrent  (0 -  0%) (d0714f1c-c51c-4b9e-b29e-5171da364c90)
2022-03-19 16:50:04.739 +01:00 [DBG] RdtClient.Service.Services.TorrentRunner: Processing 1 torrents
2022-03-19 16:50:04.739 +01:00 [DBG] RdtClient.Service.Services.TorrentRunner: Processing for torrent  (0 -  0%) (d0714f1c-c51c-4b9e-b29e-5171da364c90)
2022-03-19 16:50:05.741 +01:00 [DBG] RdtClient.Service.Services.TorrentRunner: Updating torrent info from Real-Debrid
2022-03-19 16:50:05.868 +01:00 [DBG] RdtClient.Service.Services.TorrentRunner: Finished updating torrent info from Real-Debrid, next update in 10 seconds
2022-03-19 16:50:05.868 +01:00 [DBG] RdtClient.Service.Services.TorrentRunner: Processing 1 torrents
2022-03-19 16:50:05.868 +01:00 [DBG] RdtClient.Service.Services.TorrentRunner: Processing for torrent  (0 -  0%) (d0714f1c-c51c-4b9e-b29e-5171da364c90)
2022-03-19 16:50:06.870 +01:00 [DBG] RdtClient.Service.Services.TorrentRunner: Processing 1 torrents
2022-03-19 16:50:06.870 +01:00 [DBG] RdtClient.Service.Services.TorrentRunner: Processing for torrent  (0 -  0%) (d0714f1c-c51c-4b9e-b29e-5171da364c90)
2022-03-19 16:50:07.873 +01:00 [DBG] RdtClient.Service.Services.TorrentRunner: Processing 1 torrents
2022-03-19 16:50:07.873 +01:00 [DBG] RdtClient.Service.Services.TorrentRunner: Processing for torrent  (0 -  0%) (d0714f1c-c51c-4b9e-b29e-5171da364c90)
2022-03-19 16:50:08.875 +01:00 [DBG] RdtClient.Service.Services.TorrentRunner: Processing 1 torrents
2022-03-19 16:50:08.875 +01:00 [DBG] RdtClient.Service.Services.TorrentRunner: Processing for torrent  (0 -  0%) (d0714f1c-c51c-4b9e-b29e-5171da364c90)
2022-03-19 16:50:09.877 +01:00 [DBG] RdtClient.Service.Services.TorrentRunner: Processing 1 torrents
2022-03-19 16:50:09.877 +01:00 [DBG] RdtClient.Service.Services.TorrentRunner: Processing for torrent  (0 -  0%) (d0714f1c-c51c-4b9e-b29e-5171da364c90)
2022-03-19 16:50:10.879 +01:00 [DBG] RdtClient.Service.Services.TorrentRunner: Processing 1 torrents
2022-03-19 16:50:10.879 +01:00 [DBG] RdtClient.Service.Services.TorrentRunner: Processing for torrent  (0 -  0%) (d0714f1c-c51c-4b9e-b29e-5171da364c90)
2022-03-19 16:50:11.881 +01:00 [DBG] RdtClient.Service.Services.TorrentRunner: Processing 1 torrents
2022-03-19 16:50:11.881 +01:00 [DBG] RdtClient.Service.Services.TorrentRunner: Processing for torrent  (0 -  0%) (d0714f1c-c51c-4b9e-b29e-5171da364c90)
2022-03-19 16:50:12.885 +01:00 [DBG] RdtClient.Service.Services.TorrentRunner: Processing 1 torrents
2022-03-19 16:50:12.885 +01:00 [DBG] RdtClient.Service.Services.TorrentRunner: Processing for torrent  (0 -  0%) (d0714f1c-c51c-4b9e-b29e-5171da364c90)
2022-03-19 16:50:13.887 +01:00 [DBG] RdtClient.Service.Services.TorrentRunner: Processing 1 torrents
2022-03-19 16:50:13.887 +01:00 [DBG] RdtClient.Service.Services.TorrentRunner: Processing for torrent  (0 -  0%) (d0714f1c-c51c-4b9e-b29e-5171da364c90)
2022-03-19 16:50:14.890 +01:00 [DBG] RdtClient.Service.Services.TorrentRunner: Processing 1 torrents
2022-03-19 16:50:14.892 +01:00 [DBG] RdtClient.Service.Services.TorrentRunner: Processing for torrent  (0 -  0%) (d0714f1c-c51c-4b9e-b29e-5171da364c90)
2022-03-19 16:50:15.894 +01:00 [DBG] RdtClient.Service.Services.TorrentRunner: Updating torrent info from Real-Debrid
2022-03-19 16:50:16.008 +01:00 [DBG] RdtClient.Service.Services.TorrentRunner: Finished updating torrent info from Real-Debrid, next update in 10 seconds

**Comment by rogerfar** [comment]
I fixed the error that I could see in the logs, for some reason it didn't have a torrent name yet.

Can you check with the latest version if the issue persists?

**Comment by Pommefrais3** [comment]
Thanks you for your quick reply.
Since the last version (2.0.11), I no longer systematically have these errors but they can still occur from time to time.

**Comment by rogerfar** [comment]
Ok let me know if it still happens regularly, then I will have to look again.
