### ISSUE TITLE
Crashes no matter what changes I make. 

### ISSUE THREAD

**Issue by evolutionaryman** [rogerfar/rdt-client#131]
The program crashes out no matter what settings I use. Not sure what to do. I did // the slashes. Any clues?

**What version are you using?**
2.0.12

**What OS are you running?**
Edition	Windows 10 Pro
Version	20H2
OS build	19042.1586
Experience	Windows Feature Experience Pack 120.2212.4170.0

**Are you using Docker or as a service?**
As a service

**Please attach a log file here with the log setting set to debug**
[rdtclient.log](https://github.com/rogerfar/rdt-client/files/8420443/rdtclient.log)

---
I installed the software in the directory "C:\RdtClient"

--------
Appsetting is missing the double // due to how formatting is working on git. 
{
  "Logging": {
    "File": {
      "Path": "C:\\RdtClient\\db\\rdtclient.log",
      "Append": "True",
      "FileSizeLimitBytes": 5242880,
      "MaxRollingFiles": 5
    }
  },
  "Database": {
    "Path": "C:\\RdtClient\\db\\rdtclient.db"
  },
  "AllowedHosts": "*",
  "HostUrl": "http://0.0.0.0:6500"
}

-----

After deleting the entire directory and just keeping the appsettings file

I get this error: 
2022-04-05 13:20:16.914 -04:00 [ERR] Microsoft.EntityFrameworkCore.Database.Connection: An error occurred using the connection to database 'main' on server 'C:\RdtClient\db\rdtclient.db'.
2022-04-05 13:20:16.943 -04:00 [FTL] : Host terminated unexpectedly
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 14: 'unable to open database file'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteConnectionInternal..ctor(SqliteConnectionStringBuilder connectionOptions, SqliteConnectionPool pool)
   at Microsoft.Data.Sqlite.SqliteConnectionPool.GetConnection()
   at Microsoft.Data.Sqlite.SqliteConnectionFactory.GetConnection(SqliteConnection outerConnection)
   at Microsoft.Data.Sqlite.SqliteConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnection(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternal(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal.SqliteDatabaseCreator.Create()
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.CreateAsync(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.MigrateAsync(String targetMigration, CancellationToken cancellationToken)
   at RdtClient.Web.Program.Main(String[] args) in C:\Projects\rdt-client\server\RdtClient.Web\Program.cs:line 34

**Comment by profucius** [comment]
In your Path lines, change the \ symbols to double \\

So it becomes like C:\\RdtClient\\db\\

**Comment by evolutionaryman** [comment]
> In your Path lines, change the `\` symbols to double `\\`
> 
> So it becomes like `C:\\RdtClient\\db\\`

They are both double \ . GitHub changed it to a single one on here. That is for both the .log and the .db

**Comment by rogerfar** [comment]
Make sure that you give the path `C:\RdtClient\` the correct permissions. It looks like a permission error.

**Comment by evolutionaryman** [comment]
The cause of this headache was ESET security protection. Disabled it for 10 minutes and the program is golden. I have no clue why it was causing issues for this software.
