### ISSUE TITLE
Failed to import movie, Destination already exists

### ISSUE THREAD

**Issue by abhigunner** [rogerfar/rdt-client#152]
**What version are you using?** latest from docker

**Wat OS are you running?** Synology NAS

**Are you using Docker or as a service?**Docker

I am trying to use this in Radarr. The movie file itself downloads imports in the proper folder but I get an error "Failed to import movie, Destination already exists". If I manually remove from queue and force refresh then Radarr recognizes the file . Is there a setting I should use. Using normal Qbittorrent in docker with radarr works fine with no problems. I am using the same paths as the existing Qbittorrent download path.
![image](https://user-images.githubusercontent.com/106907515/172043608-49563ed4-901a-4883-a57c-0422501c3c60.png)

**Comment by rogerfar** [comment]
Please post logs in debug mode.

**Comment by abhigunner** [comment]
[rdtclient.log](https://github.com/rogerfar/rdt-client/files/8840767/rdtclient.log)
I should add I am using hardlinks using TRaSH Guides.

**Comment by rogerfar** [comment]
Can you turn on debug.

**Comment by abhigunner** [comment]
[rdtclient (1).log](https://github.com/rogerfar/rdt-client/files/8842481/rdtclient.1.log)
Hope this is correct

**Comment by rogerfar** [comment]
Yes that works. But I don't see anything unusual happening here. Did you check the debug logs of Radarr? Because this kinda smells like a permission issue. Maybe Radarr isn't allowed to delete the torrent?

**Comment by abhigunner** [comment]
Following is what I think is the relevant part from Radarr Logs. It does say permission denied. However when I download from my normal Qbittorrent, it also saves in the same folder ie /data/torrents/movies/ and radarr can import from there.

I used your docker compose example. Should I have added PGId and PUID fields? Sorry I am not very proficient in docker permissions.






2022-06-06 02:31:01.5|Info|ReleaseSearchService|Searching indexers for [Father Stu]. 11 active indexers
2022-06-06 02:31:04.9|Info|DownloadDecisionMaker|Processing 87 releases
2022-06-06 02:31:17.7|Info|DownloadService|Report sent to RealDebrid. Father.Stu.2022.1080p.WEBRip.x264-RARBG
2022-06-06 02:32:41.3|Warn|ImportApprovedMovie|Couldn't import movie /data/torrents/movies/Father.Stu.2022.1080p.WEBRip.x264-RARBG/Father.Stu.2022.1080p.WEBRip.x264-RARBG.mp4

[v4.1.0.6175] System.UnauthorizedAccessException: Access to the path '/data/torrents/movies/Father.Stu.2022.1080p.WEBRip.x264-RARBG/Father.Stu.2022.1080p.WEBRip.x264-RARBG.mp4' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.FileSystem.DeleteFile(String fullPath)
   at NzbDrone.Common.Disk.DiskProviderBase.DeleteFile(String path) in D:\a\1\s\src\NzbDrone.Common\Disk\DiskProviderBase.cs:line 199
   at NzbDrone.Common.Disk.DiskTransferService.TransferFile(String sourcePath, String targetPath, TransferMode mode, Boolean overwrite) in D:\a\1\s\src\NzbDrone.Common\Disk\DiskTransferService.cs:line 296
   at NzbDrone.Core.MediaFiles.MovieFileMovingService.TransferFile(MovieFile movieFile, Movie movie, String destinationFilePath, TransferMode mode) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\MovieFileMovingService.cs:line 117
   at NzbDrone.Core.MediaFiles.MovieFileMovingService.MoveMovieFile(MovieFile movieFile, LocalMovie localMovie) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\MovieFileMovingService.cs:line 79
   at NzbDrone.Core.MediaFiles.UpgradeMediaFileService.UpgradeMovieFile(MovieFile movieFile, LocalMovie localMovie, Boolean copyOnly) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\UpgradeMediaFileService.cs:line 75
   at NzbDrone.Core.MediaFiles.MovieImport.ImportApprovedMovie.Import(List`1 decisions, Boolean newDownload, DownloadClientItem downloadClientItem, ImportMode importMode) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\MovieImport\ImportApprovedMovie.cs:line 123


2022-06-06 02:32:45.3|Warn|ImportApprovedMovie|Couldn't import movie /data/torrents/movies/Father.Stu.2022.1080p.WEBRip.x264-RARBG/Father.Stu.2022.1080p.WEBRip.x264-RARBG.mp4

[v4.1.0.6175] NzbDrone.Common.Disk.DestinationAlreadyExistsException: Destination /data/media/movies/Father Stu (2022)/Father.Stu.2022.1080p.WEBRip.x264-RARBG.mp4 already exists.
   at NzbDrone.Common.Disk.DiskTransferService.ClearTargetPath(String sourcePath, String targetPath, Boolean overwrite) in D:\a\1\s\src\NzbDrone.Common\Disk\DiskTransferService.cs:line 403
   at NzbDrone.Common.Disk.DiskTransferService.TransferFile(String sourcePath, String targetPath, TransferMode mode, Boolean overwrite) in D:\a\1\s\src\NzbDrone.Common\Disk\DiskTransferService.cs:line 296
   at NzbDrone.Core.MediaFiles.MovieFileMovingService.TransferFile(MovieFile movieFile, Movie movie, String destinationFilePath, TransferMode mode) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\MovieFileMovingService.cs:line 134
   at NzbDrone.Core.MediaFiles.MovieFileMovingService.MoveMovieFile(MovieFile movieFile, LocalMovie localMovie) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\MovieFileMovingService.cs:line 79
   at NzbDrone.Core.MediaFiles.UpgradeMediaFileService.UpgradeMovieFile(MovieFile movieFile, LocalMovie localMovie, Boolean copyOnly) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\UpgradeMediaFileService.cs:line 51
   at NzbDrone.Core.MediaFiles.MovieImport.ImportApprovedMovie.Import(List`1 decisions, Boolean newDownload, DownloadClientItem downloadClientItem, ImportMode importMode) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\MovieImport\ImportApprovedMovie.cs:line 123

**Comment by rogerfar** [comment]
This is the error yes:
`[v4.1.0.6175] System.UnauthorizedAccessException: Access to the path '/data/torrents/movies/.mp4' is denied.`

I'm assuming that's not where the movie is actually located correct? Did you setup path mapping in the settings in both Radarr and RDT:

![image](https://user-images.githubusercontent.com/1142915/172231323-0eed5e64-6288-485c-9889-acf87b3e6289.png)

**Comment by abhigunner** [comment]
This is the mapped path in RDT
![image](https://user-images.githubusercontent.com/106907515/172251637-5da9b08c-34aa-4127-b4e1-30237993a9cd.png)

Also I tried downloading from my normal Qbitorrent and I have this error. File error alert. Torrent: "Father.Stu.2022.1080p.BluRay.H264.AAC-RARBG". File: "/data/torrents/movies/Father.Stu.2022.1080p.BluRay.H264.AAC-RARBG/Father.Stu.2022.1080p.BluRay.H264.AAC-RARBG.mp4". Reason: Father.Stu.2022.1080p.BluRay.H264.AAC-RARBG mkdir (/data/torrents/movies/Father.Stu.2022.1080p.BluRay.H264.AAC-RARBG/Father.Stu.2022.1080p.BluRay.H264.AAC-RARBG.mp4) error: Permission denied

So some permissions have screwed up. What can I do to correct them?

**Comment by rogerfar** [comment]
Are you running on a Linux host? If so, you need to pass the PUID and PGID through from the host:
https://github.com/rogerfar/rdt-client/blob/master/README-DOCKER.md#user--group-identifiers

**Comment by rogerfar** [comment]
And does QBittorrent / Radarr have the same permissions as those PGID? It might be an idea to have radarr/qbittorrent and rdtclient all use the same PID or at least make all users part of the same group.

**Comment by abhigunner** [comment]
Yeah all have the docker PUID PGID. Same permissions. And Radarr is able to copy that file to its directory. It just says unable to import.

**Comment by rogerfar** [comment]
Not sure, seems related to Radarr, if you search around a bit, there are quite a few issues about this:
https://www.reddit.com/r/radarr/comments/g3omrl/couldnt_import_moviedestination_already_exists/

**Comment by dewdrinker19** [comment]
I was having the exact same issue.  Radarr would successfully move the file to where it is supposed to go. Then the error of destination already exists happens.  The reason for me was Radarr did not have correct permission to the docker folder and was unable to delete the files from rdt-client after importing.  Once I gave radar read/write to the docker folder everything works great.  Amazing tool!

**Comment by abhigunner** [comment]
this is the permissions for Radarr container when I see them through terminal in the docker app in Synology DSM.

![image](https://user-images.githubusercontent.com/106907515/172703673-bdbcce9a-9c6b-4f87-8194-9d32b0140b6b.png)

Father STU is through RDT client.
Sonic is through Qbitorrent.

How can I make the permissions to be the same.

**Comment by dewdrinker19** [comment]
I don't know how to use terminal at all. I just went to Control Panel, Shares, clicked the Docker folder, set the system user for radarr to read/write and it worked.

The only thing I can't figure out at all is how to get Radarr to know a file is finished and ready to import so I don't have to manually go in and push refresh.

**Comment by rogerfar** [comment]
> The only thing I can't figure out at all is how to get Radarr to know a file is finished and ready to import so I don't have to manually go in and push refresh.

This should go automatically, but it can take a few minutes for it to pick up. Set logging to trace in Radarr and check the logs if anything stands out there.

**Comment by abhigunner** [comment]
I did chmod 777 movies in Radarr terminal and restarted the container and now it works. Thanks for all the help.

Now if I set this up in sonarr will the same issue come up?

**Comment by tanmaster** [comment]
Can the issue be reopened? I use separate users for rdtclient and sonarr (the users share the same group), each running in their own container. I have the problem that files downloaded via the rdtclient have `drwxr-xr-x` and sonarr cannot move/delete them because of missing group write permission. 

I know the alternative would be to create a single user for rdtclient, sonarr and radarr, but I want to try this approach first.

Is there a way to make the downloaded files being created with `drwxrwxr-x` instead?

**Comment by tanmaster** [comment]
> Is there a way to make the downloaded files being created with drwxrwxr-x instead?

FWIW, I managed to achieve my goal using these two options on my download path:

<img width="1398" alt="image" src="https://user-images.githubusercontent.com/3981445/230719481-bdebe608-7f8c-412d-bc62-061f00547fb4.png">
