### ISSUE TITLE
crashing after most recent pull

### ISSUE THREAD

**Issue by m-ayub** [rogerfar/rdt-client#153]
2.0.17

Synology NAS vDSM 7.0.1-42218 Update 3

Docker

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 01-migrations: executing... 
[migrations] started
[migrations] no migrations found
[cont-init.d] 01-migrations: exited 0.
[cont-init.d] 02-tamper-check: executing... 
[cont-init.d] 02-tamper-check: exited 0.
[cont-init.d] 10-adduser: executing... 

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/

Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1026
User gid:    100
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
Setting permissions
[cont-init.d] 30-config: exited 0.
[cont-init.d] 90-custom-folders: executing... 
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
Changing to /app folder
Starting rtdclient
[services.d] done.
[17:08:09 WRN] Using an in-memory repository. Keys will not be persisted to storage.
[17:08:09 WRN] Neither user profile nor HKLM registry available. Using an ephemeral key repository. Protected data will be unavailable when application exits.
[17:08:10 WRN] No XML encryptor configured. Key {6e791c27-3b1b-4470-b38f-2b52780f09d4} may be persisted to storage in unencrypted form.
[17:08:10 WRN] Starting host on version 2.0.17.0
[17:08:24 ERR] BackgroundService failed
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at RdtClient.Service.BackgroundServices.ProviderUpdater.ExecuteAsync(CancellationToken stoppingToken) in /appserver/server/RdtClient.Service/BackgroundServices/ProviderUpdater.cs:line 25
   at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService backgroundService)
Changing to /app folder
Starting rtdclient
[17:08:26 WRN] Using an in-memory repository. Keys will not be persisted to storage.
[17:08:26 WRN] Neither user profile nor HKLM registry available. Using an ephemeral key repository. Protected data will be unavailable when application exits.
[17:08:26 WRN] No XML encryptor configured. Key {a147ddb9-0ed5-4cc1-8c28-f7715cd6d6a9} may be persisted to storage in unencrypted form.
[17:08:26 WRN] Starting host on version 2.0.17.0
[17:08:30 ERR] BackgroundService failed
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at RdtClient.Service.BackgroundServices.ProviderUpdater.ExecuteAsync(CancellationToken stoppingToken) in /appserver/server/RdtClient.Service/BackgroundServices/ProviderUpdater.cs:line 25
   at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService backgroundService)
Changing to /app folder
Starting rtdclient
[17:08:32 WRN] Using an in-memory repository. Keys will not be persisted to storage.
[17:08:32 WRN] Neither user profile nor HKLM registry available. Using an ephemeral key repository. Protected data will be unavailable when application exits.
[17:08:32 WRN] No XML encryptor configured. Key {796a05d3-6ebe-4f0d-8a37-788400df800d} may be persisted to storage in unencrypted form.
[17:08:32 WRN] Starting host on version 2.0.17.0
[17:08:36 ERR] BackgroundService failed
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at RdtClient.Service.BackgroundServices.ProviderUpdater.ExecuteAsync(CancellationToken stoppingToken) in /appserver/server/RdtClient.Service/BackgroundServices/ProviderUpdater.cs:line 25
   at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService backgroundService)
Changing to /app folder
Starting rtdclient
[17:08:37 WRN] Using an in-memory repository. Keys will not be persisted to storage.
[17:08:37 WRN] Neither user profile nor HKLM registry available. Using an ephemeral key repository. Protected data will be unavailable when application exits.
[17:08:37 WRN] No XML encryptor configured. Key {77dfa672-9cab-4ac0-94d8-29dcfd4b6d94} may be persisted to storage in unencrypted form.
[17:08:37 WRN] Starting host on version 2.0.17.0
[17:08:42 ERR] BackgroundService failed
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at RdtClient.Service.BackgroundServices.ProviderUpdater.ExecuteAsync(CancellationToken stoppingToken) in /appserver/server/RdtClient.Service/BackgroundServices/ProviderUpdater.cs:line 25
   at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService backgroundService)
Changing to /app folder
Starting rtdclient
[17:08:44 WRN] Using an in-memory repository. Keys will not be persisted to storage.
[17:08:44 WRN] Neither user profile nor HKLM registry available. Using an ephemeral key repository. Protected data will be unavailable when application exits.
[17:08:44 WRN] No XML encryptor configured. Key {9c505081-5229-47c8-bfdc-13e67beee879} may be persisted to storage in unencrypted form.
[17:08:44 WRN] Starting host on version 2.0.17.0
[17:08:49 ERR] BackgroundService failed
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at RdtClient.Service.BackgroundServices.ProviderUpdater.ExecuteAsync(CancellationToken stoppingToken) in /appserver/server/RdtClient.Service/BackgroundServices/ProviderUpdater.cs:line 25
   at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService backgroundService)
Changing to /app folder
Starting rtdclient
[17:08:51 WRN] Using an in-memory repository. Keys will not be persisted to storage.
[17:08:51 WRN] Neither user profile nor HKLM registry available. Using an ephemeral key repository. Protected data will be unavailable when application exits.
[17:08:51 WRN] No XML encryptor configured. Key {2e598eed-fed4-46a2-ad8c-56fd3fae8c64} may be persisted to storage in unencrypted form.
[17:08:51 WRN] Starting host on version 2.0.17.0
[17:08:56 ERR] BackgroundService failed
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at RdtClient.Service.BackgroundServices.ProviderUpdater.ExecuteAsync(CancellationToken stoppingToken) in /appserver/server/RdtClient.Service/BackgroundServices/ProviderUpdater.cs:line 25
   at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService backgroundService)
Changing to /app folder

**Comment by m-ayub** [comment]
deleted the db and it's working. going to set it up again
