### ISSUE TITLE
Client no longer selects files within torrents

### ISSUE THREAD

**Issue by jackkerouac** [rogerfar/rdt-client#156]
Running in a Docker container on a Raspberry Pi 4. Files within torrents are not selected. When I go to RealDebrid, it pops up the torrents so I can choose the files within.

This started within the past two weeks - up until then, everything was fine.

Logs (before and after restarting):

`2022-06-16T13:17:19.2007241Z Maximum destructuring depth reached.
2022-06-16T13:17:19.2007883Z Maximum destructuring depth reached.
2022-06-16T13:17:19.2008628Z Maximum destructuring depth reached.
2022-06-16T13:17:19.2009548Z Maximum destructuring depth reached.
2022-06-16T13:17:19.2010234Z Maximum destructuring depth reached.
2022-06-16T13:17:19.2010876Z Maximum destructuring depth reached.
2022-06-16T13:17:19.2011509Z Maximum destructuring depth reached.
2022-06-16T13:17:19.2012377Z Maximum destructuring depth reached.
2022-06-16T13:17:19.2013063Z Maximum destructuring depth reached.
2022-06-16T13:17:19.2013667Z Maximum destructuring depth reached.
2022-06-16T13:17:19.2014251Z Maximum destructuring depth reached.
2022-06-16T13:17:19.2015011Z Maximum destructuring depth reached.
2022-06-16T13:17:19.2015656Z Maximum destructuring depth reached.
2022-06-16T13:17:19.2016272Z Maximum destructuring depth reached.
2022-06-16T13:17:19.2016889Z Maximum destructuring depth reached.
[09:17:06 ERR] Unexpected error occurred in TorrentDownloadManager.Tick: The database operation was expected to affect 1 row(s), but actually affected 0 row(s); data may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=527962 for information on understanding and handling optimistic concurrency exceptions.
Microsoft.EntityFrameworkCore.DbUpdateConcurrencyException: The database operation was expected to affect 1 row(s), but actually affected 0 row(s); data may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=527962 for information on understanding and handling optimistic concurrency exceptions.
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ThrowAggregateUpdateConcurrencyException(Int32 commandIndex, Int32 expectedRowsAffected, Int32 rowsAffected)
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeResultSetWithoutPropagationAsync(Int32 commandIndex, RelationalDataReader reader, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeAsync(RelationalDataReader reader, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at RdtClient.Data.Data.TorrentData.UpdateComplete(Guid torrentId, String error, Nullable`1 datetime, Boolean retry)
   at RdtClient.Service.Services.Torrents.UpdateComplete(Guid torrentId, String error, DateTimeOffset datetime, Boolean retry) in /appserver/server/RdtClient.Service/Services/Torrents.cs:line 519
   at RdtClient.Service.Services.TorrentRunner.Tick() in /appserver/server/RdtClient.Service/Services/TorrentRunner.cs:line 559
   at RdtClient.Service.BackgroundServices.TaskRunner.ExecuteAsync(CancellationToken stoppingToken) in /appserver/server/RdtClient.Service/BackgroundServices/TaskRunner.cs:line 37
[09:24:12 WRN] 101: /hub
[09:40:54 WRN] 101: /hub
[09:40:54 ERR] Unexpected error occurred in ProviderUpdater: A task was canceled.
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at RdtClient.Service.BackgroundServices.WatchFolderChecker.ExecuteAsync(CancellationToken stoppingToken) in /appserver/server/RdtClient.Service/BackgroundServices/WatchFolderChecker.cs:line 40
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 01-migrations: executing... 
[migrations] started
[migrations] no migrations found
[cont-init.d] 01-migrations: exited 0.
[cont-init.d] 02-tamper-check: executing... 
[cont-init.d] 02-tamper-check: exited 0.
[cont-init.d] 10-adduser: executing... 
usermod: no changes

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/

Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
Setting permissions
[cont-init.d] 30-config: exited 0.
[cont-init.d] 90-custom-folders: executing... 
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Changing to /app folder
Starting rtdclient
[09:42:01 WRN] Using an in-memory repository. Keys will not be persisted to storage.
[09:42:01 WRN] Neither user profile nor HKLM registry available. Using an ephemeral key repository. Protected data will be unavailable when application exits.
[09:42:01 WRN] No XML encryptor configured. Key {7817976c-4980-4543-b7c0-369a6e24b656} may be persisted to storage in unencrypted form.
[09:42:02 WRN] Starting host on version 2.0.17.0
[09:42:21 WRN] The query uses the 'First'/'FirstOrDefault' operator without 'OrderBy' and filter operators. This may lead to unpredictable results.
[09:42:21 WRN] 401: /api/v2/torrents/info
`

**Comment by ofifoto** [comment]
I'm seeing this too; no files are selected and I have to go to the website to do it

**Comment by ddpruel** [comment]
I'm also noticing this issue

**Comment by rogerfar** [comment]
Could you post a log file too in debug mode? I'm not really seeing anything obvious that would cause it.

**Comment by androo-d** [comment]
I am also having this issue... I have "Only download available files on debrid provider " and "Minimum file size to download" enabled but only the default files are being selected on real-debrid.com. RDTClient is giving hte download status as "Torrent waiting for file selection". Any update for this would be greatly appreciated.

**Comment by rogerfar** [comment]
Again,
> Could you post a log file too in debug mode? I'm not really seeing anything obvious that would cause it.
