### ISSUE TITLE
Watch Folder stops adding after error

### ISSUE THREAD

**Issue by cavedog8** [rogerfar/rdt-client#160]
First of all, let me just thank you for the amazing software you made!

**What version are you using?**

Version 2.0.17

**Wat OS are you running?**

Ubuntu Server 20.04 and Windows 11

**Are you using Docker or as a service?**

Docker Compose for Ubuntu and running as a service on Windows 11.

When you set the watch folder in the watch section it adds files up until an infringing torrent fails to add then it stops and doesn't add torrents anymore. As soon as you remove the problem/infringing .torrent file from the folder the importing continues.

Suggestion: Move failed/infringing torrent files to a folder called failed and allow the processing to continue.

![Screenshot 2022-06-21 094231](https://user-images.githubusercontent.com/64382634/174746461-4bef3990-d156-4d85-ba52-9b1a78ce3a81.png)
![Screenshot 2022-06-21 094212](https://user-images.githubusercontent.com/64382634/174746466-c8005b33-0f84-4d1b-85da-131256d1ce63.png)

**Comment by cavedog8** [comment]
Can't seem to figure out what file is infringing.


2022-07-01 23:23:04.133 +02:00 [ERR] RdtClient.Service.BackgroundServices.WatchFolderChecker: Unexpected error occurred in ProviderUpdater: infringing_file
RDNET.Exceptions.RealDebridException: infringing_file
   at RDNET.Apis.Requests.Request(String baseUrl, String url, String headerOutput, Boolean requireAuthentication, RequestType requestType, HttpContent data, CancellationToken cancellationToken)
   at RDNET.Apis.Requests.Request[T](String baseUrl, String url, Boolean requireAuthentication, RequestType requestType, HttpContent data, CancellationToken cancellationToken)
   at RDNET.Apis.Requests.PutRequestAsync[T](String url, Byte[] file, Boolean requireAuthentication, CancellationToken cancellationToken)
   at RDNET.Apis.TorrentsApi.AddFileAsync(Byte[] file, CancellationToken cancellationToken)
   at RdtClient.Service.Services.TorrentClients.RealDebridTorrentClient.AddFile(Byte[] bytes) in /appserver/server/RdtClient.Service/Services/TorrentClients/RealDebridTorrentClient.cs:line 136
   at RdtClient.Service.Services.Torrents.UploadFile(Byte[] bytes, Torrent torrent) in /appserver/server/RdtClient.Service/Services/Torrents.cs:line 150
   at RdtClient.Service.BackgroundServices.WatchFolderChecker.ExecuteAsync(CancellationToken stoppingToken) in /appserver/server/RdtClient.Service/BackgroundServices/WatchFolderChecker.cs:line 97
2022-07-01 23:23:06.166 +02:00 [ERR] RdtClient.Service.BackgroundServices.WatchFolderChecker: Unexpected error occurred in ProviderUpdater: infringing_file

**Comment by rudnypc** [comment]
’m dealing with the same problem as you.

**Comment by rogerfar** [comment]
I added a fix for this in the next version where it moves the file to the "error" folder if it encounters an error.

**Comment by kudddyyy** [comment]
This brings a side effect, when real debrid max number of download slots, everything goes in the error folder, even the torrents that are cached by real debrid.

A dirty fix is adding back all the files from the error folder back to the main one, except the ones that are not cached on real debrid. Any better ideas ?

**Comment by rogerfar** [comment]
Sorry, I'm not following, when does this happen exactly?

**Comment by rogerfar** [comment]
If it's still an issue please file a new issue with new logs.
