### ISSUE TITLE
Setting permissions

### ISSUE THREAD

**Issue by janaxhell** [rogerfar/rdt-client#167]
**What version are you using?**
2.0.17
**Wat OS are you running?**
OMV 6
**Are you using Docker or as a service?**
Yes
**Please attach a log file here with the log setting set to debug**
[_rdtclient_logs.txt](https://github.com/rogerfar/rdt-client/files/9147324/_rdtclient_logs.txt)

Each time I reboot OMV, rdt-client hangs for 10/15 minutes "setting permissions". 
How do I fix that?

**Comment by janaxhell** [comment]
You mean /watch folder? How? That is a folder on a NTFS HDD. I actually don't need it, can I just remove it?

**Comment by janaxhell** [comment]
It didn't change: I have cleared /watch path and Saved changes, then set logging to Debug and saved changes, then restarted container, but it does exactly the same as before:
[_rdtclient_logs2.txt](https://github.com/rogerfar/rdt-client/files/9150207/_rdtclient_logs2.txt)

**Comment by janaxhell** [comment]
Updated logs after 15 minutes of Setting permissions:
[_rdtclient_logs3.txt](https://github.com/rogerfar/rdt-client/files/9150286/_rdtclient_logs3.txt)

**Comment by rogerfar** [comment]
There's nothing odd in the RDT logs, can you somehow enable more logging for Docker / linuxserver / OMV?

**Comment by janaxhell** [comment]
I honestly don't know how to do that, I'm getting the logs from Portainer. 
For that matters, this is my stack:

> version: '3.3'
services:
    rdtclient:
        container_name: rdtclient
        environment:
        - PUID=998
        - PGID=100
        volumes:
            - '/srv/dev-disk-by-uuid-2628F1C228F19153/data:/data'
            - '/srv/dev-disk-by-uuid-A870CA6B70CA3FB4/data:/data2'
            - '/srv/dev-disk-by-uuid-5b67514d-485e-4306-873e-b1cbb54ccf99/Config/rdtclient:/data/db'
            - '/srv/dev-disk-by-uuid-5b67514d-485e-4306-873e-b1cbb54ccf99/Config/rdtclient/config/:/config'
        image: rogerfar/rdtclient
        restart: always
        logging:
            driver: json-file
            options:
                max-size: 10m
        ports:
            - '6500:6500'

**Comment by rogerfar** [comment]
Looks like still a permission issue:

`Access to the path '/watch/processed' is denied.`

Make sure that the /watch/ path is mapped properly and that docker can read the folder.

**Comment by janaxhell** [comment]
But I haven't set any /watch folder neither in container nor app settings, nor in Radarr/Sonarr. I never use that. Do I have to set it in any case?
_Test download path permissions
Your download path looks good!_

**Comment by rogerfar** [comment]
That setting is blank by default, at one point it got set.

If you clear out the setting `Watch Path` it will not attempt to check for that directory anymore.

**Comment by janaxhell** [comment]
The only entry I see is "Check Interval: 3600". I might have tried that months ago. Is it that?

**Comment by rogerfar** [comment]
So this is blank?

![image](https://user-images.githubusercontent.com/1142915/186956210-8fcfa0e7-12cc-40a9-9ad8-fc5567417de8.png)

**Comment by janaxhell** [comment]
Yes, it's blank

**Comment by rogerfar** [comment]
Then really that error shouldn't happen anymore, does it still take long for a restart?

**Comment by janaxhell** [comment]
I don't think so, log just says 
2022-08-26T17:11:33.989638235Z 
2022-08-26T17:11:34.004684906Z [cont-init.d] 10-adduser: exited 0.
2022-08-26T17:11:34.006491445Z [cont-init.d] 30-config: executing... 
2022-08-26T17:11:34.011291478Z Setting permissions
and I hear the HDD thrashing. 
But as I said, that /watch entry was already blank since beginning of this whole thread.

**Comment by rogerfar** [comment]
How long does that take now?

Because it's only doing this command:
https://github.com/rogerfar/rdt-client/blob/cc7abc82ba22382a1ac608ace11b087c519a8427/root/etc/cont-init.d/30-config#L13

**Comment by janaxhell** [comment]
It is still thrashing as I'm writing, I'll try to update as soon as it stops.

**Comment by janaxhell** [comment]
This is the log in the upper part of Portainer Window:

2022-08-26T13:36:37.135723541Z [13:36:37 DBG] Waiting for downloads to complete. 0/1 complete for torrent Passion.in.the.Desert.1997.1080p.AMZN.WEBRip.DDP2.0.x264-ISA (154943247 - Ready 100%) (43f44b03-1128-44f0-8c22-49548672e339)
2022-08-26T13:36:38.138415003Z [13:36:38 DBG] TorrentRunner Tick Start, 1 active downloads, 0 active unpacks
2022-08-26T13:36:38.138471756Z [13:36:38 DBG] Processing 1 torrents
2022-08-26T13:36:38.138488899Z [13:36:38 DBG] Processing for torrent Passion.in.the.Desert.1997.1080p.AMZN.WEBRip.DDP2.0.x264-ISA (154943247 - Ready 100%) (43f44b03-1128-44f0-8c22-49548672e339)
2022-08-26T13:36:38.138504551Z [13:36:38 DBG] Waiting for downloads to complete. 0/1 complete for torrent Passion.in.the.Desert.1997.1080p.AMZN.WEBRip.DDP2.0.x264-ISA (154943247 - Ready 100%) (43f44b03-1128-44f0-8c22-49548672e339)
2022-08-26T13:36:39.136596503Z [13:36:39 DBG] TorrentRunner Tick Start, 1 active downloads, 0 active unpacks
2022-08-26T13:36:39.136613448Z [13:36:39 DBG] Processing 1 completed downloads
2022-08-26T13:36:39.137135374Z [13:36:39 DBG] Processing download for download Passion.in.the.Desert.1997.1080p.WEB-DL.DDP2.0.H.264-ISA.mkv 0% (6e95b6a7-814a-4f0e-bf2e-221ee3d74df0) for torrent Passion.in.the.Desert.1997.1080p.AMZN.WEBRip.DDP2.0.x264-ISA (154943247 - Ready 100%) (43f44b03-1128-44f0-8c22-49548672e339)
2022-08-26T13:36:39.137148521Z [13:36:39 DBG] Download finished successfully for download Passion.in.the.Desert.1997.1080p.WEB-DL.DDP2.0.H.264-ISA.mkv 0% (6e95b6a7-814a-4f0e-bf2e-221ee3d74df0) for torrent Passion.in.the.Desert.1997.1080p.AMZN.WEBRip.DDP2.0.x264-ISA (154943247 - Ready 100%) (43f44b03-1128-44f0-8c22-49548672e339)
2022-08-26T13:36:39.159831407Z [13:36:39 DBG] Removed from ActiveDownloadClients for download Passion.in.the.Desert.1997.1080p.WEB-DL.DDP2.0.H.264-ISA.mkv 0% (6e95b6a7-814a-4f0e-bf2e-221ee3d74df0) for torrent Passion.in.the.Desert.1997.1080p.AMZN.WEBRip.DDP2.0.x264-ISA (154943247 - Ready 100%) (43f44b03-1128-44f0-8c22-49548672e339)
2022-08-26T13:36:39.160162926Z [13:36:39 DBG] Processing 1 torrents
2022-08-26T13:36:39.160173604Z [13:36:39 DBG] Starting unpack for download Passion.in.the.Desert.1997.1080p.WEB-DL.DDP2.0.H.264-ISA.mkv 0% (6e95b6a7-814a-4f0e-bf2e-221ee3d74df0) for torrent Passion.in.the.Desert.1997.1080p.AMZN.WEBRip.DDP2.0.x264-ISA (154943247 - Ready 100%) (43f44b03-1128-44f0-8c22-49548672e339)
2022-08-26T13:36:39.160179553Z [13:36:39 DBG] Found file name Passion.in.the.Desert.1997.1080p.WEB-DL.DDP2.0.H.264-ISA.mkv for download Passion.in.the.Desert.1997.1080p.WEB-DL.DDP2.0.H.264-ISA.mkv 0% (6e95b6a7-814a-4f0e-bf2e-221ee3d74df0) for torrent Passion.in.the.Desert.1997.1080p.AMZN.WEBRip.DDP2.0.x264-ISA (154943247 - Ready 100%) (43f44b03-1128-44f0-8c22-49548672e339)
2022-08-26T13:36:39.160222491Z [13:36:39 DBG] No need to unpack, setting it as unpacked for download Passion.in.the.Desert.1997.1080p.WEB-DL.DDP2.0.H.264-ISA.mkv 0% (6e95b6a7-814a-4f0e-bf2e-221ee3d74df0) for torrent Passion.in.the.Desert.1997.1080p.AMZN.WEBRip.DDP2.0.x264-ISA (154943247 - Ready 100%) (43f44b03-1128-44f0-8c22-49548672e339)
2022-08-26T13:36:39.220049962Z [13:36:39 DBG] Processing for torrent Passion.in.the.Desert.1997.1080p.AMZN.WEBRip.DDP2.0.x264-ISA (154943247 - Ready 100%) (43f44b03-1128-44f0-8c22-49548672e339)
2022-08-26T13:36:39.220121741Z [13:36:39 DBG] All downloads complete, marking torrent as complete for torrent Passion.in.the.Desert.1997.1080p.AMZN.WEBRip.DDP2.0.x264-ISA (154943247 - Ready 100%) (43f44b03-1128-44f0-8c22-49548672e339)
2022-08-26T13:36:39.245493102Z [13:36:39 DBG] Not removing torrents or files for torrent Passion.in.the.Desert.1997.1080p.AMZN.WEBRip.DDP2.0.x264-ISA (154943247 - Ready 100%) (43f44b03-1128-44f0-8c22-49548672e339)
2022-08-26T13:37:02.104074574Z [13:37:02 DBG] Updating torrent info from Real-Debrid
2022-08-26T13:37:02.208657854Z [13:37:02 DBG] Finished updating torrent info from Real-Debrid, next update in 30 seconds
2022-08-26T13:37:29.987349503Z [13:37:29 DBG] Deleting for torrent Passion.in.the.Desert.1997.1080p.AMZN.WEBRip.DDP2.0.x264-ISA (154943247 - Ready 100%) (43f44b03-1128-44f0-8c22-49548672e339)
2022-08-26T13:37:29.991825140Z [13:37:29 DBG] Deleting RdtClient data for torrent Passion.in.the.Desert.1997.1080p.AMZN.WEBRip.DDP2.0.x264-ISA (154943247 - Ready 100%) (43f44b03-1128-44f0-8c22-49548672e339)
2022-08-26T13:37:29.997463114Z [13:37:29 DBG] Deleting RealDebrid Torrent for torrent Passion.in.the.Desert.1997.1080p.AMZN.WEBRip.DDP2.0.x264-ISA (154943247 - Ready 100%) (43f44b03-1128-44f0-8c22-49548672e339)
2022-08-26T13:37:30.078055822Z [13:37:30 DBG] Deleting local files in /data2/torrents/movies/Passion.in.the.Desert.1997.1080p.AMZN.WEBRip.DDP2.0.x264-ISA for torrent Passion.in.the.Desert.1997.1080p.AMZN.WEBRip.DDP2.0.x264-ISA (154943247 - Ready 100%) (43f44b03-1128-44f0-8c22-49548672e339)
2022-08-26T16:51:38.568024458Z [16:51:38 WRN] 401: /Api/Authentication/IsLoggedIn
2022-08-26T17:10:44.425841891Z [17:10:44 WRN] 101: /hub
2022-08-26T17:10:49.302119024Z [17:10:49 WRN] 101: /hub
2022-08-26T17:10:49.621100622Z [17:10:49 ERR] Unexpected error occurred in ProviderUpdater: A task was canceled.
2022-08-26T17:10:49.621120801Z System.Threading.Tasks.TaskCanceledException: A task was canceled.
2022-08-26T17:10:49.621131593Z    at RdtClient.Service.BackgroundServices.WatchFolderChecker.ExecuteAsync(CancellationToken stoppingToken) in /appserver/server/RdtClient.Service/BackgroundServices/WatchFolderChecker.cs:line 40
2022-08-26T17:10:53.280017166Z [cont-finish.d] executing container finish scripts...
2022-08-26T17:10:53.281017695Z [cont-finish.d] done.
2022-08-26T17:10:53.281239329Z [s6-finish] waiting for services.
2022-08-26T17:10:53.504707056Z [s6-finish] sending all processes the TERM signal.
2022-08-26T17:11:32.143762244Z [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
2022-08-26T17:11:32.554245342Z [s6-init] ensuring user provided files have correct perms...exited 0.
2022-08-26T17:11:32.555340458Z [fix-attrs.d] applying ownership & permissions fixes...
2022-08-26T17:11:32.555984104Z [fix-attrs.d] done.
2022-08-26T17:11:32.556678226Z [cont-init.d] executing container initialization scripts...
2022-08-26T17:11:32.560730727Z [cont-init.d] 01-envfile: executing... 
2022-08-26T17:11:32.737707693Z [cont-init.d] 01-envfile: exited 0.
2022-08-26T17:11:32.741068767Z [cont-init.d] 01-migrations: executing... 
2022-08-26T17:11:32.758575597Z [migrations] started
2022-08-26T17:11:32.758678955Z [migrations] no migrations found
2022-08-26T17:11:32.760310889Z [cont-init.d] 01-migrations: exited 0.
2022-08-26T17:11:32.763422462Z [cont-init.d] 02-tamper-check: executing... 
2022-08-26T17:11:32.986755234Z **** Potential tampering with custom scripts/services detected ****
2022-08-26T17:11:33.378001598Z **** Folder /config/custom-cont-init.d is moved to /config/custom-cont-init.d.iN4a8t_b ****
2022-08-26T17:11:33.382619540Z **** Folder /config/custom-services.d is moved to /config/custom-services.d.iN4a8t_b ****
2022-08-26T17:11:33.382705401Z **** The folders '/config/custom-cont-init.d' and '/config/custom-services.d'; and their contents need to all be owned by root to prevent root escalation inside the container!!! ****
2022-08-26T17:11:33.443385438Z [cont-init.d] 02-tamper-check: exited 0.
2022-08-26T17:11:33.446605879Z [cont-init.d] 10-adduser: executing... 
2022-08-26T17:11:33.965068504Z usermod: no changes

**Comment by rogerfar** [comment]
Is there a part missing? I don't see [cont-init.d] 30 starting.

**Comment by janaxhell** [comment]
This is all I can get from Portainer since early today

2022-08-26T13:36:37.135723541Z [13:36:37 DBG] Waiting for downloads to complete. 0/1 complete for torrent Passion.in.the.Desert.1997.1080p.AMZN.WEBRip.DDP2.0.x264-ISA (154943247 - Ready 100%) (43f44b03-1128-44f0-8c22-49548672e339)
2022-08-26T13:36:38.138415003Z [13:36:38 DBG] TorrentRunner Tick Start, 1 active downloads, 0 active unpacks
2022-08-26T13:36:38.138471756Z [13:36:38 DBG] Processing 1 torrents
2022-08-26T13:36:38.138488899Z [13:36:38 DBG] Processing for torrent Passion.in.the.Desert.1997.1080p.AMZN.WEBRip.DDP2.0.x264-ISA (154943247 - Ready 100%) (43f44b03-1128-44f0-8c22-49548672e339)
2022-08-26T13:36:38.138504551Z [13:36:38 DBG] Waiting for downloads to complete. 0/1 complete for torrent Passion.in.the.Desert.1997.1080p.AMZN.WEBRip.DDP2.0.x264-ISA (154943247 - Ready 100%) (43f44b03-1128-44f0-8c22-49548672e339)
2022-08-26T13:36:39.136596503Z [13:36:39 DBG] TorrentRunner Tick Start, 1 active downloads, 0 active unpacks
2022-08-26T13:36:39.136613448Z [13:36:39 DBG] Processing 1 completed downloads
2022-08-26T13:36:39.137135374Z [13:36:39 DBG] Processing download for download Passion.in.the.Desert.1997.1080p.WEB-DL.DDP2.0.H.264-ISA.mkv 0% (6e95b6a7-814a-4f0e-bf2e-221ee3d74df0) for torrent Passion.in.the.Desert.1997.1080p.AMZN.WEBRip.DDP2.0.x264-ISA (154943247 - Ready 100%) (43f44b03-1128-44f0-8c22-49548672e339)
2022-08-26T13:36:39.137148521Z [13:36:39 DBG] Download finished successfully for download Passion.in.the.Desert.1997.1080p.WEB-DL.DDP2.0.H.264-ISA.mkv 0% (6e95b6a7-814a-4f0e-bf2e-221ee3d74df0) for torrent Passion.in.the.Desert.1997.1080p.AMZN.WEBRip.DDP2.0.x264-ISA (154943247 - Ready 100%) (43f44b03-1128-44f0-8c22-49548672e339)
2022-08-26T13:36:39.159831407Z [13:36:39 DBG] Removed from ActiveDownloadClients for download Passion.in.the.Desert.1997.1080p.WEB-DL.DDP2.0.H.264-ISA.mkv 0% (6e95b6a7-814a-4f0e-bf2e-221ee3d74df0) for torrent Passion.in.the.Desert.1997.1080p.AMZN.WEBRip.DDP2.0.x264-ISA (154943247 - Ready 100%) (43f44b03-1128-44f0-8c22-49548672e339)
2022-08-26T13:36:39.160162926Z [13:36:39 DBG] Processing 1 torrents
2022-08-26T13:36:39.160173604Z [13:36:39 DBG] Starting unpack for download Passion.in.the.Desert.1997.1080p.WEB-DL.DDP2.0.H.264-ISA.mkv 0% (6e95b6a7-814a-4f0e-bf2e-221ee3d74df0) for torrent Passion.in.the.Desert.1997.1080p.AMZN.WEBRip.DDP2.0.x264-ISA (154943247 - Ready 100%) (43f44b03-1128-44f0-8c22-49548672e339)
2022-08-26T13:36:39.160179553Z [13:36:39 DBG] Found file name Passion.in.the.Desert.1997.1080p.WEB-DL.DDP2.0.H.264-ISA.mkv for download Passion.in.the.Desert.1997.1080p.WEB-DL.DDP2.0.H.264-ISA.mkv 0% (6e95b6a7-814a-4f0e-bf2e-221ee3d74df0) for torrent Passion.in.the.Desert.1997.1080p.AMZN.WEBRip.DDP2.0.x264-ISA (154943247 - Ready 100%) (43f44b03-1128-44f0-8c22-49548672e339)
2022-08-26T13:36:39.160222491Z [13:36:39 DBG] No need to unpack, setting it as unpacked for download Passion.in.the.Desert.1997.1080p.WEB-DL.DDP2.0.H.264-ISA.mkv 0% (6e95b6a7-814a-4f0e-bf2e-221ee3d74df0) for torrent Passion.in.the.Desert.1997.1080p.AMZN.WEBRip.DDP2.0.x264-ISA (154943247 - Ready 100%) (43f44b03-1128-44f0-8c22-49548672e339)
2022-08-26T13:36:39.220049962Z [13:36:39 DBG] Processing for torrent Passion.in.the.Desert.1997.1080p.AMZN.WEBRip.DDP2.0.x264-ISA (154943247 - Ready 100%) (43f44b03-1128-44f0-8c22-49548672e339)
2022-08-26T13:36:39.220121741Z [13:36:39 DBG] All downloads complete, marking torrent as complete for torrent Passion.in.the.Desert.1997.1080p.AMZN.WEBRip.DDP2.0.x264-ISA (154943247 - Ready 100%) (43f44b03-1128-44f0-8c22-49548672e339)
2022-08-26T13:36:39.245493102Z [13:36:39 DBG] Not removing torrents or files for torrent Passion.in.the.Desert.1997.1080p.AMZN.WEBRip.DDP2.0.x264-ISA (154943247 - Ready 100%) (43f44b03-1128-44f0-8c22-49548672e339)
2022-08-26T13:37:02.104074574Z [13:37:02 DBG] Updating torrent info from Real-Debrid
2022-08-26T13:37:02.208657854Z [13:37:02 DBG] Finished updating torrent info from Real-Debrid, next update in 30 seconds
2022-08-26T13:37:29.987349503Z [13:37:29 DBG] Deleting for torrent Passion.in.the.Desert.1997.1080p.AMZN.WEBRip.DDP2.0.x264-ISA (154943247 - Ready 100%) (43f44b03-1128-44f0-8c22-49548672e339)
2022-08-26T13:37:29.991825140Z [13:37:29 DBG] Deleting RdtClient data for torrent Passion.in.the.Desert.1997.1080p.AMZN.WEBRip.DDP2.0.x264-ISA (154943247 - Ready 100%) (43f44b03-1128-44f0-8c22-49548672e339)
2022-08-26T13:37:29.997463114Z [13:37:29 DBG] Deleting RealDebrid Torrent for torrent Passion.in.the.Desert.1997.1080p.AMZN.WEBRip.DDP2.0.x264-ISA (154943247 - Ready 100%) (43f44b03-1128-44f0-8c22-49548672e339)
2022-08-26T13:37:30.078055822Z [13:37:30 DBG] Deleting local files in /data2/torrents/movies/Passion.in.the.Desert.1997.1080p.AMZN.WEBRip.DDP2.0.x264-ISA for torrent Passion.in.the.Desert.1997.1080p.AMZN.WEBRip.DDP2.0.x264-ISA (154943247 - Ready 100%) (43f44b03-1128-44f0-8c22-49548672e339)
2022-08-26T16:51:38.568024458Z [16:51:38 WRN] 401: /Api/Authentication/IsLoggedIn
2022-08-26T17:10:44.425841891Z [17:10:44 WRN] 101: /hub
2022-08-26T17:10:49.302119024Z [17:10:49 WRN] 101: /hub
2022-08-26T17:10:49.621100622Z [17:10:49 ERR] Unexpected error occurred in ProviderUpdater: A task was canceled.
2022-08-26T17:10:49.621120801Z System.Threading.Tasks.TaskCanceledException: A task was canceled.
2022-08-26T17:10:49.621131593Z    at RdtClient.Service.BackgroundServices.WatchFolderChecker.ExecuteAsync(CancellationToken stoppingToken) in /appserver/server/RdtClient.Service/BackgroundServices/WatchFolderChecker.cs:line 40
2022-08-26T17:10:53.280017166Z [cont-finish.d] executing container finish scripts...
2022-08-26T17:10:53.281017695Z [cont-finish.d] done.
2022-08-26T17:10:53.281239329Z [s6-finish] waiting for services.
2022-08-26T17:10:53.504707056Z [s6-finish] sending all processes the TERM signal.
2022-08-26T17:11:32.143762244Z [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
2022-08-26T17:11:32.554245342Z [s6-init] ensuring user provided files have correct perms...exited 0.
2022-08-26T17:11:32.555340458Z [fix-attrs.d] applying ownership & permissions fixes...
2022-08-26T17:11:32.555984104Z [fix-attrs.d] done.
2022-08-26T17:11:32.556678226Z [cont-init.d] executing container initialization scripts...
2022-08-26T17:11:32.560730727Z [cont-init.d] 01-envfile: executing... 
2022-08-26T17:11:32.737707693Z [cont-init.d] 01-envfile: exited 0.
2022-08-26T17:11:32.741068767Z [cont-init.d] 01-migrations: executing... 
2022-08-26T17:11:32.758575597Z [migrations] started
2022-08-26T17:11:32.758678955Z [migrations] no migrations found
2022-08-26T17:11:32.760310889Z [cont-init.d] 01-migrations: exited 0.
2022-08-26T17:11:32.763422462Z [cont-init.d] 02-tamper-check: executing... 
2022-08-26T17:11:32.986755234Z **** Potential tampering with custom scripts/services detected ****
2022-08-26T17:11:33.378001598Z **** Folder /config/custom-cont-init.d is moved to /config/custom-cont-init.d.iN4a8t_b ****
2022-08-26T17:11:33.382619540Z **** Folder /config/custom-services.d is moved to /config/custom-services.d.iN4a8t_b ****
2022-08-26T17:11:33.382705401Z **** The folders '/config/custom-cont-init.d' and '/config/custom-services.d'; and their contents need to all be owned by root to prevent root escalation inside the container!!! ****
2022-08-26T17:11:33.443385438Z [cont-init.d] 02-tamper-check: exited 0.
2022-08-26T17:11:33.446605879Z [cont-init.d] 10-adduser: executing... 
2022-08-26T17:11:33.965068504Z usermod: no changes
2022-08-26T17:11:33.965959552Z 
2022-08-26T17:11:33.966036747Z -------------------------------------
2022-08-26T17:11:33.966057988Z           _         ()
2022-08-26T17:11:33.966072767Z          | |  ___   _    __
2022-08-26T17:11:33.966086049Z          | | / __| | |  /  \
2022-08-26T17:11:33.966099537Z          | | \__ \ | | | () |
2022-08-26T17:11:33.966113885Z          |_| |___/ |_|  \__/
2022-08-26T17:11:33.966127082Z 
2022-08-26T17:11:33.966139881Z 
2022-08-26T17:11:33.966149944Z Brought to you by linuxserver.io
2022-08-26T17:11:33.966160848Z -------------------------------------
2022-08-26T17:11:33.966441493Z 
2022-08-26T17:11:33.966470833Z To support LSIO projects visit:
2022-08-26T17:11:33.966522851Z https://www.linuxserver.io/donate/
2022-08-26T17:11:33.966537752Z -------------------------------------
2022-08-26T17:11:33.966551144Z GID/UID
2022-08-26T17:11:33.966564361Z -------------------------------------
2022-08-26T17:11:33.989540930Z 
2022-08-26T17:11:33.989593921Z User uid:    998
2022-08-26T17:11:33.989610963Z User gid:    100
2022-08-26T17:11:33.989625175Z -------------------------------------
2022-08-26T17:11:33.989638235Z 
2022-08-26T17:11:34.004684906Z [cont-init.d] 10-adduser: exited 0.
2022-08-26T17:11:34.006491445Z [cont-init.d] 30-config: executing... 
2022-08-26T17:11:34.011291478Z Setting permissions
2022-08-26T17:23:55.100760409Z [cont-init.d] 30-config: exited 0.
2022-08-26T17:23:55.112882769Z [cont-init.d] 90-custom-folders: executing... 
2022-08-26T17:23:55.242039420Z [cont-init.d] 90-custom-folders: exited 0.
2022-08-26T17:23:55.243802790Z [cont-init.d] 99-custom-scripts: executing... 
2022-08-26T17:23:55.291508396Z [custom-init] no custom files found exiting...
2022-08-26T17:23:55.292348432Z [cont-init.d] 99-custom-scripts: exited 0.
2022-08-26T17:23:55.293085278Z [cont-init.d] done.
2022-08-26T17:23:55.293855381Z [services.d] starting services
2022-08-26T17:23:55.368434028Z Changing to /app folder
2022-08-26T17:23:55.368484557Z Starting rtdclient
2022-08-26T17:23:55.371249150Z [services.d] done.
2022-08-26T17:23:59.303182956Z [17:23:59 WRN] Using an in-memory repository. Keys will not be persisted to storage.
2022-08-26T17:23:59.303564838Z [17:23:59 WRN] Neither user profile nor HKLM registry available. Using an ephemeral key repository. Protected data will be unavailable when application exits.
2022-08-26T17:23:59.586455468Z [17:23:59 WRN] No XML encryptor configured. Key {25272171-cc61-44ca-bdde-747675816a33} may be persisted to storage in unencrypted form.
2022-08-26T17:23:59.686237861Z [17:23:59 WRN] Starting host on version 2.0.17.0
2022-08-26T17:24:01.505436788Z [17:24:01 INF] TaskRunner started.
2022-08-26T17:24:01.510428053Z [17:24:01 DBG] Initializing TorrentRunner
2022-08-26T17:24:01.575784337Z [17:24:01 DBG] {"General":{"LogLevel":0,"DownloadLimit":2,"UnpackLimit":1,"Categories":"movies,prowlarr,tv,music,xxx,torrents","RunOnTorrentCompleteFileName":null,"RunOnTorrentCompleteArguments":null},"DownloadClient":{"Client":0,"DownloadPath":"/data2/torrents","MappedPath":"/data2/torrents","MaxSpeed":0,"Aria2cUrl":"http://127.0.0.1:6800/jsonrpc","Aria2cSecret":"*****","TempPath":"/data2/torrents/incomplete","ChunkCount":8,"ProxyServer":null},"Provider":{"Provider":1,"ApiKey":"*****","AutoImport":false,"AutoDelete":true,"Timeout":10,"CheckInterval":10,"Default":{"Category":null,"FinishedAction":1,"OnlyDownloadAvailableFiles":true,"MinFileSize":0,"TorrentRetryAttempts":1,"DownloadRetryAttempts":3,"DeleteOnError":0,"TorrentLifetime":0,"Priority":0}},"Integrations":{"Default":{"OnlyDownloadAvailableFiles":true,"MinFileSize":1,"TorrentRetryAttempts":1,"DownloadRetryAttempts":3,"DeleteOnError":0,"TorrentLifetime":0,"Priority":0}},"Gui":{"Default":{"Category":null,"FinishedAction":1,"OnlyDownloadAvailableFiles":true,"MinFileSize":0,"TorrentRetryAttempts":1,"DownloadRetryAttempts":3,"DeleteOnError":0,"TorrentLifetime":0,"Priority":0}},"Watch":{"Path":"","Interval":0,"Default":{"Category":null,"FinishedAction":1,"OnlyDownloadAvailableFiles":true,"MinFileSize":0,"TorrentRetryAttempts":1,"DownloadRetryAttempts":3,"DeleteOnError":0,"TorrentLifetime":0,"Priority":0}}
2022-08-26T17:24:01.635943856Z [17:24:01 INF] ProviderUpdater started.
2022-08-26T17:24:01.738226335Z [17:24:01 DBG] Found 0 not completed torrents
2022-08-26T17:24:01.738249641Z [17:24:01 DBG] TorrentRunner Initialized
2022-08-26T17:24:01.803320003Z [17:24:01 INF] UpdateChecker started, currently on version v2.0.17.
2022-08-26T17:24:01.846279518Z [17:24:01 INF] WatchFolderChecker started.

**Comment by rogerfar** [comment]
Yeah so it's really this part:
```
2022-08-26T17:11:34.011291478Z Setting permissions
2022-08-26T17:23:55.100760409Z [cont-init.d] 30-config: exited 0.
```

Which is executing this:
```
chown -R abc:abc \
	/app /data /config
```
/app and /config are fairly contained, /data is mapped to your `/srv/dev-disk-by-uuid-2628F1C228F19153/data` path, how many files are in there?

**Comment by janaxhell** [comment]
Thousands, that's the root folder of the whole server...

**Comment by rogerfar** [comment]
Because it has to put files there, so it needs permission to put the files there.

For the time being I suggest making a folder inside your data folder like `/downloads` and mapping it to there, as the client re-sets permissions for the whole folder.

**Comment by janaxhell** [comment]
The point is to have atomic move within Radarr/Sonarr, hence they are all mounted on /data and each of them points to a subfolder 
Radarr container = /data -> app settings = /data/media/movies
Sonarr container = /data -> app settings = /data/media/tv
Rdtclient container = /data -> app settings = /data/torrents  and according to category assigned in Radarr/Sonarr the whole path becomes /data/torrents/movies or /data/torrents/tv when something is added to download.
If I don't do that, files will be copied from /torrents to /media instead of hardlinked.
I can't mount rdtclient on /data/torrents in container because that will be invisible to Radarr/Sonarr.

**Comment by rogerfar** [comment]
You can use the path mapping features from Radarr/Sonarr for that.

But why not just mount Rdtclient to `/data/rdtdownloads`? It will report the correct paths back to Sonarr and Radarr and as long they have permissions to read from this directories they will just move the files to the right folders after downloads are completed.

**Comment by janaxhell** [comment]
You mean like 
/data/rdtdownloads:/data 
?
Wouldn't that make it invisible to *arrs?
And how/why do I give permission? I didn't need to give any explicit permission in my current scenario.
