### ISSUE TITLE
Aria2 uses the "Download path" when it should use the "Mapped path", which causes Aria2 to throw a missing permission error

### ISSUE THREAD

**Issue by bannert1337** [rogerfar/rdt-client#195]
**What version are you using?**
Version 2.0.19
**What OS are you running?**
Debian 11
**Are you using Docker or as a service?**
Docker
**Please attach a log file here with the log setting set to debug.**

**Real-Debrid Client:**

2022-11-03 14:31:42.774 +00:00 [DBG] RdtClient.Service.BackgroundServices.TaskRunner: Finished updating torrent info from Real-Debrid, next update in 10 seconds
2022-11-03 14:31:45.754 +00:00 [DBG] RdtClient.Service.Services.Torrents: Retrying Download for download xxx.rar 0% (5a5cc5e5-279b-4c9e-9ab1-2d762aef349f) for torrent xxx (VA3TO2YNU4BKG - downloaded 100%) (6416ac8b-af08-4eca-83d5-f76bcbdac74c)
2022-11-03 14:31:45.758 +00:00 [ERR] Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware: An unhandled exception has occurred while executing the request.
System.UnauthorizedAccessException: Access to the path '/mnt/cloud/Download/lidarr/xxx' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.FileSystem.CreateDirectory(String fullPath)
   at System.IO.Directory.CreateDirectory(String path)
   at RdtClient.Service.Helpers.DownloadHelper.GetDownloadPath(String downloadPath, Torrent torrent, Download download) in /appserver/server/RdtClient.Service/Helpers/DownloadHelper.cs:line 18
   at RdtClient.Service.Services.Torrents.RetryDownload(Guid downloadId) in /appserver/server/RdtClient.Service/Services/Torrents.cs:line 498
   at RdtClient.Web.Controllers.TorrentsController.RetryDownload(Guid downloadId) in /appserver/server/RdtClient.Web/Controllers/TorrentsController.cs:line 189
   at lambda_method447(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Program.<>c.<<<Main>$>b__0_12>d.MoveNext() in /appserver/server/RdtClient.Web/Program.cs:line 159
--- End of stack trace from previous location ---
   at RdtClient.Service.Middleware.AuthorizeMiddleware.Invoke(HttpContext context) in /appserver/server/RdtClient.Service/Middleware/AuthorizeMiddleware.cs:line 28
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)

**Aria2:**

11/03 15:31:28 [ERROR] CUID#102 - Download aborted. URI=https://xxx.rar
Exception: [AbstractCommand.cc:403] errorCode=18 URI=https://xxx.rar
  -> [RequestGroup.cc:761] errorCode=18 Download aborted.
  -> [util.cc:1948] errNum=13 errorCode=18 Failed to make the directory /data/downloads/test/lidarr/xxx, cause: Permission denied

**Solution**
Replace the "Download path" with the "Mapped path" when launching Aria2.

**Comment by Today223** [comment]
How were you able to install this rdt? I keep getting a Volume error even though I know the folder path is correct.

**Comment by bannert1337** [comment]
I installed RDT using the Docker Container

**Comment by tduong-cloud** [comment]
Hey, I think I am having the same issue : 
-rdt client is installed in docker, and is working well with sonarr and radarr
- I have been able to install Aria2c and AriaNG (webui) and my rdt client can connect to Aria2c

Unfortunately, when starting to download, I have this error 18 and download is aborted. Where can I find the Aria2c log ?

**Comment by rogerfar** [comment]
The Aria2c log is configured in your aria config file.

![image](https://user-images.githubusercontent.com/1142915/222187149-2b3289a9-7028-4291-a835-4b535adf4dcd.png)

**Comment by Freckled7261** [comment]
@tduong-cloud can you explain how you solved this? I tried mounting a /data/downloads folder in aria2 and binding that to the downloads folder on my host. Now I am getting an error 16
