### ISSUE TITLE
. Net version  error 

### ISSUE THREAD

**Issue by deepdivered** [rogerfar/rdt-client#210]
**What version are you using?**

**Wat OS are you running?**

**Are you using Docker or as a service?**

**Please attach a log file here with the log setting set to debug**

I pulled the latest image in docker and now I am getting a .Net framework error. I tried using the. Console to install .Net6 but I still get this error.

Changing to /app folder
Starting rtdclient
You must install or update .NET to run this application.
App: /app/RdtClient.Web.dll
Architecture: x64
Framework: 'Microsoft.NETCore.App', version '6.0.0' (x64)
.NET location: /usr/share/dotnet/
The following frameworks were found:
  7.0.3 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]
Learn about framework resolution:
https://aka.ms/dotnet/app-launch-failed
To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=6.0.0&arch=x64&rid=ubuntu.20.04-x64

**Comment by louga31** [comment]
I have the same error, I did fix it temporarily by using the 2.0.19 tag, but something is definitely wrong with the latest version docker image

**Comment by screamjojo** [comment]
Same with Docker

**Comment by Muneer91** [comment]
Same issue here with exactly the same error messages, actually tried installing dotnet6 but still doesn't work. 
Tried 2.0.19 and works fine.

**Comment by rogerfar** [comment]
Turns out the dockerfile was set to use latest. Changed it to use LTS (.NET 6) and re-published the image, if someone can verify that would be appreciated.

**Comment by timcoop3r** [comment]
By complete coincidence I just did a docker pull to the latest version and this still seems to be broken? Not sure if this is the potentially fixed version or not, but there isn’t a newer one as yet?

Image ID I have is  fc1e5e45209a

**Comment by rogerfar** [comment]
I don't think that is the latest, this is the last push: https://hub.docker.com/layers/rogerfar/rdtclient/latest/images/sha256-fb89e7a16b52b80b6d02b705ba3aa54f9bdcb25f2e3c7c5676c2db46fa201ea2?context=repo

**Comment by sylvaindd** [comment]
For some reason it doesn't seem to pull latest tag : 
![image](https://user-images.githubusercontent.com/5629405/224062507-b7567cc5-b6b8-420e-ad15-8597f8978f24.png)
The sha256 doesn't match dockerhub

**Comment by rogerfar** [comment]
Probably easier to push a new tag, I published 1.0.0.21 now.

**Comment by 23doors** [comment]
2.0.21 doesnt work for me. different error now.
```
2023-03-09T15:42:40.5654329Z Caught exception while emitting to sink Serilog.Sinks.File.RollingFileSink: System.UnauthorizedAccessException: Access to the path '/data/db/rdtclient_205.log' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.File.Open(String path, FileMode mode, FileAccess access, FileShare share)
   at Serilog.Sinks.File.FileSink..ctor(String path, ITextFormatter textFormatter, Nullable`1 fileSizeLimitBytes, Encoding encoding, Boolean buffered, FileLifecycleHooks hooks)
   at Serilog.Sinks.File.RollingFileSink.OpenFile(DateTime now, Nullable`1 minSequence)
   at Serilog.Sinks.File.RollingFileSink.AlignCurrentFileTo(DateTime now, Boolean nextSequence)
   at Serilog.Sinks.File.RollingFileSink.Emit(LogEvent logEvent)
   at Serilog.Core.Sinks.SafeAggregateSink.Emit(LogEvent logEvent)
```

same error even when I delete the log file.
Using PUID/PGID env vars and it works fine with <=2.0.19 with exactly same config.

**Comment by timcoop3r** [comment]
2.0.21 working fine for me.

There was a permissions issue on the log files but I stopped the container, deleted the logs, started the container and all is fine.

**Comment by 23doors** [comment]
Yup, seems like stopping container and re-running chown $PUID:$PGID -R on all shared volume data fixed it.
Kind of a weird introduced behavior though.

**Comment by rogerfar** [comment]
Yeah not sure how that would've happened, same base container was used, unless something changed there, but I doubt it.

I'm going to close this issue now, thanks for all the reports!

**Comment by deepdivered** [comment]
I am have trouble with pulling from docker hub this 2.0.21 tag vsrsion. It seems it's out of date and does not have the latest build. 2.0.19 is the newest version there and it looks like on git your at 2.0.21 or higher now.

https://hub.docker.com/r/rogerfar/rdtclient/tags
