### ISSUE TITLE
Docker won't start 

### ISSUE THREAD

**Issue by Alfiegerner** [rogerfar/rdt-client#215]
**What version are you using?**
2.0.21
**Wat OS are you running?**
Ubuntu 
**Are you using Docker or as a service?**
Docker

**Please attach a log file here with the log setting set to debug**

Have successfully using service for some time, thank you for your efforts.  However docker service now not starting.

Logs:
      
[21:44:31 ERR] BackgroundService failed
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at RdtClient.Service.BackgroundServices.ProviderUpdater.ExecuteAsync(CancellationToken stoppingToken) in /appserver/server/RdtClient.Service/BackgroundServices/ProviderUpdater.cs:line 25
   at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService backgroundService)
Changing to /app folder
Starting rtdclient
[21:44:31 WRN] Using an in-memory repository. Keys will not be persisted to storage.
[21:44:31 WRN] Neither user profile nor HKLM registry available. Using an ephemeral key repository. Protected data will be unavailable when application exits.
[21:44:31 WRN] No XML encryptor configured. Key {3c526d93-d417-49cc-a42a-ed34b71c6752} may be persisted to storage in unencrypted form.
[21:44:31 WRN] Starting host on version 2.0.21.0
[21:44:32 ERR] BackgroundService failed
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at RdtClient.Service.BackgroundServices.ProviderUpdater.ExecuteAsync(CancellationToken stoppingToken) in /appserver/server/RdtClient.Service/BackgroundServices/ProviderUpdater.cs:line 25
   at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService backgroundService)
Changing to /app folder
Starting rtdclient
[21:44:33 WRN] Using an in-memory repository. Keys will not be persisted to storage.
[21:44:33 WRN] Neither user profile nor HKLM registry available. Using an ephemeral key repository. Protected data will be unavailable when application exits.
[21:44:33 WRN] No XML encryptor configured. Key {dfcf3592-9c1a-4631-a263-a9d618b420aa} may be persisted to storage in unencrypted form.
[21:44:33 WRN] Starting host on version 2.0.21.0
[21:44:34 ERR] BackgroundService failed

Docker compose.

version: '3.3'
services:
 rdtclient:
        container_name: rdtclient
        volumes:
            - /mnt/external/media/downloads:/data/downloads
            - /home/pi/hass/docker/data/rdt-client:/data/db
        image: rogerfar/rdtclient
        restart: always
        logging:
            driver: json-file
            options:
                max-size: 10m
        ports:
            - 6500:6500
        environment:

           - PUID=1000

           - PGID=1000

           - TZ=Pacific/Auckland

**Comment by Stephan296** [comment]
Set the rights of the folder back to 1000:1000. Now are they 911:911.
After that restart it wil work. But after a restart you have the same problem. I have already made an issue

**Comment by Alfiegerner** [comment]
Hi @Stephan296 , thanks for looking at this. 
The uid and gid of my
/home/pi/hass/docker/data/rdt-client:/data/db volume is 1000:1000? Is that what you were expecting to be 911?

**Comment by simani** [comment]
Hello @Stephan296  ! Went to check and i'm in the same case, the folder is already 1000:1000, I don't see 911 anywhere. Which folder are you referring to ? The one with the log and the .db ?

**Comment by simani** [comment]
up :)
