### ISSUE TITLE
Need to handle duplicate jobs in Premiumize better

### ISSUE THREAD

**Issue by nihilist77** [rogerfar/rdt-client#219]
**What version are you using?**
2.0.22

**Wat OS are you running?**
Docker on x86.

**Are you using Docker or as a service?**
Docker

**Please attach a log file here with the log setting set to debug**
Sometimes a job fails to get a link and just waits for a link. So if I remove the job and add it again from *arr, `rdt-client` tries to add the job again to premiumize and fails. Below is the relevant part of the log.

```
[20:51:18 ERR] An unhandled exception has occurred while executing the request.
PremiumizeNET.PremiumizeException: You already added this job.
   at PremiumizeNET.Requests.Request[T](String url, Boolean requireAuthentication, RequestType requestType, HttpContent data, IDictionary`2 parameters, CancellationToken cancellationToken)
   at PremiumizeNET.Requests.PostRequestAsync[T](String url, IEnumerable`1 data, Boolean requireAuthentication, CancellationToken cancellationToken)
   at PremiumizeNET.TransferApi.CreateAsync(String src, String folderId, CancellationToken cancellationToken)
   at RdtClient.Service.Services.TorrentClients.PremiumizeTorrentClient.AddMagnet(String magnetLink) in /appserver/server/RdtClient.Service/Services/TorrentClients/PremiumizeTorrentClient.cs:line 121
   at RdtClient.Service.Services.Torrents.UploadMagnet(String magnetLink, Torrent torrent) in /appserver/server/RdtClient.Service/Services/Torrents.cs:line 126
   at RdtClient.Service.Services.QBittorrent.TorrentsAddMagnet(String magnetLink, String category, Nullable`1 priority) in /appserver/server/RdtClient.Service/Services/QBittorrent.cs:line 434
   at RdtClient.Web.Controllers.QBittorrentController.TorrentsAdd(QBTorrentsAddRequest request) in /appserver/server/RdtClient.Web/Controllers/QBittorrentController.cs:line 322
   at RdtClient.Web.Controllers.QBittorrentController.TorrentsAddPost(QBTorrentsAddRequest request) in /appserver/server/RdtClient.Web/Controllers/QBittorrentController.cs:line 359
   at lambda_method212(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Program.<>c.<<<Main>$>b__0_14>d.MoveNext() in /appserver/server/RdtClient.Web/Program.cs:line 165
--- End of stack trace from previous location ---
   at RdtClient.Service.Middleware.AuthorizeMiddleware.Invoke(HttpContext context) in /appserver/server/RdtClient.Service/Middleware/AuthorizeMiddleware.cs:line 28
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
```

**Comment by rogerfar** [comment]
If it gives that error, where in Premiumize does it already exist? Is that in your personal files or magnets? Or is it more like on their servers?

**Comment by nihilist77** [comment]
I think it already exist as a transfer in premiumize. So I guess they are using the magnet as a hash to check if it's already there.

**Comment by rogerfar** [comment]
I had a look at this today, but I don't see how this can be solved. The issue is that the job already exist in your transfer list, but the error doesn't give any information back like the ID of that file. And because we don't know what the output it will be, it will be impossible to figure out which torrent belongs to what transfer.

I suggest enabling `Automatically import and process torrents added to provider`
