### ISSUE TITLE
does not download

### ISSUE THREAD

**Issue by Gotcha007** [rogerfar/rdt-client#22]
I just setup rdt-client via Docker Compose and I'm having an issue. 
I can add torrents, I see them added and completed on the real-debrid side but it does not download (automatically or not).
In the docker log , I have the below. I don't recognize that IP, this is not my external IP.
```

2021-01-22T03:33:18.459125854Z     FROM "Torrents" AS "t"
2021-01-22T03:33:18.459136662Z     WHERE "t"."TorrentId" = @__torrentId_0
2021-01-22T03:33:18.459147005Z     LIMIT 1
2021-01-22T03:33:18.459157057Z ) AS "t0"
2021-01-22T03:33:18.459167853Z LEFT JOIN "Downloads" AS "d" ON "t0"."TorrentId" = "d"."TorrentId"
2021-01-22T03:33:18.459180932Z ORDER BY "t0"."TorrentId", "d"."DownloadId"
2021-01-22T03:33:18.723037942Z [03:33:18 ERR] Unexpected error occurred in TorrentDownloadManager.Tick
2021-01-22T03:33:18.723108524Z System.Exception: {
2021-01-22T03:33:18.723126399Z 	"error": "ip_not_allowed_199.188.237.142",
2021-01-22T03:33:18.723141607Z 	"error_code": 22
2021-01-22T03:33:18.723155196Z }
2021-01-22T03:33:18.723167953Z    at RDNET.RdNetClient.Post[T](String url, KeyValuePair`2[] data, Boolean repeatRequest)
2021-01-22T03:33:18.723181530Z    at RDNET.RdNetClient.UnrestrictLinkAsync(String link, String password, Boolean remote)
2021-01-22T03:33:18.723195383Z    at RdtClient.Service.Services.Torrents.Unrestrict(Guid torrentId) in /appserver/RdtClient.Service/Services/Torrents.cs:line 211
2021-01-22T03:33:18.723209554Z    at RdtClient.Service.Services.TorrentRunner.Tick() in /appserver/RdtClient.Service/Services/TorrentRunner.cs:line 313
2021-01-22T03:33:18.723223674Z    at RdtClient.Service.Services.TaskRunner.ExecuteAsync(CancellationToken stoppingToken) in /appserver/RdtClient.Service/Services/TaskRunner.cs:line 36
```

**Comment by rogerfar** [comment]
Error 22 from real debris means 	IP Address not allowed.

Can you download from Rd if you in restrict a torrent and then download it?

**Comment by Gotcha007** [comment]
Yep, If I click on the green package, it brings me to the download page when I can click on the link and download

**Comment by Gotcha007** [comment]
so I thought it was because of the 2 factor authentication. So I went on the device where the docker is running, opened up a browser and logged in into Real-Debrid, got the email with the 2 factor code and was able to login.
Tried again to download but getting the same error.

**Comment by Gotcha007** [comment]
strangely enough, from a different machine on the same network I don't have the issue

**Comment by rogerfar** [comment]
I have the same issue when I login from a new ip yeah. But did you install the container on that different machine? Only thing I can think of is that the IPs are different.

**Comment by Gotcha007** [comment]
Found the issue. My server was going out to my VPN interface. It looks like Real-debrid does not like hotspotshieldvpn
