### ISSUE TITLE
Docker composing errors

### ISSUE THREAD

**Issue by handshake87** [rogerfar/rdt-client#25]
I am getting this when trying to launch the docker container:

`[03:25:05 INF] Entity Framework Core 5.0.2 initialized 'DataContext' using provider 'Microsoft.EntityFrameworkCore.Sqlite' with options: None
[03:25:05 ERR] An error occurred using the connection to database 'main' on server '/data/db/rdtclient.db'.
[03:25:05 FTL] Host terminated unexpectedly
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 14: 'unable to open database file'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnection(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternal(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal.SqliteDatabaseCreator.Create()
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.CreateAsync(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.MigrateAsync(String targetMigration, CancellationToken cancellationToken)
   at RdtClient.Web.Program.Main(String[] args) in /appserver/RdtClient.Web/Program.cs:line 30
`

**Comment by rogerfar** [comment]
How are you launching? This sounds like it's trying to write a database file to a path that doesn't exist.

**Comment by handshake87** [comment]
I out everything into compose and hit run and it creates the container
which ends up erroring out with that error. If I run the run.bat in the
older version it works just fine.

**Comment by rogerfar** [comment]
But did you replace the mapped paths to a directory on your host machine?

**Comment by handshake87** [comment]
Yes I already had my directory setup for downloads and I created a folder
for Docker/rtdclient

**Comment by logtho** [comment]
Where is your downloads folder? I found I ran into a similar error when trying to use my D:\ drive. It seemed anything but the C:\ drive would cause this error and I believe it's entirely a Docker issue.

**Comment by handshake87** [comment]
Ya it was when I used C:/ as my drive for Docker files and downloads

**Comment by rogerfar** [comment]
@handshake87 can you try with the latest docker image and see if it changes anything?

**Comment by handshake87** [comment]
No it hasnt been resolved. Here is full log and was pulled in from build 15 days ago.

`=2021-03-02T03:37:19.9390131Z Caught exception while emitting to sink Serilog.Sinks.File.RollingFileSink: System.UnauthorizedAccessException: Access to the path '/data/db' is denied.

---> System.IO.IOException: Permission denied

--- End of inner exception stack trace ---

at System.IO.FileSystem.CreateDirectory(String fullPath)

at System.IO.Directory.CreateDirectory(String path)

at Serilog.Sinks.File.FileSink..ctor(String path, ITextFormatter textFormatter, Nullable`1 fileSizeLimitBytes, Encoding encoding, Boolean buffered, FileLifecycleHooks hooks)

at Serilog.Sinks.File.RollingFileSink.OpenFile(DateTime now, Nullable`1 minSequence)

at Serilog.Sinks.File.RollingFileSink.AlignCurrentFileTo(DateTime now, Boolean nextSequence)

at Serilog.Sinks.File.RollingFileSink.Emit(LogEvent logEvent)

at Serilog.Core.Sinks.SafeAggregateSink.Emit(LogEvent logEvent)

[03:37:19 DBG] An 'IServiceProvider' was created for internal use by Entity Framework.

[03:37:20 DBG] The index {'UserId'} was not created on entity type 'IdentityUserRole<string>' as the properties are already covered by the index {'UserId', 'RoleId'}.

[03:37:20 DBG] The index {'UserId'} was not created on entity type 'IdentityUserToken<string>' as the properties are already covered by the index {'UserId', 'LoginProvider', 'Name'}.

[03:37:20 INF] Entity Framework Core 5.0.3 initialized 'DataContext' using provider 'Microsoft.EntityFrameworkCore.Sqlite' with options: None

[03:37:20 DBG] Migrating using database 'main' on server '/data/db/rdtclient.db'.

[03:37:20 DBG] Opening connection to database 'main' on server '/data/db/rdtclient.db'.

[03:37:20 DBG] An error occurred using the connection to database 'main' on server '/data/db/rdtclient.db'.

[03:37:20 DBG] Opening connection to database 'main' on server '/data/db/rdtclient.db'.

[03:37:20 DBG] An error occurred using the connection to database 'main' on server '/data/db/rdtclient.db'.

[03:37:20 DBG] Opening connection to database 'main' on server '/data/db/rdtclient.db'.

[03:37:20 ERR] An error occurred using the connection to database 'main' on server '/data/db/rdtclient.db'.

[03:37:20 DBG] 'DataContext' disposed.

[03:37:20 FTL] Host terminated unexpectedly

Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 14: 'unable to open database file'.

at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)

at Microsoft.Data.Sqlite.SqliteConnection.Open()

at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnection(Boolean errorsExpected)

at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternal(Boolean errorsExpected)

at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)

at Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal.SqliteDatabaseCreator.Create()

at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.CreateAsync(CancellationToken cancellationToken)

at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.MigrateAsync(String targetMigration, CancellationToken cancellationToken)

at RdtClient.Web.Program.Main(String[] args) in /appserver/RdtClient.Web/Program.cs:line 33`

**Comment by handshake87** [comment]
Issue has been resolved. Seems I didnt have the C:\Downloads folder under the Resources-File Sharing in docker. Having a new problem but will create a new ticket for that!
