### ISSUE TITLE
rdt creates wrong permission 

### ISSUE THREAD

**Issue by darkwst** [rogerfar/rdt-client#259]
**What version are you using?**
6.11.5
**Wat OS are you running?**
unraid
**Are you using Docker or as a service?**
docker
**Please attach a log file here with the log setting set to debug**
rdt client creates wrong permission 775 every time sonarr tries to import a file it fails until i manually change permissions every time it downloads something 
some of sonarr logs: 

2023-05-13 18:31:16.5|Warn|ImportApprovedEpisodes|Couldn't import episode /data/torrents/tv-sonarr/Euphoria.US.S02.1080p.AMZN.WEBRip.DDP5.1.x264-NTb/Euphoria.US.S02E02.Out.Of.Touch.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.mkv

[v3.0.10.1567] System.UnauthorizedAccessException: Access to the path '/data/torrents/tv-sonarr/Euphoria.US.S02.1080p.AMZN.WEBRip.DDP5.1.x264-NTb/Euphoria.US.S02E02.Out.Of.Touch.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.mkv' is denied. ---> System.IO.IOException: Permission denied

2023-05-13 18:32:43.3|Warn|ImportApprovedEpisodes|Couldn't import episode /data/torrents/tv-sonarr/Euphoria.US.S02.1080p.AMZN.WEBRip.DDP5.1.x264-NTb/Euphoria.US.S02E01.Trying.To.Get.To.Heaven.Before.They.Close.The.Door.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.mkv

2023-05-13 18:32:46.3|Warn|ImportApprovedEpisodes|Couldn't import episode /data/torrents/tv-sonarr/Euphoria.US.S02.1080p.AMZN.WEBRip.DDP5.1.x264-NTb/Euphoria.US.S02E02.Out.Of.Touch.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.mkv

[v3.0.10.1567] System.UnauthorizedAccessException: Access to the path '/data/torrents/tv-sonarr/Euphoria.US.S02.1080p.AMZN.WEBRip.DDP5.1.x264-NTb/Euphoria.US.S02E02.Out.Of.Touch.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.mkv' is denied. ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
  at System.IO.FileSystem.DeleteFile (System.String fullPath) [0x0006e] in /build/mono/src/mono/external/corefx/src/System.IO.FileSystem/src/System/IO/FileSystem.Unix.cs:218 
  at System.IO.File.Delete (System.String path) [0x0000e] in /build/mono/src/mono/external/corefx/src/System.IO.FileSystem/src/System/IO/File.cs:107 
  at NzbDrone.Mono.Disk.DiskProvider.TransferFilePatched (System.String source, System.String destination, System.Boolean overwrite, System.Boolean move) [0x00291] in C:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Mono\Disk\DiskProvider.cs:423 
  at NzbDrone.Mono.Disk.DiskProvider.MoveFileInternal (System.String source, System.String destination) [0x00098] in C:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Mono\Disk\DiskProvider.cs:302 
  at NzbDrone.Common.Disk.DiskProviderBase.MoveFile (System.String source, System.String destination, System.Boolean overwrite) [0x000e1] in C:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Disk\DiskProviderBase.cs:255 
  at NzbDrone.Common.Disk.DiskTransferService.TryMoveFileVerified (System.String sourcePath, System.String targetPath, System.Int64 originalSize) [0x00047] in C:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Disk\DiskTransferService.cs:487 
  at NzbDrone.Common.Disk.DiskTransferService.TransferFile (System.String sourcePath, System.String targetPath, NzbDrone.Common.Disk.TransferMode mode, System.Boolean overwrite) [0x004b9] in C:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Disk\DiskTransferService.cs:367 
  at NzbDrone.Core.MediaFiles.EpisodeFileMovingService.TransferFile (NzbDrone.Core.MediaFiles.EpisodeFile episodeFile, NzbDrone.Core.Tv.Series series, System.Collections.Generic.List`1[T] episodes, System.String destinationFilePath, NzbDrone.Common.Disk.TransferMode mode) [0x00129] in C:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\MediaFiles\EpisodeFileMovingService.cs:116 
  at NzbDrone.Core.MediaFiles.EpisodeFileMovingService.MoveEpisodeFile (NzbDrone.Core.MediaFiles.EpisodeFile episodeFile, NzbDrone.Core.Parser.Model.LocalEpisode localEpisode) [0x00046] in C:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\MediaFiles\EpisodeFileMovingService.cs:79 
  at NzbDrone.Core.MediaFiles.UpgradeMediaFileService.UpgradeEpisodeFile (NzbDrone.Core.MediaFiles.EpisodeFile episodeFile, NzbDrone.Core.Parser.Model.LocalEpisode localEpisode, System.Boolean copyOnly) [0x001b0] in C:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\MediaFiles\UpgradeMediaFileService.cs:77 
  at NzbDrone.Core.MediaFiles.EpisodeImport.ImportApprovedEpisodes.Import (System.Collections.Generic.List`1[T] decisions, System.Boolean newDownload, NzbDrone.Core.Download.DownloadClientItem downloadClientItem, NzbDrone.Core.MediaFiles.EpisodeImport.ImportMode importMode) [0x0029b] in C:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\MediaFiles\EpisodeImport\ImportApprovedEpisodes.cs:109 

tried to change it through sonarr's settings under media management to 777
drwxrwxrwx and chmod group to nobody and tried 99/100 its all the same every time rdt creates a file sonarr cant import 

---------------------------------------------- rdt logs ---------------------------------------------------

2023-05-13 13:55:26.625 +00:00 [ERR] RdtClient.Service.BackgroundServices.WatchFolderChecker: Unexpected error occurred in ProviderUpdater: A task was canceled.
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at RdtClient.Service.BackgroundServices.WatchFolderChecker.ExecuteAsync(CancellationToken stoppingToken) in /appserver/server/RdtClient.Service/BackgroundServices/WatchFolderChecker.cs:line 40
2023-05-13 13:55:50.274 +00:00 [WRN] Microsoft.AspNetCore.DataProtection.Repositories.EphemeralXmlRepository: Using an in-memory repository. Keys will not be persisted to storage.
2023-05-13 13:55:50.306 +00:00 [WRN] Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager: Neither user profile nor HKLM registry available. Using an ephemeral key repository. Protected data will be unavailable when application exits.
2023-05-13 13:55:50.322 +00:00 [WRN] Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager: No XML encryptor configured. Key {5e55a0ff-95dd-494b-9494-45a3111e2d39} may be persisted to storage in unencrypted form.
2023-05-13 13:55:50.342 +00:00 [WRN] : Starting host on version 2.0.30.0
2023-05-13 13:55:53.946 +00:00 [WRN] Microsoft.EntityFrameworkCore.Query: The query uses the 'First'/'FirstOrDefault' operator without 'OrderBy' and filter operators. This may lead to unpredictable results.
2023-05-13 14:23:27.688 +00:00 [ERR] RdtClient.Service.BackgroundServices.WatchFolderChecker: Unexpected error occurred in ProviderUpdater: A task was canceled.
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at RdtClient.Service.BackgroundServices.WatchFolderChecker.ExecuteAsync(CancellationToken stoppingToken) in /appserver/server/RdtClient.Service/BackgroundServices/WatchFolderChecker.cs:line 40
2023-05-13 14:30:15.174 +00:00 [WRN] Microsoft.AspNetCore.DataProtection.Repositories.EphemeralXmlRepository: Using an in-memory repository. Keys will not be persisted to storage.
2023-05-13 14:30:15.207 +00:00 [WRN] Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager: Neither user profile nor HKLM registry available. Using an ephemeral key repository. Protected data will be unavailable when application exits.
2023-05-13 14:30:15.223 +00:00 [WRN] Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager: No XML encryptor configured. Key {0e161d69-65db-4d58-8057-179645b7f851} may be persisted to storage in unencrypted form.
2023-05-13 14:30:15.243 +00:00 [WRN] : Starting host on version 2.0.30.0
2023-05-13 14:30:18.674 +00:00 [WRN] Microsoft.EntityFrameworkCore.Query: The query uses the 'First'/'FirstOrDefault' operator without 'OrderBy' and filter operators. This may lead to unpredictable results.
2023-05-13 14:41:14.262 +00:00 [ERR] RdtClient.Service.BackgroundServices.WatchFolderChecker: Unexpected error occurred in ProviderUpdater: A task was canceled.
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at RdtClient.Service.BackgroundServices.WatchFolderChecker.ExecuteAsync(CancellationToken stoppingToken) in /appserver/server/RdtClient.Service/BackgroundServices/WatchFolderChecker.cs:line 40
2023-05-13 14:42:05.367 +00:00 [WRN] Microsoft.AspNetCore.DataProtection.Repositories.EphemeralXmlRepository: Using an in-memory repository. Keys will not be persisted to storage.
2023-05-13 14:42:05.401 +00:00 [WRN] Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager: Neither user profile nor HKLM registry available. Using an ephemeral key repository. Protected data will be unavailable when application exits.
2023-05-13 14:42:05.417 +00:00 [WRN] Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager: No XML encryptor configured. Key {c64b31fe-952e-4063-befa-5f3922b84a36} may be persisted to storage in unencrypted form.
2023-05-13 14:42:05.437 +00:00 [WRN] : Starting host on version 2.0.30.0
2023-05-13 14:42:08.956 +00:00 [WRN] Microsoft.EntityFrameworkCore.Query: The query uses the 'First'/'FirstOrDefault' operator without 'OrderBy' and filter operators. This may lead to unpredictable results.
2023-05-13 15:09:17.114 +00:00 [WRN] : 401: /Api/Authentication/IsLoggedIn
2023-05-13 16:08:40.194 +00:00 [WRN] : 401: /Api/Authentication/IsLoggedIn
2023-05-13 17:37:09.072 +00:00 [WRN] : 304: /favicon.ico
2023-05-13 17:52:26.958 +00:00 [WRN] : 101: /hub
2023-05-13 19:54:21.722 +00:00 [WRN] : 101: /hub
2023-05-13 20:12:54.771 +00:00 [WRN] : 101: /hub
2023-05-13 21:28:33.024 +00:00 [WRN] : 101: /hub
2023-05-13 21:30:32.274 +00:00 [WRN] : 304: /runtime.52f1d05aa6c3afea.js
2023-05-13 21:30:32.274 +00:00 [WRN] : 304: /styles.9638ea5157c483f9.css
2023-05-13 21:30:32.274 +00:00 [WRN] : 304: /main.5aeeb8cd47feeb5b.js
2023-05-13 21:30:32.274 +00:00 [WRN] : 304: /polyfills.9d4d8b2ca59be0bc.js
2023-05-13 21:30:32.571 +00:00 [WRN] : 401: /Api/Authentication/IsLoggedIn
2023-05-13 21:30:32.821 +00:00 [WRN] : 304: /assets/logo.png
2023-05-13 21:30:32.833 +00:00 [WRN] : 304: /fa-solid-900.d5d28b783e396c28.woff2
2023-05-13 21:30:41.624 +00:00 [WRN] : 400: /Api/Authentication/Login

im on remote paths because thats another issue couldn't get it to work  

*my rdt build setup: 

version: '3.3'
services:
    rdtclient:
        container_name: rdtclient
        volumes:
            - '/mnt/user/data/torrents/:/data/torrents'
            - '/mnt/cache/appdata/rdtclient/data/:/data/db'
        image: rogerfar/rdtclient
        restart: always
        logging:
            driver: json-file
            options:
                max-size: 10m
        ports:
            - '6500:6500'

*my sonarr remote paths 

192.168.8.124
/mnt/user/data/torrents/tv-sonarr/
/data/torrents/tv-sonarr/

spent days trying to fix it any help for a newbie is seriously appreciated!

**Comment by darkwst** [comment]
logs for rdt


2023-05-13 13:55:26.625 +00:00 [ERR] RdtClient.Service.BackgroundServices.WatchFolderChecker: Unexpected error occurred in ProviderUpdater: A task was canceled.
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at RdtClient.Service.BackgroundServices.WatchFolderChecker.ExecuteAsync(CancellationToken stoppingToken) in /appserver/server/RdtClient.Service/BackgroundServices/WatchFolderChecker.cs:line 40
2023-05-13 13:55:50.274 +00:00 [WRN] Microsoft.AspNetCore.DataProtection.Repositories.EphemeralXmlRepository: Using an in-memory repository. Keys will not be persisted to storage.
2023-05-13 13:55:50.306 +00:00 [WRN] Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager: Neither user profile nor HKLM registry available. Using an ephemeral key repository. Protected data will be unavailable when application exits.
2023-05-13 13:55:50.322 +00:00 [WRN] Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager: No XML encryptor configured. Key {5e55a0ff-95dd-494b-9494-45a3111e2d39} may be persisted to storage in unencrypted form.
2023-05-13 13:55:50.342 +00:00 [WRN] : Starting host on version 2.0.30.0
2023-05-13 13:55:53.946 +00:00 [WRN] Microsoft.EntityFrameworkCore.Query: The query uses the 'First'/'FirstOrDefault' operator without 'OrderBy' and filter operators. This may lead to unpredictable results.
2023-05-13 14:23:27.688 +00:00 [ERR] RdtClient.Service.BackgroundServices.WatchFolderChecker: Unexpected error occurred in ProviderUpdater: A task was canceled.
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at RdtClient.Service.BackgroundServices.WatchFolderChecker.ExecuteAsync(CancellationToken stoppingToken) in /appserver/server/RdtClient.Service/BackgroundServices/WatchFolderChecker.cs:line 40
2023-05-13 14:30:15.174 +00:00 [WRN] Microsoft.AspNetCore.DataProtection.Repositories.EphemeralXmlRepository: Using an in-memory repository. Keys will not be persisted to storage.
2023-05-13 14:30:15.207 +00:00 [WRN] Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager: Neither user profile nor HKLM registry available. Using an ephemeral key repository. Protected data will be unavailable when application exits.
2023-05-13 14:30:15.223 +00:00 [WRN] Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager: No XML encryptor configured. Key {0e161d69-65db-4d58-8057-179645b7f851} may be persisted to storage in unencrypted form.
2023-05-13 14:30:15.243 +00:00 [WRN] : Starting host on version 2.0.30.0
2023-05-13 14:30:18.674 +00:00 [WRN] Microsoft.EntityFrameworkCore.Query: The query uses the 'First'/'FirstOrDefault' operator without 'OrderBy' and filter operators. This may lead to unpredictable results.
2023-05-13 14:41:14.262 +00:00 [ERR] RdtClient.Service.BackgroundServices.WatchFolderChecker: Unexpected error occurred in ProviderUpdater: A task was canceled.
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at RdtClient.Service.BackgroundServices.WatchFolderChecker.ExecuteAsync(CancellationToken stoppingToken) in /appserver/server/RdtClient.Service/BackgroundServices/WatchFolderChecker.cs:line 40
2023-05-13 14:42:05.367 +00:00 [WRN] Microsoft.AspNetCore.DataProtection.Repositories.EphemeralXmlRepository: Using an in-memory repository. Keys will not be persisted to storage.
2023-05-13 14:42:05.401 +00:00 [WRN] Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager: Neither user profile nor HKLM registry available. Using an ephemeral key repository. Protected data will be unavailable when application exits.
2023-05-13 14:42:05.417 +00:00 [WRN] Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager: No XML encryptor configured. Key {c64b31fe-952e-4063-befa-5f3922b84a36} may be persisted to storage in unencrypted form.
2023-05-13 14:42:05.437 +00:00 [WRN] : Starting host on version 2.0.30.0
2023-05-13 14:42:08.956 +00:00 [WRN] Microsoft.EntityFrameworkCore.Query: The query uses the 'First'/'FirstOrDefault' operator without 'OrderBy' and filter operators. This may lead to unpredictable results.
2023-05-13 15:09:17.114 +00:00 [WRN] : 401: /Api/Authentication/IsLoggedIn
2023-05-13 16:08:40.194 +00:00 [WRN] : 401: /Api/Authentication/IsLoggedIn
2023-05-13 17:37:09.072 +00:00 [WRN] : 304: /favicon.ico
2023-05-13 17:52:26.958 +00:00 [WRN] : 101: /hub
2023-05-13 19:54:21.722 +00:00 [WRN] : 101: /hub
2023-05-13 20:12:54.771 +00:00 [WRN] : 101: /hub
2023-05-13 21:28:33.024 +00:00 [WRN] : 101: /hub
2023-05-13 21:30:32.274 +00:00 [WRN] : 304: /runtime.52f1d05aa6c3afea.js
2023-05-13 21:30:32.274 +00:00 [WRN] : 304: /styles.9638ea5157c483f9.css
2023-05-13 21:30:32.274 +00:00 [WRN] : 304: /main.5aeeb8cd47feeb5b.js
2023-05-13 21:30:32.274 +00:00 [WRN] : 304: /polyfills.9d4d8b2ca59be0bc.js
2023-05-13 21:30:32.571 +00:00 [WRN] : 401: /Api/Authentication/IsLoggedIn
2023-05-13 21:30:32.821 +00:00 [WRN] : 304: /assets/logo.png
2023-05-13 21:30:32.833 +00:00 [WRN] : 304: /fa-solid-900.d5d28b783e396c28.woff2
2023-05-13 21:30:41.624 +00:00 [WRN] : 400: /Api/Authentication/Login

**Comment by darkwst** [comment]
Fixed here what I did a solution for newbies like me 

--------my paths in sonarr -----------

Container Path: /data

host path: /mnt/user/data/

Default value: /mnt/user/data/

my library is set like trash guides

---------------torrents-----------------

/data/torrents/movies

data/torrents/music

/data/torrents/tv

---------------media-----------------

/data/media/movies
data/media/music
/data/media/tv


here what i did, I edited the docker image for sonarr as the following

Container Variable: PUID is set to: 911

Container Variable: PGID is also set to: 911

-------------------- inside sonarr configuration -------------------------

i went to media management

set

chmod Folder to: 777

chown Group: 911


----------------------------------------------------------------------------

also inside of sonarr download client remote path seetings are 

Host: 192.168.8.124
Remote Path: /mnt/user/data/torrents/tv-sonarr/
Local Path: /data/torrents/tv-sonarr/
