### ISSUE TITLE
No Premiumize download server when adding torrents via api

### ISSUE THREAD

**Issue by Gunb0at-Dipl0mat** [rogerfar/rdt-client#260]
Getting below error while trying to add torrents via Sonarr or Prowlarr. It works out fine when manually adding the torrent file or magnet link in the rdt web gui. I confirmed all credentials between the applications.

**What version are you using?**
v2.0.30
**Wat OS are you running?**
Linux - Fedora38 - K3s
**Are you using Docker or as a service?**
Container
**Please attach a log file here with the log setting set to debug**
[22:03:50 INF] UpdateChecker started, currently on version v2.0.30.
[22:03:50 INF] WatchFolderChecker started.
[22:04:35 WRN] 401: /api/v2/torrents/add
[22:04:39 ERR] An unhandled exception has occurred while executing the request.
PremiumizeNET.PremiumizeException: Could not find a download server. Please contact customer service.
   at PremiumizeNET.Requests.Request[T](String url, Boolean requireAuthentication, RequestType requestType, HttpContent data, IDictionary`2 parameters, CancellationToken cancellationToken)
   at PremiumizeNET.Requests.PostFileRequestAsync[T](String url, Byte[] file, String folderId, Boolean requireAuthentication, CancellationToken cancellationToken)
   at PremiumizeNET.TransferApi.CreateAsync(Byte[] file, String folderId, CancellationToken cancellationToken)
   at RdtClient.Service.Services.TorrentClients.PremiumizeTorrentClient.AddFile(Byte[] bytes) in /appserver/server/RdtClient.Service/Services/TorrentClients/PremiumizeTorrentClient.cs:line 125
   at RdtClient.Service.Services.Torrents.UploadFile(Byte[] bytes, Torrent torrent) in /appserver/server/RdtClient.Service/Services/Torrents.cs:line 154
   at RdtClient.Service.Services.QBittorrent.TorrentsAddFile(Byte[] fileBytes, String category, Nullable`1 priority) in /appserver/server/RdtClient.Service/Services/QBittorrent.cs:line 453
   at RdtClient.Web.Controllers.QBittorrentController.TorrentsAddPost(QBTorrentsAddRequest request) in /appserver/server/RdtClient.Web/Controllers/QBittorrentController.cs:line 353
   at RdtClient.Web.Controllers.QBittorrentController.TorrentsAddPost(QBTorrentsAddRequest request) in /appserver/server/RdtClient.Web/Controllers/QBittorrentController.cs:line 353
   at lambda_method143(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Program.<>c.<<<Main>$>b__0_14>d.MoveNext() in /appserver/server/RdtClient.Web/Program.cs:line 159
--- End of stack trace from previous location ---
   at RdtClient.Service.Middleware.AuthorizeMiddleware.Invoke(HttpContext context) in /appserver/server/RdtClient.Service/Middleware/AuthorizeMiddleware.cs:line 22
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
[22:04:43 WRN] The query uses the 'First'/'FirstOrDefault' operator without 'OrderBy' and filter operators. This may lead to unpredictable results.
[22:04:43 WRN] 401: /api/v2/torrents/info

**Comment by Gunb0at-Dipl0mat** [comment]
Issue was with related to the itorrent setting in Prowlarr. Changing to Download Link option to always provide magnet links fixed the problem.
