### ISSUE TITLE
`BasePath` option breaks the whole server

### ISSUE THREAD

**Issue by Willy-JL** [rogerfar/rdt-client#271]
**What version are you using?**
v2.0.31

**Wat OS are you running?**
Debian Linux 12 bookworm

**Are you using Docker or as a service?**
Service

**Please attach a log file here with the log setting set to debug**

The issue is that the `BaseHrefMiddleware` simply writes an updated version of the response content, without changing the HTTP `Content-Length` header appropriately. With curl, this results in no content being sent at all, with curl saying: `curl: (18) transfer closed with 2657 bytes remaining to read` and web browsers just hanging indefinitely.

I would attempt fixing this myself and making a PR, but C# is not my thing.

<details>
<summary>Error log just in case</summary>
<pre>
[12:42:53 ERR] An unhandled exception has occurred while executing the request.
System.InvalidOperationException: Response Content-Length mismatch: too many bytes written (2670 of 2657).
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.VerifyAndUpdateWrite(Int32 count)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.Advance(Int32 bytes)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponsePipeWriter.Advance(Int32 bytes)
   at Microsoft.AspNetCore.Http.HttpResponseWritingExtensions.Write(HttpResponse response, String text, Encoding encoding)
   at Microsoft.AspNetCore.Http.HttpResponseWritingExtensions.WriteAsync(HttpResponse response, String text, Encoding encoding, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.HttpResponseWritingExtensions.WriteAsync(HttpResponse response, String text, CancellationToken cancellationToken)
   at RdtClient.Service.Middleware.BaseHrefMiddleware.InvokeAsync(HttpContext context, AppSettings appSettings) in C:\Projects\rdt-client\server\RdtClient.Service\Middleware\BaseHrefMiddleware.cs:line 42
   at Program.<>c.<<<Main>$>b__0_14>d.MoveNext() in C:\Projects\rdt-client\server\RdtClient.Web\Program.cs:line 159
--- End of stack trace from previous location ---
   at RdtClient.Service.Middleware.AuthorizeMiddleware.Invoke(HttpContext context) in C:\Projects\rdt-client\server\RdtClient.Service\Middleware\AuthorizeMiddleware.cs:line 22
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
[12:42:53 WRN] The response has already started, the error handler will not be executed.
[12:42:53 ERR] Connection id "0HMRMVD19DJFK", Request id "0HMRMVD19DJFK:00000002": An unhandled exception was thrown by the application.
System.InvalidOperationException: Response Content-Length mismatch: too many bytes written (2670 of 2657).
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.VerifyAndUpdateWrite(Int32 count)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.Advance(Int32 bytes)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponsePipeWriter.Advance(Int32 bytes)
   at Microsoft.AspNetCore.Http.HttpResponseWritingExtensions.Write(HttpResponse response, String text, Encoding encoding)
   at Microsoft.AspNetCore.Http.HttpResponseWritingExtensions.WriteAsync(HttpResponse response, String text, Encoding encoding, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.HttpResponseWritingExtensions.WriteAsync(HttpResponse response, String text, CancellationToken cancellationToken)
   at RdtClient.Service.Middleware.BaseHrefMiddleware.InvokeAsync(HttpContext context, AppSettings appSettings) in C:\Projects\rdt-client\server\RdtClient.Service\Middleware\BaseHrefMiddleware.cs:line 42
   at Program.<>c.<<<Main>$>b__0_14>d.MoveNext() in C:\Projects\rdt-client\server\RdtClient.Web\Program.cs:line 159
--- End of stack trace from previous location ---
   at RdtClient.Service.Middleware.AuthorizeMiddleware.Invoke(HttpContext context) in C:\Projects\rdt-client\server\RdtClient.Service\Middleware\AuthorizeMiddleware.cs:line 22
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.HandleException(HttpContext context, ExceptionDispatchInfo edi)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
</pre>
</details>

**Comment by rogerfar** [comment]
Can you try 2.0.32 and see if it fixes it?

**Comment by Willy-JL** [comment]
> Can you try 2.0.32 and see if it fixes it?

progress, definitely. now the webserver responds atleast. another issue now tho.

the html response is correctly altered, and tries to fetch the assets in the right place, like `example.com/basepath/favicon.ico`. problem is, the router is not aware of the basepath, so to it `/basepath/favicon.ico` does not exist, so it replies with an empty html, always. this means that all assets, css, js and so on, just return the standard empty html data, so the page remains blank and unusable.

i'd imagine this could be fixed by checking in the router if the path starts with the basepath, and popping it off the start of the path string

**Comment by rogerfar** [comment]
Not sure what you mean, I have it setup in IIS as `localhost/rdt`, the body of the HTML is like this:
```
<base href="[/rdt/](http://localhost/rdt/)">
...
<link rel="icon" type="image/x-icon" href="[/rdt/favicon.ico](http://localhost/rdt/favicon.ico)">
<script src="[/rdt/runtime.52f1d05aa6c3afea.js](http://localhost/rdt/runtime.52f1d05aa6c3afea.js)" type="module">
```

The console reports it as resolved:
![image](https://github.com/rogerfar/rdt-client/assets/1142915/b2a483bb-c03c-4ba0-8f80-8892b18b4c6f)

Which router do you mean?

**Comment by Willy-JL** [comment]
maybe this is also something to look at?

https://angular.io/api/common/APP_BASE_HREF

**Comment by rogerfar** [comment]
That's implemented here:
https://github.com/rogerfar/rdt-client/blob/cac5a3b3fc3674eed93769970609064c59998430/client/src/app/app.module.ts#L57

**Comment by Willy-JL** [comment]
yea i noticed right after commenting about it, the other 2 still stand tho

**Comment by rogerfar** [comment]
How are you testing this? Because if I try `localhost/favicon.ico` it returns a 404. But the favicon is also handled outside of the angular router, that's all done in .NET.

**Comment by Willy-JL** [comment]
im testing this in as many ways as i can. im doing it on a public self hosted server. mostly, im always trying (and always getting the same results) using a apache proxypass like rdt.example.com, another like example.com/rdt, and also ssh'd into the box, using curl directly on the rdt client instance. ill use the localhost curl example to rule out as many other possible causes like apache, but i get consistent results via apache and the browser.

basepath is set to `/rdt`, port is set to `6500`
`curl localhost:6500` gets me the main html
`curl localhost:6500/` gets me the main html
`curl localhost:6500/rdt` gets me the main html
`curl localhost:6500/rdt/` gets me the main html
`curl localhost:6500/rdt/favicon.ico` gets me the main html
`curl localhost:6500/favicon.ico` gets me the actual icon

i piped all the results into `md5sum`, all the "main html"s i listed are all the exact same. as in, they all already have the script and asset paths replaced to rdt/styles... but of course the app is not usable in this state, because localhost:6500/rdt/runtime... retuns the same exact html data, so the page is completely non functional

**Comment by kungfoolfighting** [comment]
I can't get the base_url to work either.

**Comment by rogerfar** [comment]
@kungfoolfighting did you use the latest version? That was fixed in there.

**Comment by rogerfar** [comment]
Can you post the full log so I can see what URL is being called?
