### ISSUE TITLE
Downloaded Files have URL encoded titles instead of normal ones

### ISSUE THREAD

**Issue by amanagarwal-sopho** [rogerfar/rdt-client#29]
When i download a torrent the files inside it have url encoded names while the folder have proper names.

For ex-
When i download a torrent called `Mission - Impossible III (2006) (1080p BluRay x265 HEVC 10bit AAC 5.1 Tigole)` the file gets renamed to
`Mission%20-%20Impossible%20III%20%282006%29%20%281080p%20BluRay%20x265%2010bit%20Tigole%29.mkv`
instead of 
`Mission - Impossible III (2006) (1080p BluRay x265 HEVC 10bit AAC 5.1 Tigole)`

**Comment by rogerfar** [comment]
What version are you on?

**Comment by amanagarwal-sopho** [comment]
I'm using the latest docker image.

**Comment by rogerfar** [comment]
This shouldn't happen with the latest images, can you double check that the interface shows version 1.5.4 in the right top Account menu?

**Comment by amanagarwal-sopho** [comment]
It doesn't actually. The version is 0.8.0 in the image i'm using. I just used the command in the ReadMe to whip up a container. Will adding the latest tag give me the current image?

**Comment by rogerfar** [comment]
Maybe, try just removing the image `docker stop rogerfar/rdtclient` and then `docker rm rogerfar/rdtclient`, then running again.

**Comment by amanagarwal-sopho** [comment]
I did try that already and i was getting the same version.

**Comment by rogerfar** [comment]
You can try deleting the actual image first: `docker image rm -f rogerfar/rdtclient`. Then it should re-pull from docker.

**Comment by amanagarwal-sopho** [comment]
Did that just now and i think i have the latest image that was created 17 hours ago. Let's see if this works. Thanks for such a quick reply.

**Comment by rogerfar** [comment]
I just released a new version, when I tried updating I noticed that docker doesn't always pull in the new version of the image automatically. If you use `docker run` try the new `--pull always` switch, I updated it in the readme.

**Comment by amanagarwal-sopho** [comment]
The new image is giving me this error

``` Caught exception while emitting to sink Serilog.Sinks.File.RollingFileSink: System.UnauthorizedAccessException: Access to the path '/data/db/rdtclient.log' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.File.Open(String path, FileMode mode, FileAccess access, FileShare share)
   at Serilog.Sinks.File.FileSink..ctor(String path, ITextFormatter textFormatter, Nullable`1 fileSizeLimitBytes, Encoding encoding, Boolean buffered, FileLifecycleHooks hooks)
   at Serilog.Sinks.File.RollingFileSink.OpenFile(DateTime now, Nullable`1 minSequence)
   at Serilog.Sinks.File.RollingFileSink.AlignCurrentFileTo(DateTime now, Boolean nextSequence)
   at Serilog.Sinks.File.RollingFileSink.Emit(LogEvent logEvent)
   at Serilog.Core.Sinks.SafeAggregateSink.Emit(LogEvent logEvent)
```

**Comment by rogerfar** [comment]
Try removing your db file and log file, they probably have the wrong permissions.

**Comment by amanagarwal-sopho** [comment]
I have tried changing their permission and it has access to the directory where the database files are stored, but still it keeps me giving this error.

**Comment by amanagarwal-sopho** [comment]
I got it working by giving it a read/write access to all users and the app is deployed but i still see the version 0.8.0 so don't know if the fix for it will still work will give it a try.
