### ISSUE TITLE
[Bug] Unable to deserialize Premiumize API response

### ISSUE THREAD

**Issue by jeffjohnson11** [rogerfar/rdt-client#297]
**What version are you using?** 2.0.32

**Wat OS are you running?** Docker compose image 'rogerfar/rdtclient'

**Are you using Docker or as a service?** Docker

When adding a torrent via radarr I am getting following error message. I think it is because the torrent is directly linking to the .mkv file and does not create a folder in premiumize.me. Please help.

[16:39:31 DBG] Processing for torrent No.Country.for.Old.Men.2007.1080p.BluRay.10bit.HEVC.6CH-MkvCage.ws.mkv (iCXabLGfM_GFZIHsTlTjlg - finished 100%) (3091c657-957a-4e88-924b-68705ea2394e)
[16:39:31 DBG] Creating downloads for torrent No.Country.for.Old.Men.2007.1080p.BluRay.10bit.HEVC.6CH-MkvCage.ws.mkv (iCXabLGfM_GFZIHsTlTjlg - finished 100%) (3091c657-957a-4e88-924b-68705ea2394e)
[16:39:31 DBG] Method: GET, Path: /api/v2/app/webapiVersion
[16:39:31 DBG] Method: GET, Path: /api/v2/app/preferences
[16:39:31 DBG] Method: GET, Path: /api/v2/torrents/info, QueryString: ?category=radarr
[16:39:31 DBG] Found 8 transfers for torrent No.Country.for.Old.Men.2007.1080p.BluRay.10bit.HEVC.6CH-MkvCage.ws.mkv (iCXabLGfM_GFZIHsTlTjlg - finished 100%) (3091c657-957a-4e88-924b-68705ea2394e)
[16:39:31 ERR] Unable to deserialize Premiumize API response to ItemContent. Response was: {"id":"_8uFaxxxxxxxxxxxxxxxQ","user_id":"xxxxxx","customer_id":"xxxxxxx","name":"No.Country.for.Old.Men.2007.1080p.BluRay.10bit.HEVC.6CH-MkvCage.ws.mkv","size":3225816913,"created_at":1692801570,"transcode_status":"finished","folder_id":"xxxxxxxxxx","server_name":"glamorousbaboon","acodec":"aac","vcodec":"hevc","mime_type":"video\/x-matroska","opensubtitles_hash":"70e44ab38aebbfdc","resx":null,"resy":null,"duration":null,"virus_scan":null,"audio_track_names":[null],"type":"file","link":"https:\/\/glamorousbaboon-sto.energycdn.com\/dl\/xxxxxxxxxxxxxxxxx\/No.Country.for.Old.Men.2007.1080p.BluRay.10bit.HEVC.6CH-MkvCage.ws.mkv","stream_link":"https:\/\/glamorousbaboon-sto.energycdn.com\/dl\/xxxxxxxxxxxxxxxx\/5cec6403473d66.01174257_default.mp4\/No.Country.for.Old.Men.2007.1080p.BluRay.10bit.HEVC.6CH-MkvCage.ws.mkv.mp4"}. Error converting value {null} to type 'System.Int64'. Path 'resx', line 1, position 412.

**Comment by neo8848** [comment]
seems like the same issue I am having :
running on oracle freetier, ubuntu lts docker


---> AllDebridNET.AllDebridException: Servers are not allowed to use this feature. Visit https://alldebrid.com/vpn if you're using a VPN. (NO_SERVER)
   at AllDebridNET.Requests.Request[T](String url, Boolean requireAuthentication, RequestType requestType, HttpContent data, IDictionary`2 parameters, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at AllDebridNET.Requests.Request[T](String url, Boolean requireAuthentication, RequestType requestType, HttpContent data, IDictionary`2 parameters, CancellationToken cancellationToken)
   at AllDebridNET.Requests.GetRequestAsync[T](String url, Boolean requireAuthentication, IDictionary`2 parameters, CancellationToken cancellationToken)
   at AllDebridNET.LinksApi.DownloadLinkAsync(String link, String password, CancellationToken cancellationToken)
   at RdtClient.Service.Services.TorrentClients.AllDebridTorrentClient.Unrestrict(String link) in /appserver/server/RdtClient.Service/Services/TorrentClients/AllDebridTorrentClient.cs:line 176
   at RdtClient.Service.Services.Torrents.UnrestrictLink(Guid downloadId) in /appserver/server/RdtClient.Service/Services/Torrents.cs:line 332
   at RdtClient.Service.Services.TorrentRunner.Tick() in /appserver/server/RdtClient.Service/Services/TorrentRunner.cs:line 335
[10:22:23 ERR] Cannot unrestrict link: {ex.Message}
System.Exception: Unable to deserialize AllDebrid API response to DownloadLink. Response was: {
    "status": "error",
    "error": {
        "code": "NO_SERVER",
        "message": "Servers are not allowed to use this feature. Visit https:\/\/alldebrid.com\/vpn if you're using a VPN."
    }
}

**Comment by rogerfar** [comment]
@neo8848 your error is: Servers are not allowed to use this feature. Visit https://alldebrid.com/vpn if you're using a VPN.

@jeffjohnson11 This will be fixed in 2.0.33.
