### ISSUE TITLE
SQLLite Error 14

### ISSUE THREAD

**Issue by handshake87** [rogerfar/rdt-client#30]
While under the settings using the Docker image I get the following error

Could not test your download speed
SQLite Error 14: 'unable to open database file'.

This is for the Test RealDebrid download speed

**Comment by no-usr-nm** [comment]
@handshake87 how did you fix this issue. I am seeing a similar error

```
2021-03-14T20:20:18.0517623Z Caught exception while emitting to sink Serilog.Sinks.File.RollingFileSink: System.UnauthorizedAccessException: Access to the path '/data/db/rdtclient.log' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.File.Open(String path, FileMode mode, FileAccess access, FileShare share)
   at Serilog.Sinks.File.FileSink..ctor(String path, ITextFormatter textFormatter, Nullable`1 fileSizeLimitBytes, Encoding encoding, Boolean buffered, FileLifecycleHooks hooks)
   at Serilog.Sinks.File.RollingFileSink.OpenFile(DateTime now, Nullable`1 minSequence)
   at Serilog.Sinks.File.RollingFileSink.AlignCurrentFileTo(DateTime now, Boolean nextSequence)
   at Serilog.Sinks.File.RollingFileSink.Emit(LogEvent logEvent)
   at Serilog.Core.Sinks.SafeAggregateSink.Emit(LogEvent logEvent)
[20:20:18 DBG] An 'IServiceProvider' was created for internal use by Entity Framework.
[20:20:18 DBG] The index {'UserId'} was not created on entity type 'IdentityUserRole<string>' as the properties are already covered by the index {'UserId', 'RoleId'}.
[20:20:18 DBG] The index {'UserId'} was not created on entity type 'IdentityUserToken<string>' as the properties are already covered by the index {'UserId', 'LoginProvider', 'Name'}.
[20:20:18 INF] Entity Framework Core 5.0.3 initialized 'DataContext' using provider 'Microsoft.EntityFrameworkCore.Sqlite' with options: None
[20:20:19 DBG] Migrating using database 'main' on server '/data/db/rdtclient.db'.
[20:20:19 DBG] Opening connection to database 'main' on server '/data/db/rdtclient.db'.
[20:20:19 DBG] An error occurred using the connection to database 'main' on server '/data/db/rdtclient.db'.
[20:20:19 DBG] Opening connection to database 'main' on server '/data/db/rdtclient.db'.
[20:20:19 DBG] An error occurred using the connection to database 'main' on server '/data/db/rdtclient.db'.
[20:20:19 DBG] Opening connection to database 'main' on server '/data/db/rdtclient.db'.
[20:20:19 ERR] An error occurred using the connection to database 'main' on server '/data/db/rdtclient.db'.
[20:20:19 DBG] 'DataContext' disposed.
[20:20:19 FTL] Host terminated unexpectedly
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 14: 'unable to open database file'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnection(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternal(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal.SqliteDatabaseCreator.Create()
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.CreateAsync(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.MigrateAsync(String targetMigration, CancellationToken cancellationToken)
   at RdtClient.Web.Program.Main(String[] args) in /appserver/RdtClient.Web/Program.cs:line 33
   ```

**Comment by letunglam** [comment]
I have same error while running docker on linux

**Comment by rogerfar** [comment]
Did you delete the DB and log file and have RDT create them?

**Comment by letunglam** [comment]
I solved it now by give the correct permission for the mapped folder.

**Comment by handshake87** [comment]
How did you solve it? I am still having issues. I get the page to come up but when I try to login or anything I get the SQL error. This was using a fresh folder.

**Comment by letunglam** [comment]
I give the correct permission so it can write the database into it.

**Comment by handshake87** [comment]
> I give the correct permission so it can write the database into it.

Can you please explain a little further... I still am unable to get this working

**Comment by rogerfar** [comment]
What permission does the path have you put in your docker file?
