### ISSUE TITLE
[BUG] The file '/data/downloads/sonarr' already exists.

### ISSUE THREAD

**Issue by JReming85** [rogerfar/rdt-client#300]
**What version are you using?**
Latest docker 2.0.32

**Wat OS are you running?**
Ubuntu 20.04.6 LTS

**Are you using Docker or as a service?**
Docker

**Please attach a log file here with the log setting set to debug**
![image](https://github.com/rogerfar/rdt-client/assets/21246660/1124629a-71e7-4f1c-a5f6-93ac7d79f6f3)
![image](https://github.com/rogerfar/rdt-client/assets/21246660/c0d52b66-adee-46c9-8c26-a9f726573526)
![image](https://github.com/rogerfar/rdt-client/assets/21246660/332daec6-1319-497c-8586-6d2d73e26b05)

Docker Logs
```
[22:06:47 ERR] An unhandled exception has occurred while executing the request.
System.IO.IOException: The file '/data/downloads/sonarr' already exists.
   at System.IO.FileSystem.CreateDirectory(String fullPath)
   at System.IO.Directory.CreateDirectory(String path)
   at RdtClient.Service.Helpers.DownloadHelper.GetDownloadPath(String downloadPath, Torrent torrent, Download download) in /appserver/server/RdtClient.Service/Helpers/DownloadHelper.cs:line 18
   at RdtClient.Service.Services.Torrents.RetryDownload(Guid downloadId) in /appserver/server/RdtClient.Service/Services/Torrents.cs:line 511
   at RdtClient.Web.Controllers.TorrentsController.RetryDownload(Guid downloadId) in /appserver/server/RdtClient.Web/Controllers/TorrentsController.cs:line 189
   at lambda_method728(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at RdtClient.Service.Middleware.RequestLoggingMiddleware.Invoke(HttpContext context) in /appserver/server/RdtClient.Service/Middleware/RequestLoggingMiddleware.cs:line 47
   at Program.<>c.<<<Main>$>b__0_14>d.MoveNext() in /appserver/server/RdtClient.Web/Program.cs:line 165
--- End of stack trace from previous location ---
   at RdtClient.Service.Middleware.AuthorizeMiddleware.Invoke(HttpContext context) in /appserver/server/RdtClient.Service/Middleware/AuthorizeMiddleware.cs:line 28
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
```
DB folder log
```
2023-08-31 22:02:22.425 +00:00 [ERR] RdtClient.Service.Services.TorrentRunner: Download reported an error: An unexpected error occurred preparing download https://den1.download.real-debrid.com/d/XXXXXXXXXXXXXXX/Destined.with.You.S01E02.1080p.WEB.h264-EDITH%5Beztv.re%5D.mkv for torrent Destined.with.You.S01E02.1080p.WEB.h264-EDITH[eztv.re].mkv: The file '/data/downloads/sonarr' already exists. for download Destined.with.You.S01E02.1080p.WEB.h264-EDITH[eztv.re].mkv. Completed: -2147483648%, avg speed: 0bytes/s (fae81ad4-d467-4c3d-8c4c-d2e4e837c1cc) for torrent Destined.with.You.S01E02.1080p.WEB.h264-EDITH[eztv.re].mkv (WC2K5LAOOAN4G - downloaded 100%) (daf778c7-28ce-4a39-92a0-bedf1265c747)
2023-08-31 22:02:23.544 +00:00 [ERR] RdtClient.Service.Services.TorrentRunner: Download reported an error: An unexpected error occurred preparing download https://den1.download.real-debrid.com/d/XXXXXXXXXXXXXXX/Destined.with.You.S01E02.1080p.WEB.h264-EDITH%5Beztv.re%5D.mkv for torrent Destined.with.You.S01E02.1080p.WEB.h264-EDITH[eztv.re].mkv: The file '/data/downloads/sonarr' already exists. for download Destined.with.You.S01E02.1080p.WEB.h264-EDITH[eztv.re].mkv. Completed: -2147483648%, avg speed: 0bytes/s (fae81ad4-d467-4c3d-8c4c-d2e4e837c1cc) for torrent Destined.with.You.S01E02.1080p.WEB.h264-EDITH[eztv.re].mkv (WC2K5LAOOAN4G - downloaded 100%) (daf778c7-28ce-4a39-92a0-bedf1265c747)
2023-08-31 22:02:24.664 +00:00 [ERR] RdtClient.Service.Services.TorrentRunner: Download reported an error: An unexpected error occurred preparing download https://den1.download.real-debrid.com/d/XXXXXXXXXXXXXXX/Destined.with.You.S01E02.1080p.WEB.h264-EDITH%5Beztv.re%5D.mkv for torrent Destined.with.You.S01E02.1080p.WEB.h264-EDITH[eztv.re].mkv: The file '/data/downloads/sonarr' already exists. for download Destined.with.You.S01E02.1080p.WEB.h264-EDITH[eztv.re].mkv. Completed: -2147483648%, avg speed: 0bytes/s (fae81ad4-d467-4c3d-8c4c-d2e4e837c1cc) for torrent Destined.with.You.S01E02.1080p.WEB.h264-EDITH[eztv.re].mkv (WC2K5LAOOAN4G - downloaded 100%) (daf778c7-28ce-4a39-92a0-bedf1265c747)
2023-08-31 22:02:25.788 +00:00 [ERR] RdtClient.Service.Services.TorrentRunner: Download reported an error: An unexpected error occurred preparing download https://den1.download.real-debrid.com/d/XXXXXXXXXXXXXXX/Destined.with.You.S01E02.1080p.WEB.h264-EDITH%5Beztv.re%5D.mkv for torrent Destined.with.You.S01E02.1080p.WEB.h264-EDITH[eztv.re].mkv: The file '/data/downloads/sonarr' already exists. for download Destined.with.You.S01E02.1080p.WEB.h264-EDITH[eztv.re].mkv. Completed: -2147483648%, avg speed: 0bytes/s (fae81ad4-d467-4c3d-8c4c-d2e4e837c1cc) for torrent Destined.with.You.S01E02.1080p.WEB.h264-EDITH[eztv.re].mkv (WC2K5LAOOAN4G - downloaded 100%) (daf778c7-28ce-4a39-92a0-bedf1265c747)
2023-08-31 22:02:33.155 +00:00 [ERR] RdtClient.Service.Services.TorrentRunner: Download reported an error: An unexpected error occurred preparing download https://den1.download.real-debrid.com/d/XXXXXXXXXXXXXXX/Destined.with.You.S01E02.1080p.WEB.h264-EDITH%5Beztv.re%5D.mkv for torrent Destined.with.You.S01E02.1080p.WEB.h264-EDITH[eztv.re].mkv: The file '/data/downloads/sonarr' already exists. for download Destined.with.You.S01E02.1080p.WEB.h264-EDITH[eztv.re].mkv. Completed: -2147483648%, avg speed: 0bytes/s (a4c04adb-b51e-40ef-a4a7-967708a61c46) for torrent Destined.with.You.S01E02.1080p.WEB.h264-EDITH[eztv.re].mkv (PVMZU7DG4LA3I - downloaded 100%) (efdc4a1e-38c4-4bb7-9e89-65882319d732)
2023-08-31 22:02:34.275 +00:00 [ERR] RdtClient.Service.Services.TorrentRunner: Download reported an error: An unexpected error occurred preparing download https://den1.download.real-debrid.com/d/XXXXXXXXXXXXXXX/Destined.with.You.S01E02.1080p.WEB.h264-EDITH%5Beztv.re%5D.mkv for torrent Destined.with.You.S01E02.1080p.WEB.h264-EDITH[eztv.re].mkv: The file '/data/downloads/sonarr' already exists. for download Destined.with.You.S01E02.1080p.WEB.h264-EDITH[eztv.re].mkv. Completed: -2147483648%, avg speed: 0bytes/s (a4c04adb-b51e-40ef-a4a7-967708a61c46) for torrent Destined.with.You.S01E02.1080p.WEB.h264-EDITH[eztv.re].mkv (PVMZU7DG4LA3I - downloaded 100%) (efdc4a1e-38c4-4bb7-9e89-65882319d732)
2023-08-31 22:02:35.395 +00:00 [ERR] RdtClient.Service.Services.TorrentRunner: Download reported an error: An unexpected error occurred preparing download https://den1.download.real-debrid.com/d/XXXXXXXXXXXXXXX/Destined.with.You.S01E02.1080p.WEB.h264-EDITH%5Beztv.re%5D.mkv for torrent Destined.with.You.S01E02.1080p.WEB.h264-EDITH[eztv.re].mkv: The file '/data/downloads/sonarr' already exists. for download Destined.with.You.S01E02.1080p.WEB.h264-EDITH[eztv.re].mkv. Completed: -2147483648%, avg speed: 0bytes/s (a4c04adb-b51e-40ef-a4a7-967708a61c46) for torrent Destined.with.You.S01E02.1080p.WEB.h264-EDITH[eztv.re].mkv (PVMZU7DG4LA3I - downloaded 100%) (efdc4a1e-38c4-4bb7-9e89-65882319d732)
2023-08-31 22:02:36.513 +00:00 [ERR] RdtClient.Service.Services.TorrentRunner: Download reported an error: An unexpected error occurred preparing download https://den1.download.real-debrid.com/d/XXXXXXXXXXXXXXX/Destined.with.You.S01E02.1080p.WEB.h264-EDITH%5Beztv.re%5D.mkv for torrent Destined.with.You.S01E02.1080p.WEB.h264-EDITH[eztv.re].mkv: The file '/data/downloads/sonarr' already exists. for download Destined.with.You.S01E02.1080p.WEB.h264-EDITH[eztv.re].mkv. Completed: -2147483648%, avg speed: 0bytes/s (a4c04adb-b51e-40ef-a4a7-967708a61c46) for torrent Destined.with.You.S01E02.1080p.WEB.h264-EDITH[eztv.re].mkv (PVMZU7DG4LA3I - downloaded 100%) (efdc4a1e-38c4-4bb7-9e89-65882319d732)
2023-08-31 22:06:47.214 +00:00 [ERR] Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware: An unhandled exception has occurred while executing the request.
System.IO.IOException: The file '/data/downloads/sonarr' already exists.
   at System.IO.FileSystem.CreateDirectory(String fullPath)
   at System.IO.Directory.CreateDirectory(String path)
   at RdtClient.Service.Helpers.DownloadHelper.GetDownloadPath(String downloadPath, Torrent torrent, Download download) in /appserver/server/RdtClient.Service/Helpers/DownloadHelper.cs:line 18
   at RdtClient.Service.Services.Torrents.RetryDownload(Guid downloadId) in /appserver/server/RdtClient.Service/Services/Torrents.cs:line 511
   at RdtClient.Web.Controllers.TorrentsController.RetryDownload(Guid downloadId) in /appserver/server/RdtClient.Web/Controllers/TorrentsController.cs:line 189
   at lambda_method728(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at RdtClient.Service.Middleware.RequestLoggingMiddleware.Invoke(HttpContext context) in /appserver/server/RdtClient.Service/Middleware/RequestLoggingMiddleware.cs:line 47
   at Program.<>c.<<<Main>$>b__0_14>d.MoveNext() in /appserver/server/RdtClient.Web/Program.cs:line 165
--- End of stack trace from previous location ---
   at RdtClient.Service.Middleware.AuthorizeMiddleware.Invoke(HttpContext context) in /appserver/server/RdtClient.Service/Middleware/AuthorizeMiddleware.cs:line 28
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
2023-08-31 22:13:47.591 +00:00 [WRN] : 101: /hub
2023-08-31 22:16:22.801 +00:00 [ERR] RdtClient.Service.BackgroundServices.WatchFolderChecker: Unexpected error occurred in ProviderUpdater: A task was canceled.
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at RdtClient.Service.BackgroundServices.WatchFolderChecker.ExecuteAsync(CancellationToken stoppingToken) in /appserver/server/RdtClient.Service/BackgroundServices/WatchFolderChecker.cs:line 40
2023-08-31 22:16:29.294 +00:00 [WRN] Microsoft.AspNetCore.DataProtection.Repositories.EphemeralXmlRepository: Using an in-memory repository. Keys will not be persisted to storage.
2023-08-31 22:16:29.351 +00:00 [WRN] Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager: Neither user profile nor HKLM registry available. Using an ephemeral key repository. Protected data will be unavailable when application exits.
2023-08-31 22:16:29.379 +00:00 [WRN] Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager: No XML encryptor configured. Key {xxxx} may be persisted to storage in unencrypted form.
2023-08-31 22:16:29.424 +00:00 [WRN] : Starting host on version 2.0.32.0
2023-08-31 22:16:31.387 +00:00 [INF] RdtClient.Service.BackgroundServices.TaskRunner: TaskRunner started.
2023-08-31 22:16:31.397 +00:00 [DBG] RdtClient.Service.Services.TorrentRunner: Initializing TorrentRunner
2023-08-31 22:16:31.421 +00:00 [INF] RdtClient.Service.BackgroundServices.TaskRunner: ProviderUpdater started.
2023-08-31 22:16:31.522 +00:00 [DBG] RdtClient.Service.Services.TorrentRunner: {"General":{"LogLevel":0,"DownloadLimit":2,"UnpackLimit":1,"Categories":"sonarr,radarr,prowlarr","RunOnTorrentCompleteFileName":null,"RunOnTorrentCompleteArguments":null,"AuthenticationType":0},"DownloadClient":{"Client":0,"DownloadPath":"/data/downloads","MappedPath":"/home/xxxxxxx/torrents/qbittorrent","MaxSpeed":0,"ParallelCount":0,"Timeout":5000,"ProxyServer":null,"Aria2cUrl":"http://127.0.0.1:6800/jsonrpc","Aria2cSecret":"*****"},"Provider":{"Provider":0,"ApiKey":"*****","AutoImport":false,"AutoDelete":false,"Timeout":10,"CheckInterval":10,"Default":{"Category":null,"FinishedAction":1,"OnlyDownloadAvailableFiles":true,"MinFileSize":0,"TorrentRetryAttempts":1,"DownloadRetryAttempts":3,"DeleteOnError":0,"TorrentLifetime":0,"Priority":0}},"Integrations":{"Default":{"HostDownloadAction":0,"Category":null,"FinishedAction":1,"OnlyDownloadAvailableFiles":true,"MinFileSize":0,"TorrentRetryAttempts":1,"DownloadRetryAttempts":3,"DeleteOnError":0,"TorrentLifetime":0,"Priority":0}},"Gui":{"Default":{"HostDownloadAction":0,"Category":null,"FinishedAction":1,"OnlyDownloadAvailableFiles":true,"MinFileSize":0,"TorrentRetryAttempts":1,"DownloadRetryAttempts":3,"DeleteOnError":0,"TorrentLifetime":0,"Priority":0}},"Watch":{"Path":null,"ErrorPath":null,"ProcessedPath":null,"Interval":60,"Default":{"HostDownloadAction":0,"Category":null,"FinishedAction":1,"OnlyDownloadAvailableFiles":true,"MinFileSize":0,"TorrentRetryAttempts":1,"DownloadRetryAttempts":3,"DeleteOnError":0,"TorrentLifetime":0,"Priority":0}}
2023-08-31 22:16:31.542 +00:00 [INF] RdtClient.Service.BackgroundServices.UpdateChecker: UpdateChecker started, currently on version v2.0.32.
2023-08-31 22:16:31.613 +00:00 [INF] RdtClient.Service.BackgroundServices.WatchFolderChecker: WatchFolderChecker started.
2023-08-31 22:16:31.734 +00:00 [DBG] RdtClient.Service.BackgroundServices.TaskRunner: Updating torrent info from Real-Debrid
2023-08-31 22:16:31.735 +00:00 [DBG] RdtClient.Service.Services.TorrentRunner: Found 0 not completed torrents
2023-08-31 22:16:31.735 +00:00 [DBG] RdtClient.Service.Services.TorrentRunner: TorrentRunner Initialized
2023-08-31 22:16:33.104 +00:00 [DBG] RdtClient.Service.BackgroundServices.TaskRunner: Finished updating torrent info from Real-Debrid, next update in 30 seconds
2023-08-31 22:17:02.326 +00:00 [DBG] RdtClient.Service.Middleware.RequestLoggingMiddleware: Method: GET, Path: /api/v2/app/webapiVersion
2023-08-31 22:17:02.432 +00:00 [DBG] RdtClient.Service.Middleware.RequestLoggingMiddleware: Method: GET, Path: /api/v2/app/preferences
2023-08-31 22:17:02.732 +00:00 [DBG] RdtClient.Service.BackgroundServices.TaskRunner: Updating torrent info from Real-Debrid
2023-08-31 22:17:02.763 +00:00 [DBG] RdtClient.Service.Middleware.RequestLoggingMiddleware: Method: GET, Path: /api/v2/torrents/info, QueryString: ?category=sonarr
2023-08-31 22:17:02.773 +00:00 [WRN] : 401: /api/v2/torrents/info
2023-08-31 22:17:02.864 +00:00 [DBG] RdtClient.Service.Middleware.RequestLoggingMiddleware: Method: POST, Path: /api/v2/auth/login, Form: username: xxx, password: xxx
2023-08-31 22:17:03.118 +00:00 [DBG] RdtClient.Service.Middleware.RequestLoggingMiddleware: Method: GET, Path: /api/v2/torrents/info, QueryString: ?category=sonarr
2023-08-31 22:17:03.431 +00:00 [DBG] RdtClient.Service.BackgroundServices.TaskRunner: Finished updating torrent info from Real-Debrid, next update in 30 seconds
2023-08-31 22:17:33.055 +00:00 [DBG] RdtClient.Service.BackgroundServices.TaskRunner: Updating torrent info from Real-Debrid
2023-08-31 22:17:33.760 +00:00 [DBG] RdtClient.Service.BackgroundServices.TaskRunner: Finished updating torrent info from Real-Debrid, next update in 30 seconds
```

I am assuming this is because the torrent is just a video file without a folder.

**Comment by JReming85** [comment]
I just re-setup the app on bare metal instead of docker and it looks like its working fine with single files.

Not sure what the problem was, maybe it didnt like a symlink category file?

**Comment by rogerfar** [comment]
Try the latest version, there were some fixes made there too.
