### ISSUE TITLE
BasePath is not working with radarr

### ISSUE THREAD

**Issue by infraninja** [rogerfar/rdt-client#309]
**What version are you using?**
2.0.32

**Wat OS are you running?**
Host OS - OMV 6.8.0-1/Debian11

**Are you using Docker or as a service?**
Docker

**Which debrid provider are you using?**
real-debrid

**Please attach a log file here with the log setting set to debug**
I tried and couldn't find how to set Debug logging level to my docker container. If someone can tell me how to set my docker service logging level to DEBUG, I will add the logs here.

RDT-Client URL: http://example.com/rdt
Radarr URL: http://example.com/radarr

When I try and add rdt-client as a download client in my radarr, it fails. I removed the BasePath option from the rdtclient's appsetttings.json and it works fine. The logs are below.
```
[01:30:14 ERR] An unhandled exception has occurred while executing the request.
System.InvalidOperationException: The SPA default page middleware could not return the default page '/index.html' because it was not found, and no other middleware handled the request.
Your application is running in Production mode, so make sure it has been published, or that you have built your SPA manually. Alternatively you may wish to switch to the Development environment.

   at Microsoft.AspNetCore.SpaServices.SpaDefaultPageMiddleware.<>c__DisplayClass0_0.<Attach>b__1(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at RdtClient.Service.Middleware.RequestLoggingMiddleware.Invoke(HttpContext context) in /appserver/server/RdtClient.Service/Middleware/RequestLoggingMiddleware.cs:line 47
   at RdtClient.Service.Middleware.BaseHrefMiddleware.InvokeAsync(HttpContext context, AppSettings appSettings) in /appserver/server/RdtClient.Service/Middleware/BaseHrefMiddleware.cs:line 54
   at Program.<>c.<<<Main>$>b__0_14>d.MoveNext() in /appserver/server/RdtClient.Web/Program.cs:line 165
--- End of stack trace from previous location ---
   at RdtClient.Service.Middleware.AuthorizeMiddleware.Invoke(HttpContext context) in /appserver/server/RdtClient.Service/Middleware/AuthorizeMiddleware.cs:line 28
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
[01:30:14 WRN] 401: /api/v2/torrents/info
[01:30:14 ERR] An unhandled exception has occurred while executing the request.
System.InvalidOperationException: StatusCode cannot be set because the response has already started.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ThrowResponseAlreadyStartedException(String value)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.Microsoft.AspNetCore.Http.Features.IHttpResponseFeature.set_StatusCode(Int32 value)
   at RdtClient.Service.Middleware.AuthorizeMiddleware.Invoke(HttpContext context) in /appserver/server/RdtClient.Service/Middleware/AuthorizeMiddleware.cs:line 28
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
[01:30:14 WRN] The response has already started, the error handler will not be executed.
[01:30:14 ERR] Connection id "0HMTIGODLCTOV", Request id "0HMTIGODLCTOV:00000002": An unhandled exception was thrown by the application.
System.InvalidOperationException: StatusCode cannot be set because the response has already started.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ThrowResponseAlreadyStartedException(String value)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.Microsoft.AspNetCore.Http.Features.IHttpResponseFeature.set_StatusCode(Int32 value)
   at RdtClient.Service.Middleware.AuthorizeMiddleware.Invoke(HttpContext context) in /appserver/server/RdtClient.Service/Middleware/AuthorizeMiddleware.cs:line 28
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.HandleException(HttpContext context, ExceptionDispatchInfo edi)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

<img width="1283" alt="image" src="https://github.com/rogerfar/rdt-client/assets/78243730/a67797db-67fa-474e-b346-3464227e6b96">

**Comment by infraninja** [comment]
I guess the problem is the BasePath is not being appended to the URL.

Current:
> [01:30:14 WRN] 401: /api/v2/torrents/info

Expected:
> [01:30:14 WRN] 401: /rdt/api/v2/torrents/info

**Comment by kungfoolfighting** [comment]
I have issues with this, when I restart rdt-client after having already started radarr.
I have to restart radarr every time I restart rdt-client. I guess it has something to do with session cookies or something.

**Comment by rogerfar** [comment]
@infraninja The logs show a 401, which means unauthorized. Are you using the right username + password?

**Comment by rogerfar** [comment]
@infraninja did you get this to work? Seems to me that your host is wrong in the radarr settings?

**Comment by rogerfar** [comment]
If it's still an issue please file a new issue with new logs.
