### ISSUE TITLE
Resource temporarily unavailable on connecting to any provider using Synology Docker

### ISSUE THREAD

**Issue by ZTiKnl** [rogerfar/rdt-client#312]
Hi there,

Using rdtclient in docker on a Synology, latest version (2.0.37) with AllDebrid seems to work during setup, all checks are approved for paths and connection (API key).

Adding a torrent/magnet link, results in the following error:
`Resource temporarily unavailable (api.alldebrid.com:443)`

Trying to access the api directly in a browser, shows the following result:
`{"error":"apiv3 has been discontinued, please migrate to apiv4. See https:\/\/docs.alldebrid.com\/v4\/#general-informations","errorCode":-1}`

Any chance of AD hook being updated to work with v4, or am I overlooking a setting/config somewhere to resolve this issue?

**Comment by ZTiKnl** [comment]
Deleted the container, emptied all folders, redownloaded the image and configured it, issue persists.
(this helped another user with a similar issue: https://github.com/rogerfar/rdt-client/issues/308)

corresponding log on debug mode:
```
2023-09-19 22:21:05.923 +02:00 [ERR] Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware: An unhandled exception has occurred while executing the request.
System.Net.Http.HttpRequestException: Resource temporarily unavailable (api.alldebrid.com:443)
 ---> System.Net.Sockets.SocketException (11): Resource temporarily unavailable
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at AllDebridNET.Requests.Request(String url, Boolean requireAuthentication, RequestType requestType, HttpContent data, IDictionary`2 parameters, CancellationToken cancellationToken)
   at AllDebridNET.Requests.Request[T](String url, Boolean requireAuthentication, RequestType requestType, HttpContent data, IDictionary`2 parameters, CancellationToken cancellationToken)
   at AllDebridNET.Requests.PostRequestAsync[T](String url, IEnumerable`1 data, Boolean requireAuthentication, CancellationToken cancellationToken)
   at AllDebridNET.MagnetApi.UploadMagnetAsync(String magnetLink, CancellationToken cancellationToken)
   at RdtClient.Service.Services.TorrentClients.AllDebridTorrentClient.AddMagnet(String magnetLink) in /appserver/server/RdtClient.Service/Services/TorrentClients/AllDebridTorrentClient.cs:line 109
   at RdtClient.Service.Services.Torrents.UploadMagnet(String magnetLink, Torrent torrent) in /appserver/server/RdtClient.Service/Services/Torrents.cs:line 128
   at RdtClient.Web.Controllers.TorrentsController.UploadMagnet(TorrentControllerUploadMagnetRequest request) in /appserver/server/RdtClient.Web/Controllers/TorrentsController.cs:line 116
   at lambda_method303(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at RdtClient.Service.Middleware.RequestLoggingMiddleware.Invoke(HttpContext context) in /appserver/server/RdtClient.Service/Middleware/RequestLoggingMiddleware.cs:line 47
   at Program.<>c.<<<Main>$>b__0_14>d.MoveNext() in /appserver/server/RdtClient.Web/Program.cs:line 165
--- End of stack trace from previous location ---
   at RdtClient.Service.Middleware.AuthorizeMiddleware.Invoke(HttpContext context) in /appserver/server/RdtClient.Service/Middleware/AuthorizeMiddleware.cs:line 28
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
   ```

**Comment by ZTiKnl** [comment]
And downgrading to an earlier version results in the same error
2.0.36 and 2.0.32

Seems pointless to go back further, but if that is desired, do let me know!

**Comment by ZTiKnl** [comment]
This morning I started up the docker, same error, registered for a real-debrid.com account, SAME ERROR!
Tried to read more of the logfile, and noticed that I get the same error for every outgoing connection.

```
2023-09-20 15:04:16.083 +02:00 [WRN] : 304: /index.html
2023-09-20 15:04:16.418 +02:00 [WRN] : 403: /Api/Authentication/IsLoggedIn
---
2023-09-20 15:04:20.562 +02:00 [DBG] RdtClient.Service.BackgroundServices.UpdateChecker: Unexpected error occurred while checking for updates. This error is safe to ignore.
System.Net.Http.HttpRequestException: Resource temporarily unavailable (api.github.com:443)
---
2023-09-20 15:04:24.433 +02:00 [ERR] Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware: An unhandled exception has occurred while executing the request.
System.Net.Http.HttpRequestException: Resource temporarily unavailable (api.alldebrid.com:443)
---
2023-09-20 15:07:16.559 +02:00 [ERR] Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware: An unhandled exception has occurred while executing the request.
System.AggregateException: One or more errors occurred. (Resource temporarily unavailable (api.real-debrid.com:443))
---
```


So this problem is related to my own network/firewall/permissions configuration...
Will leave this ticket open until I find out whats causing this issue, but the title is misleading.

Note to self: dont file late night bugreports, wait until the next morning to do it with a clear head.

Full log since starting docker this morning:
[rdtclient.log](https://github.com/rogerfar/rdt-client/files/12673475/rdtclient.log)

**Comment by ZTiKnl** [comment]
SOLVED!

The problem:
Configured this docker to run on bridged network.

Solution:
Run the container on the host network, and connecting works with both providers

Leaving this ticket open for the devs to close, perhaps this information should be added to the docs?
This is the case for Synology DSM7.2, but likely all earlier versions as well

**Comment by rogerfar** [comment]
`Resource temporarily unavailable (api.alldebrid.com:443)`

Their server is just down, it has nothing to do with the client or your network.

**Comment by ZTiKnl** [comment]
This is not the case, api.github.com and api.real-debrid.com giving the same error

Switched the docker container to host network and it works
Just switched it back to bridged network to make sure, and all links fail to connect again.

**Comment by ZTiKnl** [comment]
And I just did another test, running 2 docker containers simultaneously, 1 in host network, 1 in bridged network.

Host network container runs on port 6500
Bridged network container runs on port 6501

I can access both locally and remotely
The host container is able to connect to github and real-debrid.
While at the same time...
The bridged container gives `resource temporarily unavailable` for both api.github.com:443 and api.real-debrid.com:443

I didn't bother testing with all-debrid anymore, as it's obvious that this will result in the same outcome.
