### ISSUE TITLE
Torrents stuck on "Queued for downloading" 

### ISSUE THREAD

**Issue by janitory** [rogerfar/rdt-client#32]
Hey,

since 1.6 my downloads are stuck on queued for downloading after the torrent finished. They didn't go into the queue themselves, but I had to manually add them into the queue.
It happens to torrents that were manually added and torrents that were added through sonarr.

Error from the log:

2021-03-12 16:02:54.538 +01:00 [ERR] Unexpected error occurred in TorrentDownloadManager.Tick
System.Exception: {
	"error": "wrong_parameter",
	"error_details": "{link} is invalid",
	"error_code": 2
}
   at RDNET.RdNetClient.Post[T](String url, KeyValuePair`2[] data, Boolean repeatRequest)
   at RDNET.RdNetClient.UnrestrictLinkAsync(String link, String password, Boolean remote)
   at RdtClient.Service.Services.Torrents.UnrestrictLink(Guid downloadId) in /appserver/RdtClient.Service/Services/Torrents.cs:line 233
   at RdtClient.Service.Services.TorrentRunner.Tick() in /appserver/RdtClient.Service/Services/TorrentRunner.cs:line 222
   at RdtClient.Service.Services.TaskRunner.ExecuteAsync(CancellationToken stoppingToken) in /appserver/RdtClient.Service/Services/TaskRunner.cs:line 36

-----
As a side note, thanks for this project. It's pretty handy!

**Comment by janitory** [comment]
I "fixed" it by deleting the rtdclient.db and starting fresh, adding the same torrents back. Restarting the docker and server themselves didn't fix it.

I guess that there was a conflict in the way 1.6 handles downloads with certain removed settings in mind compared to 1.5 (which still worked).

**Comment by rogerfar** [comment]
You're right I didn't think of that. It's possible you have a download without a unrestricted link. To fix just delete and re add the torrent.
