### ISSUE TITLE
Docker won't work again - The connection to Real Debrid has failed

### ISSUE THREAD

**Issue by vnguyen42** [rogerfar/rdt-client#341]
**What version are you using?**
2.0.40

**Wat OS are you running?**
OS X

**Are you using Docker or as a service?**
Docker

**Which debrid provider are you using?**
Real Debrid

Hi, I've been using RDT-Client with success for the past 2 days. Worked fine even after some reboots. However as of today, the docker images won't work properly. The image does start but the client on localhost:6500 give a black screen. The error on Docker logs is shown here : 
2023-10-27 13:48:08 rdtclient  | [11:48:08 ERR] The connection to RealDebrid has failed: Address not available (api.real-debrid.com:443)
2023-10-27 13:48:08 rdtclient  | System.Net.Http.HttpRequestException: Address not available (api.real-debrid.com:443)
2023-10-27 13:48:08 rdtclient  |  ---> System.Net.Sockets.SocketException (99): Address not available
2023-10-27 13:48:08 rdtclient  |    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
2023-10-27 13:48:08 rdtclient  |    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
2023-10-27 13:48:08 rdtclient  |    at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
2023-10-27 13:48:08 rdtclient  |    at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
2023-10-27 13:48:08 rdtclient  |    --- End of inner exception stack trace ---
2023-10-27 13:48:08 rdtclient  |    at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
2023-10-27 13:48:08 rdtclient  |    at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
2023-10-27 13:48:08 rdtclient  |    at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
2023-10-27 13:48:08 rdtclient  |    at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
2023-10-27 13:48:08 rdtclient  |    at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
2023-10-27 13:48:08 rdtclient  |    at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
2023-10-27 13:48:08 rdtclient  |    at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
2023-10-27 13:48:08 rdtclient  |    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
2023-10-27 13:48:08 rdtclient  |    at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
2023-10-27 13:48:08 rdtclient  |    at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
2023-10-27 13:48:08 rdtclient  |    at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
2023-10-27 13:48:08 rdtclient  |    at RDNET.Requests.Request(String baseUrl, String url, String headerOutput, Boolean requireAuthentication, RequestType requestType, HttpContent data, CancellationToken cancellationToken)
2023-10-27 13:48:08 rdtclient  |    at RDNET.Requests.Request(String baseUrl, String url, String headerOutput, Boolean requireAuthentication, RequestType requestType, HttpContent data, CancellationToken cancellationToken)
2023-10-27 13:48:08 rdtclient  |    at RDNET.Requests.GetRequestAsync(String url, Boolean requireAuthentication, CancellationToken cancellationToken)
2023-10-27 13:48:08 rdtclient  |    at RDNET.ApiApi.GetIsoTimeAsync(CancellationToken cancellationToken)

**Comment by rogerfar** [comment]
Please check your network or maybe RD was just down, first line:

`The connection to RealDebrid has failed: Address not available (api.real-debrid.com:443)`
