### ISSUE TITLE
Seeing the InvalidOperationException in the console

### ISSUE THREAD

**Issue by khooniatma** [rogerfar/rdt-client#350]
**What version are you using?**
v2.0.42

**Wat OS are you running?**
Windows 11 64-bit

**Are you using Docker or as a service?**
Service

**Which debrid provider are you using?**
RealDebrid

**Please attach a log file here with the log setting set to debug**

```
[21:18:07 ERR] An unhandled exception has occurred while executing the request.
System.InvalidOperationException: The request reached the end of the pipeline without executing the endpoint: '/hub/negotiate'. Please register the EndpointMiddleware using 'IApplicationBuilder.UseEndpoints(...)' if using routing.
   at Microsoft.AspNetCore.Builder.ApplicationBuilder.<>c.<Build>b__25_0(HttpContext context)
   at Microsoft.AspNetCore.SpaServices.SpaDefaultPageMiddleware.<>c__DisplayClass0_0.<Attach>b__1(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.SpaServices.SpaDefaultPageMiddleware.<>c__DisplayClass0_0.<Attach>b__0(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at RdtClient.Service.Middleware.RequestLoggingMiddleware.Invoke(HttpContext context) in C:\Projects\rdt-client\server\RdtClient.Service\Middleware\RequestLoggingMiddleware.cs:line 22
   at Program.<>c.<<<Main>$>b__0_14>d.MoveNext() in C:\Projects\rdt-client\server\RdtClient.Web\Program.cs:line 159
--- End of stack trace from previous location ---
   at RdtClient.Service.Middleware.AuthorizeMiddleware.Invoke(HttpContext context) in C:\Projects\rdt-client\server\RdtClient.Service\Middleware\AuthorizeMiddleware.cs:line 22
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<Invoke>g__Awaited|10_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)
```

This does not seem to affect the operation of `rdtclient`. However I am not sure what is causing this..

**Comment by rogerfar** [comment]
Should be good now in .44.
