### ISSUE TITLE
Can't delete torrent while it's uncompressing

### ISSUE THREAD

**Issue by belidzs** [rogerfar/rdt-client#357]
**What version are you using?**
2.0.46

**Wat OS are you running?**
Container on k8s on Linux 

**Are you using Docker or as a service?**
Container

**Which debrid provider are you using?**
RD

**Please attach a log file here with the log setting set to debug**

I've downloaded a pretty big release (10GB) and after both RD and rdt-client had finished downloading, it started uncompressing. At this point I have changed my mind and I wanted to delete the torrent from the list, so I've opened up the torrent and clicked on Delete Torrent. I've selected all three options.

The frontend has shown an error message (forgot to capture) and the following was sent to the log output:
```
[17:03:53 ERR] An unhandled exception has occurred while executing the request.
System.IO.IOException: Resource busy : '/data/downloads/<redacted>/.nfs000000000910000300000045'
   at System.IO.FileSystem.RemoveDirectoryRecursive(String fullPath)
   at RdtClient.Service.Services.Torrents.Delete(Guid torrentId, Boolean deleteData, Boolean deleteRdTorrent, Boolean deleteLocalFiles) in /appserver/server/RdtClient.Service/Services/Torrents.cs:line 301
   at RdtClient.Service.Services.Torrents.Delete(Guid torrentId, Boolean deleteData, Boolean deleteRdTorrent, Boolean deleteLocalFiles)
   at RdtClient.Web.Controllers.TorrentsController.Delete(Guid torrentId, TorrentControllerDeleteRequest request) in /appserver/server/RdtClient.Web/Controllers/TorrentsController.cs:line 178
   at lambda_method819(Closure, Object)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at RdtClient.Service.Middleware.RequestLoggingMiddleware.Invoke(HttpContext context) in /appserver/server/RdtClient.Service/Middleware/RequestLoggingMiddleware.cs:line 22
   at Program.<>c.<<<Main>$>b__0_14>d.MoveNext() in /appserver/server/RdtClient.Web/Program.cs:line 159
--- End of stack trace from previous location ---
   at RdtClient.Service.Middleware.AuthorizeMiddleware.Invoke(HttpContext context) in /appserver/server/RdtClient.Service/Middleware/AuthorizeMiddleware.cs:line 22
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<Invoke>g__Awaited|10_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)
```

Then when I have opened up the torrent from the list again, the progress counter still kept on going and reported "Uncompressing" status.

**Comment by rogerfar** [comment]
I changed the unpack process a bit so it should support cancellation now while doing the uncompressing. Downside is that the progress seems pretty out of whack.

**Comment by belidzs** [comment]
Thank you for the quick fix
