### ISSUE TITLE
Files seemingly being deleted from disk upon completion all of the sudden.

### ISSUE THREAD

**Issue by doobersn** [rogerfar/rdt-client#396]
**What version are you using?**
Most recent version
**Wat OS are you running?**
Unraid
**Are you using Docker or as a service?**
Yes
**Which debrid provider are you using?**
Real Debrid
**Which downloader are you using?**
Internal
**Please attach a log file here with the log setting set to debug**
` at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at RdtClient.Service.Middleware.RequestLoggingMiddleware.Invoke(HttpContext context) in /appserver/server/RdtClient.Service/Middleware/RequestLoggingMiddleware.cs:line 22
   at Program.<>c.<<<Main>$>b__0_14>d.MoveNext() in /appserver/server/RdtClient.Web/Program.cs:line 159
--- End of stack trace from previous location ---
   at RdtClient.Service.Middleware.AuthorizeMiddleware.Invoke(HttpContext context) in /appserver/server/RdtClient.Service/Middleware/AuthorizeMiddleware.cs:line 22
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<Invoke>g__Awaited|10_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)
[12:25:58 WRN] 101: /hub
[12:26:07 WRN] 304: /index.html
[12:27:18 WRN] 101: /hub
[12:35:13 WRN] 304: /index.html
[12:35:20 WRN] 101: /hub
[13:33:29 WRN] 304: /index.html
[13:33:33 WRN] 101: /hub
[13:46:23 WRN] 304: /index.html
[13:46:28 WRN] 101: /hub
[17:39:39 WRN] 304: /assets/logo.png
[17:39:39 WRN] 304: /polyfills.bc0070be939c8a90.js
[17:39:39 WRN] 304: /main.8af36f2b27bda364.js
[17:39:39 WRN] 304: /styles.e0d9d5dcd8df4190.css
[17:40:11 WRN] 101: /hub
[20:06:16 WRN] 101: /hub
[20:07:58 WRN] 101: /hub
[01:19:39 WRN] 101: /hub
[07:44:08 WRN] 304: /index.html
[07:44:08 WRN] 304: /runtime.52f1d05aa6c3afea.js
[07:44:08 WRN] 304: /polyfills.bc0070be939c8a90.js
[07:44:08 WRN] 304: /main.8af36f2b27bda364.js
[07:44:08 WRN] 304: /styles.e0d9d5dcd8df4190.css
[07:44:08 WRN] 304: /assets/logo.png
[07:45:05 WRN] 101: /hub
[07:47:49 WRN] 304: /index.html
[07:48:11 WRN] 101: /hub
[08:23:08 WRN] 304: /index.html
[08:25:26 WRN] 101: /hub
[08:29:52 ERR] Unexpected error occurred in ProviderUpdater: The request was canceled due to the configured HttpClient.Timeout of 10 seconds elapsing.
System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 10 seconds elapsing.
 ---> System.TimeoutException: A task was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.<SendCoreAsync>g__Core|5_0(HttpRequestMessage request, Boolean useAsync, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.<SendCoreAsync>g__Core|5_0(HttpRequestMessage request, Boolean useAsync, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at RDNET.Requests.Request(String baseUrl, String url, String headerOutput, Boolean requireAuthentication, RequestType requestType, HttpContent data, CancellationToken cancellationToken)
   at RDNET.Requests.Request(String baseUrl, String url, String headerOutput, Boolean requireAuthentication, RequestType requestType, HttpContent data, CancellationToken cancellationToken)
   at RDNET.Requests.Request[T](String baseUrl, String url, Boolean requireAuthentication, RequestType requestType, HttpContent data, CancellationToken cancellationToken)
   at RDNET.Requests.GetRequestAsync[T](String url, Boolean requireAuthentication, CancellationToken cancellationToken)
   at RDNET.TorrentsApi.GetAsync(Nullable`1 offset, Nullable`1 limit, String filter, CancellationToken cancellationToken)
   at RdtClient.Service.Services.TorrentClients.RealDebridTorrentClient.GetTorrents() in /appserver/server/RdtClient.Service/Services/TorrentClients/RealDebridTorrentClient.cs:line 107
   at RdtClient.Service.Services.Torrents.UpdateRdData() in /appserver/server/RdtClient.Service/Services/Torrents.cs:line 412
   at RdtClient.Service.BackgroundServices.ProviderUpdater.ExecuteAsync(CancellationToken stoppingToken) in /appserver/server/RdtClient.Service/BackgroundServices/ProviderUpdater.cs:line 62
[11:31:14 WRN] 304: /index.html
[11:31:28 WRN] 101: /hub
[11:56:17 WRN] 304: /index.html
[11:56:32 WRN] 101: /hub
[12:18:56 WRN] 304: /index.html
[12:18:56 WRN] 304: /styles.e0d9d5dcd8df4190.css
[12:18:56 WRN] 304: /polyfills.bc0070be939c8a90.js
[12:18:56 WRN] 304: /assets/logo.png
[12:18:57 WRN] 304: /fa-solid-900.fd0b155cd663a8fa.woff2
[12:18:57 WRN] 304: /fa-regular-400.3580b4a95c9bb1d5.woff2
[12:20:08 WRN] 101: /hub
[12:31:50 WRN] 304: /index.html
[12:32:02 WRN] 101: /hub
[12:33:53 WRN] 304: /index.html
[12:34:13 WRN] 101: /hub
[12:38:45 WRN] 304: /index.html
[12:40:03 WRN] 101: /hub
[12:44:35 WRN] 304: /index.html
[12:58:12 WRN] 101: /hub
[12:58:12 WRN] 101: /hub
[13:03:22 WRN] 101: /hub
[13:17:46 WRN] 304: /index.html
[13:17:52 WRN] 101: /hub
[13:23:37 WRN] 101: /hub`

So I'm not sure whats happening. It was working fine, integrated with sonarr and radarr and importing things correctly. I downloaded a mkv and noticed radarr didnt import it and there was no file within the movie folder. Thought maybe it was a fluke so I tried again and this time I disabled 'remove from client' (or provider, I cant remember). I immediately tried manually importing and the wrong file size showed. Canceled the manual import and checked it again a couple times and each time the file size grew a bit. But then it was magically deleted the same as the first one. Then I tried downloading again but this time setting it to 'no action' after the download was finished. The same exact thing happened. It did show a .rar in the folder when I was able to get a chance to look at it before it was deleted but weirdly there was actually not supposed to be a .rar in there at all. Adding the magnet link manually and doing it that way resulted in nothing being automatically deleted and I was able to successful manually import. I'm not sure whats going wrong as it was working fine before this and in fact worked fine for other mkvs earlier today.

**Comment by rogerfar** [comment]
I noticed the same behaviour, can you check if it's working now in the latest version? 

What I noticed was that I ended up with files outside my category folder, which I still cannot trace back.

**Comment by rogerfar** [comment]
Is this still a problem? If so, can you send a torrent that causes this behaviour.

**Comment by rogerfar** [comment]
I haven't seen this behaviour anymore, let me know if it's still an issue.

**Comment by rogerfar** [comment]
Please open a new report and follow the bug reporting steps.
