### ISSUE TITLE
After rdtclient via radarr requests a torrent, then opening real-debrid GUI prompts for files to download 

### ISSUE THREAD

**Issue by vamichael** [rogerfar/rdt-client#433]
**What version are you using?**

**Wat OS are you running?** Ubuntu 

**Are you using Docker or as a service?** yes

**Which debrid provider are you using?** real-debrid 

**Which downloader are you using?** symlink

**Please attach a log file here with the log setting set to debug**

I’m using sonarr/radarr to submit torrents via rdtclient.  Let’s say I add a movie (Caddyshack) with radarr.  Radarr finds a torrent and uses rdtclient to request from real-debrid.  Radarr looks like it’s downloading (movie goes purple) but no symllink is created.  When I visit the torrent page in RD, I got the following pop up.
![IMG_0009](https://github.com/rogerfar/rdt-client/assets/6163539/daaafcec-52e0-46b1-8622-baed398e3ab8)

Only after I manually press “start my torrent” will the symlink be created. 

Is there a guide for using *arr with rdtclient/real-debrid and rclone?  I just want the *arr to find content from indexers, then to submit that to realdebrid such that it will add the torrent content to my rclone directory.

**Comment by rogerfar** [comment]
Please post a debug log.

**Comment by vamichael** [comment]
not much to show

`2024-03-12 19:08:25.830 -04:00 [WRN] : 101: /hub
2024-03-12 19:10:07.180 -04:00 [WRN] : 101: /hub
2024-03-12 19:15:18.040 -04:00 [WRN] : 101: /hub
2024-03-12 19:17:09.554 -04:00 [WRN] : 101: /hub
2024-03-12 19:18:55.154 -04:00 [WRN] : 101: /hub
2024-03-12 19:20:22.487 -04:00 [WRN] : 101: /hub
2024-03-12 19:22:36.813 -04:00 [WRN] : 101: /hub
2024-03-12 19:24:38.157 -04:00 [WRN] : 101: /hub
2024-03-12 19:29:01.929 -04:00 [WRN] : 101: /hub
2024-03-12 19:30:05.821 -04:00 [WRN] : 101: /hub
2024-03-12 19:31:07.608 -04:00 [WRN] : 101: /hub
2024-03-12 19:36:10.584 -04:00 [WRN] : 101: /hub
2024-03-12 19:46:41.985 -04:00 [WRN] : 101: /hub
`

**Comment by rogerfar** [comment]
Can you try the latest release and see if it fixes it?

**Comment by FutureTense** [comment]
Nope, it’s stilt doing it.

1. add a series in sonarr
2. Notice 2 episodes missing.  In sonarr, do an automatic search for those 2 episodes 
3. rdtclient gets passed 2 torrents 
4. Open real-debrid GUI and click “torrents”
5. Get a pop up to confirm which files to “download”
6. Click Confrim. And this is the problem, I shouldn’t have to select confirm, right?

**Comment by rogerfar** [comment]
I found the issue I think, should be good now in 2.0.76. It was because the torrent runner crashed.

**Comment by FutureTense** [comment]
Still happening, I’ll check again tomorrow

**Comment by rogerfar** [comment]
Can you post full logs from the start of RDT-client to see what is happening. In debug mode.

**Comment by vamichael** [comment]
Can you link me instructions on how to put into debug mode?  Sorry, have
never done this before.

**Comment by rogerfar** [comment]
Log level is in settings:
![image](https://github.com/rogerfar/rdt-client/assets/1142915/65b0da90-5c2a-4f4d-9002-8ca11203d74a)

It does take a minute for it to select files after you added a new torrent as there is an artificial delay in there to make sure real-debrid caches everything properly.

**Comment by FutureTense** [comment]
Ok, I’ll have to wait for it to happen again.  Are you on discord?

**Comment by FutureTense** [comment]
Found something interesting.  I was looking at real-debrid and a torrent that rdtclient added to RD was shown as an “invalid magnet”.  I deleted those and the problem went away.  Is there a way for rdt to check for these?

**Comment by mrnajiboy** [comment]
I'm experiencing a very similar issue with a similar solve, in both Sonarr and Radarr.

**What version are you using?** latest

**Wat OS are you running?** Mac OS 14.4.1, running Docker Desktop desktop-linux v0.13.1:arm64

**Are you using Docker as a service?** no

**Which debrid provider are you using?** real-debrid

**Which downloader are you using?** symlink downloader.

I’m running on all containers, with a zurg (rclone branch) remote volume via the rclone docker volume plugin, and using overseerr + prowlarr > sonarr/radarr to submit torrents via rdtclient, and scanning with autoscan.  

Sonarr/Radarr finds a torrent, uses rdtclient to request from real-debrid, but I'm met with the first message in the log below. Sonarr looks like it’s downloading (movie goes purple) but no symllink is created. Then I visit the torrent page in RD, and click on the "unrestrict link" button, Sonarr/Radarr then recognizes the torrent 1-2 minutes later and creates a symlink. 

I pressed the button 3 times in this log example, and was met with a "fair usage limit" log error on every press, though I normally only need to press once. Even with the error, the symlink was still successfully created. Here's an example with Sonarr:

LOG:

```
rdtclient    | [05:07:37 ERR] Unable to start download: An unexpected error occurred preparing download https://lax2.download.real-debrid.com/d/FOHPFWXLLAZUK58/Invincible.2021.S00E01.Presenting.Atom.Eve.Special.Episode.REPACK.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.mkv for torrent Invincible.2021.S00E01.Presenting.Atom.Eve.Special.Episode.REPACK.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb[TGx]: Could not find file from rclone mount! for download Invincible.2021.S00E01.Presenting.Atom.Eve.Special.Episode.REPACK.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.mkv. Completed: 0%, avg speed: 0bytes/s (5ed6967f-efea-4788-b8f4-3aac35cb2849) remoteID:  for torrent Invincible.2021.S00E01.Presenting.Atom.Eve.Special.Episode.REPACK.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb[TGx] (UBCQ2INT7OX4A - downloaded 100%) (348d7bfb-7ae2-4e45-bb23-fc7a87013f33)
rdtclient    | [05:07:38 ERR] Download reported an error: Could not find file from rclone mount! for download Invincible.2021.S00E01.Presenting.Atom.Eve.Special.Episode.REPACK.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.mkv. Completed: 0%, avg speed: 0bytes/s (5ed6967f-efea-4788-b8f4-3aac35cb2849) remoteID:  for torrent Invincible.2021.S00E01.Presenting.Atom.Eve.Special.Episode.REPACK.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb[TGx] (UBCQ2INT7OX4A - downloaded 100%) (348d7bfb-7ae2-4e45-bb23-fc7a87013f33)
zurg         | 2024-05-10T20:07:45.127ZINFOmanagerDetected changes! Refreshing 29 torrents
zurg         | 2024-05-10T20:07:45.798ZDEBUGrealdebridGot info for torrent M43G4C7WIWIGU (progress=100%)
zurg         | 2024-05-10T20:07:45.800ZDEBUGmanagerSaved torrent M43G4C7WIWIGU to file
zurg         | 2024-05-10T20:07:45.800ZINFOmanagerFetched info for 29 torrents
zurg         | 2024-05-10T20:07:45.800ZINFOmanagerCompiled into 29 torrents, 0 were missing info
zurg         | 2024-05-10T20:07:45.800ZINFOmanagerFinished refreshing torrents
zurg         | 2024-05-10T20:07:45.801ZDEBUGmanagerProcessing fixers (0 left: [])
zurg         | 2024-05-10T20:07:45.801ZDEBUGmanagerFinished processing fixers
zurg         | 2024-05-10T20:07:45.802ZDEBUGmanagerOutput of hook on_library_update:
zurg         | detected update on: torrents/Invincible.2021.S00E01.Presenting.Atom.Eve.Special.Episode.REPACK.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.mkv
zurg         | detected update on: __all__/Invincible.2021.S00E01.Presenting.Atom.Eve.Special.Episode.REPACK.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.mkv
zurg         | 
zurg         | 2024-05-10T20:07:45.802ZDEBUGmanagerTriggered hook on_library_update for 2 path(s)
sonarr4k     | [Info] ImportListSyncService: Starting Import List Sync 
sonarr4k     | [Info] ImportListSyncService: Processing 2 list items 
sonarr4k     | [Info] ImportListSyncService: Import List Sync Completed. Items found: 2, Series added: 0 
rdtclient    | [05:07:50 ERR] Cannot unrestrict link: {ex.Message}
rdtclient    | RDNET.RealDebridException: fair_usage_limit
rdtclient    |    at RDNET.Requests.Request(String baseUrl, String url, String headerOutput, Boolean requireAuthentication, RequestType requestType, HttpContent data, CancellationToken cancellationToken)
rdtclient    |    at RDNET.Requests.Request[T](String baseUrl, String url, Boolean requireAuthentication, RequestType requestType, HttpContent data, CancellationToken cancellationToken)
rdtclient    |    at RDNET.Requests.PostRequestAsync[T](String url, IEnumerable`1 data, Boolean requireAuthentication, CancellationToken cancellationToken)
rdtclient    |    at RDNET.UnrestrictApi.LinkAsync(String link, String password, Boolean remote, CancellationToken cancellationToken)
rdtclient    |    at RdtClient.Service.Services.TorrentClients.RealDebridTorrentClient.Unrestrict(String link) in /appserver/server/RdtClient.Service/Services/TorrentClients/RealDebridTorrentClient.cs:line 271
rdtclient    |    at RdtClient.Service.Services.Torrents.UnrestrictLink(Guid downloadId) in /appserver/server/RdtClient.Service/Services/Torrents.cs:line 364
rdtclient    |    at RdtClient.Service.Services.TorrentRunner.Tick() in /appserver/server/RdtClient.Service/Services/TorrentRunner.cs:line 350
zurg         | 2024-05-10T20:07:55.143ZINFOmanagerDetected changes! Refreshing 28 torrents
zurg         | 2024-05-10T20:07:55.545ZINFOmanagerFetched info for 28 torrents
zurg         | 2024-05-10T20:07:55.545ZINFOmanagerCompiled into 29 torrents, 0 were missing info
zurg         | 2024-05-10T20:07:55.546ZINFOmanagerRemoving torrent Invincible.2021.S00E01.Presenting.Atom.Eve.Special.Episode.REPACK.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.mkv from zurg database (not real-debrid)
zurg         | 2024-05-10T20:07:55.546ZINFOmanagerFinished refreshing torrents
zurg         | 2024-05-10T20:07:55.547ZDEBUGmanagerProcessing fixers (0 left: [])
zurg         | 2024-05-10T20:07:55.548ZDEBUGmanagerFinished processing fixers
zurg         | 2024-05-10T20:07:55.548ZDEBUGmanagerTriggered hook on_library_update for 0 path(s)
overseerr    | 2024-05-10T20:08:00.011Z [debug][Jobs]: Starting scheduled job: Download Sync 
overseerr    | 2024-05-10T20:08:00.019Z [debug][Download Tracker]: Found 1 item(s) in progress on Sonarr server: Sonarr 
rdtclient    | [05:08:01 ERR] Cannot unrestrict link: {ex.Message}
rdtclient    | RDNET.RealDebridException: fair_usage_limit
rdtclient    |    at RDNET.Requests.Request(String baseUrl, String url, String headerOutput, Boolean requireAuthentication, RequestType requestType, HttpContent data, CancellationToken cancellationToken)
rdtclient    |    at RDNET.Requests.Request[T](String baseUrl, String url, Boolean requireAuthentication, RequestType requestType, HttpContent data, CancellationToken cancellationToken)
rdtclient    |    at RDNET.Requests.PostRequestAsync[T](String url, IEnumerable`1 data, Boolean requireAuthentication, CancellationToken cancellationToken)
rdtclient    |    at RDNET.UnrestrictApi.LinkAsync(String link, String password, Boolean remote, CancellationToken cancellationToken)
rdtclient    |    at RdtClient.Service.Services.TorrentClients.RealDebridTorrentClient.Unrestrict(String link) in /appserver/server/RdtClient.Service/Services/TorrentClients/RealDebridTorrentClient.cs:line 271
rdtclient    |    at RdtClient.Service.Services.Torrents.UnrestrictLink(Guid downloadId) in /appserver/server/RdtClient.Service/Services/Torrents.cs:line 364
rdtclient    |    at RdtClient.Service.Services.TorrentRunner.Tick() in /appserver/server/RdtClient.Service/Services/TorrentRunner.cs:line 350
zurg         | 2024-05-10T20:08:05.135ZINFOmanagerDetected changes! Refreshing 28 torrents
zurg         | 2024-05-10T20:08:05.476ZINFOmanagerFetched info for 28 torrents
zurg         | 2024-05-10T20:08:05.476ZINFOmanagerCompiled into 28 torrents, 0 were missing info
zurg         | 2024-05-10T20:08:05.476ZINFOmanagerFinished refreshing torrents
zurg         | 2024-05-10T20:08:05.477ZDEBUGmanagerProcessing fixers (0 left: [])
zurg         | 2024-05-10T20:08:05.478ZDEBUGmanagerFinished processing fixers
zurg         | 2024-05-10T20:08:05.479ZDEBUGmanagerTriggered hook on_library_update for 0 path(s)
rdtclient    | [05:08:12 ERR] Cannot unrestrict link: {ex.Message}
rdtclient    | RDNET.RealDebridException: fair_usage_limit
rdtclient    |    at RDNET.Requests.Request(String baseUrl, String url, String headerOutput, Boolean requireAuthentication, RequestType requestType, HttpContent data, CancellationToken cancellationToken)
rdtclient    |    at RDNET.Requests.Request[T](String baseUrl, String url, Boolean requireAuthentication, RequestType requestType, HttpContent data, CancellationToken cancellationToken)
rdtclient    |    at RDNET.Requests.PostRequestAsync[T](String url, IEnumerable`1 data, Boolean requireAuthentication, CancellationToken cancellationToken)
rdtclient    |    at RDNET.UnrestrictApi.LinkAsync(String link, String password, Boolean remote, CancellationToken cancellationToken)
rdtclient    |    at RdtClient.Service.Services.TorrentClients.RealDebridTorrentClient.Unrestrict(String link) in /appserver/server/RdtClient.Service/Services/TorrentClients/RealDebridTorrentClient.cs:line 271
rdtclient    |    at RdtClient.Service.Services.Torrents.UnrestrictLink(Guid downloadId) in /appserver/server/RdtClient.Service/Services/Torrents.cs:line 364
rdtclient    |    at RdtClient.Service.Services.TorrentRunner.Tick() in /appserver/server/RdtClient.Service/Services/TorrentRunner.cs:line 350
zurg         | 2024-05-10T20:08:15.198ZINFOmanagerDetected changes! Refreshing 29 torrents
zurg         | 2024-05-10T20:08:15.550ZINFOmanagerFetched info for 28 torrents
zurg         | 2024-05-10T20:08:15.550ZINFOmanagerCompiled into 28 torrents, 0 were missing info
zurg         | 2024-05-10T20:08:15.550ZINFOmanagerFinished refreshing torrents
zurg         | 2024-05-10T20:08:15.550ZDEBUGmanagerProcessing fixers (0 left: [])
zurg         | 2024-05-10T20:08:15.551ZDEBUGmanagerFinished processing fixers
zurg         | 2024-05-10T20:08:15.552ZDEBUGmanagerTriggered hook on_library_update for 0 path(s)
zurg         | 2024-05-10T20:08:25.152ZINFOmanagerDetected changes! Refreshing 29 torrents
zurg         | 2024-05-10T20:08:25.842ZDEBUGrealdebridGot info for torrent UQLIQKLIQRBMU (progress=100%)
zurg         | 2024-05-10T20:08:25.845ZDEBUGmanagerSaved torrent UQLIQKLIQRBMU to file
zurg         | 2024-05-10T20:08:25.845ZINFOmanagerFetched info for 29 torrents
zurg         | 2024-05-10T20:08:25.845ZINFOmanagerCompiled into 29 torrents, 0 were missing info
zurg         | 2024-05-10T20:08:25.845ZINFOmanagerFinished refreshing torrents
zurg         | 2024-05-10T20:08:25.846ZDEBUGmanagerProcessing fixers (0 left: [])
zurg         | 2024-05-10T20:08:25.846ZDEBUGmanagerFinished processing fixers
zurg         | 2024-05-10T20:08:25.847ZDEBUGmanagerOutput of hook on_library_update:
zurg         | detected update on: torrents/Invincible.2021.S00E01.Presenting.Atom.Eve.Special.Episode.REPACK.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.mkv
zurg         | detected update on: __all__/Invincible.2021.S00E01.Presenting.Atom.Eve.Special.Episode.REPACK.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.mkv
zurg         | 
zurg         | 2024-05-10T20:08:25.847ZDEBUGmanagerTriggered hook on_library_update for 2 path(s)
rdtclient    | [05:08:33 INF] Created symbolic link from /realdebrid/torrents/Invincible.2021.S00E01.Presenting.Atom.Eve.Special.Episode.REPACK.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.mkv/Invincible.2021.S00E01.Presenting.Atom.Eve.Special.Episode.REPACK.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.mkv to /mnt/symlinks/sonarr/Invincible.2021.S00E01.Presenting.Atom.Eve.Special.Episode.REPACK.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb[TGx]/Invincible.2021.S00E01.Presenting.Atom.Eve.Special.Episode.REPACK.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.mkv
```

**Comment by rogerfar** [comment]
I was afraid of this yes. It's possible it's unrestricting too quickly causing a `fair_usage_limit` error.

I could add a retry mechanism in RDT, but it's hard to know what the limits are.

**Comment by Stooovie** [comment]
This isn't working as of 2.0.115.0. I need to manually unrestrict all torrents for rdtclient to pick up the files, which completely defeats the purpose.
