### ISSUE TITLE
Unable to add any torrents

### ISSUE THREAD

**Issue by thomazio** [rogerfar/rdt-client#45]
OS: Linux
Docker: yes

When adding torrents with Sonarr I'm facing the following error:
```
[v3.0.5.1144] NzbDrone.Core.Download.Clients.DownloadClientException: Failed to connect to qBittorrent, check your settings. ---> NzbDrone.Common.Http.HttpException: HTTP request failed: [500:InternalServerError] [POST] at [http://localhost:6500/api/v2/torrents/add]
```

Checking that API URL the errors reads:
```
Object reference not set to an instance of an object.
```

I've tried the following:
- deleting rdtclient.db
- spin up a new instance of rdtclient
- downgrade sonarr

I cannot downgrade rdtclient easily as there is only the tag latest on Dockerhub.

**Comment by rogerfar** [comment]
Can you try enabling verbose logging (through the interface) and see if it shows where the `Object reference not set to an instance of an object.` comes from?

**Comment by thomazio** [comment]
Thanks for the quick reply. It fixed itself shortly after I opened this issue. Probably a networking error unrelated to rdtclient here's the relevant log extract in any case.


```
System.Net.Http.HttpRequestException: Name or service not known (api.real-debrid.com:443)
 ---> System.Net.Sockets.SocketException (0xFFFDFFFF): Name or service not known
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|283_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.DefaultConnectAsync(SocketsHttpConnectionContext context, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at RDNET.RdNetClient.Get[T](String url, Boolean repeatRequest)
   at RDNET.RdNetClient.GetUserAsync()
   at RdtClient.Service.Services.Torrents.GetProfile() in /appserver/RdtClient.Service/Services/Torrents.cs:line 291
   at RdtClient.Web.Controllers.SettingsController.Profile() in /appserver/RdtClient.Web/Controllers/SettingsController.cs:line 59
   at lambda_method55(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
```

**Comment by rogerfar** [comment]
That's an odd one yes, probably real debrid down for a bit? Good that it's solved now.
