### ISSUE TITLE
Sonarr does not work while radarr does

### ISSUE THREAD

**Issue by Emald000** [rogerfar/rdt-client#486]
``since a few days, sonarr can not connect to rdt client (even after the 2.0.76 update), while radarr connects with no issue, and both have exactly the same configuration
**What version are you using?**
2.0.77
**Wat OS are you running?**
Linux NAS
**Are you using Docker or as a service?**
Docker
**Which debrid provider are you using?**
reak debrid
**Which downloader are you using?**
internal
**Please attach a log file here with the log setting set to debug**
[v4.0.4.1491] NzbDrone.Core.Download.Clients.DownloadClientException: Failed to connect to qBittorrent, check your settings.
 ---> System.Net.WebException: Http request timed out
 ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled.
 ---> System.Net.Sockets.SocketException (125): Operation canceled
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.InitialFillAsync(Boolean async)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponseAsync(HttpRequest request, CookieContainer cookies) in ./Sonarr.Common/Http/Dispatchers/ManagedHttpDispatcher.cs:line 144
   at NzbDrone.Common.Http.HttpClient.ExecuteRequestAsync(HttpRequest request, CookieContainer cookieContainer) in ./Sonarr.Common/Http/HttpClient.cs:line 157
   at NzbDrone.Common.Http.HttpClient.ExecuteAsync(HttpRequest request) in ./Sonarr.Common/Http/HttpClient.cs:line 70
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in ./Sonarr.Common/Http/HttpClient.cs:line 128
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxyV2.IsApiSupported(QBittorrentSettings settings) in ./Sonarr.Core/Download/Clients/QBittorrent/QBittorrentProxyV2.cs:line 68
   --- End of inner exception stack trace ---
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxyV2.IsApiSupported(QBittorrentSettings settings) in ./Sonarr.Core/Download/Clients/QBittorrent/QBittorrentProxyV2.cs:line 68
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxySelector.FetchProxy(QBittorrentSettings settings) in ./Sonarr.Core/Download/Clients/QBittorrent/QBittorrentProxySelector.cs:line 96
   at NzbDrone.Common.Cache.Cached`1.Get(String key, Func`1 function, Nullable`1 lifeTime) in ./Sonarr.Common/Cache/Cached.cs:line 99
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxySelector.GetProxyCache(QBittorrentSettings settings, Boolean force) in ./Sonarr.Core/Download/Clients/QBittorrent/QBittorrentProxySelector.cs:line 72
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxySelector.GetProxy(QBittorrentSettings settings, Boolean force) in ./Sonarr.Core/Download/Clients/QBittorrent/QBittorrentProxySelector.cs:line 62
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrent.GetItems() in ./Sonarr.Core/Download/Clients/QBittorrent/QBittorrent.cs:line 220
   at NzbDrone.Core.Download.TrackedDownloads.DownloadMonitoringService.ProcessClientDownloads(IDownloadClient downloadClient) in ./Sonarr.Core/Download/TrackedDownloads/DownloadMonitoringService.cs:line 90

2024-05-04 23:22:22.7|Error|QBittorrent|Failed to get torrents

[v4.0.4.1491] NzbDrone.Core.Download.Clients.DownloadClientException: Failed to connect to qBittorrent, check your settings.
 ---> System.Net.WebException: Http request timed out
 ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled.
 ---> System.Net.Sockets.SocketException (125): Operation canceled
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.InitialFillAsync(Boolean async)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponseAsync(HttpRequest request, CookieContainer cookies) in ./Sonarr.Common/Http/Dispatchers/ManagedHttpDispatcher.cs:line 144
   at NzbDrone.Common.Http.HttpClient.ExecuteRequestAsync(HttpRequest request, CookieContainer cookieContainer) in ./Sonarr.Common/Http/HttpClient.cs:line 157
   at NzbDrone.Common.Http.HttpClient.ExecuteAsync(HttpRequest request) in ./Sonarr.Common/Http/HttpClient.cs:line 70
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in ./Sonarr.Common/Http/HttpClient.cs:line 128
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxyV2.IsApiSupported(QBittorrentSettings settings) in ./Sonarr.Core/Download/Clients/QBittorrent/QBittorrentProxyV2.cs:line 68
   --- End of inner exception stack trace ---
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxyV2.IsApiSupported(QBittorrentSettings settings) in ./Sonarr.Core/Download/Clients/QBittorrent/QBittorrentProxyV2.cs:line 68
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxySelector.FetchProxy(QBittorrentSettings settings) in ./Sonarr.Core/Download/Clients/QBittorrent/QBittorrentProxySelector.cs:line 96
   at NzbDrone.Common.Cache.Cached`1.Get(String key, Func`1 function, Nullable`1 lifeTime) in ./Sonarr.Common/Cache/Cached.cs:line 99
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxySelector.GetProxyCache(QBittorrentSettings settings, Boolean force) in ./Sonarr.Core/Download/Clients/QBittorrent/QBittorrentProxySelector.cs:line 72
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxySelector.GetProxy(QBittorrentSettings settings, Boolean force) in ./Sonarr.Core/Download/Clients/QBittorrent/QBittorrentProxySelector.cs:line 62
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrent.TestGetTorrents() in ./Sonarr.Core/Download/Clients/QBittorrent/QBittorrent.cs:line 589

2024-05-04 23:22:24.5|Warn|SonarrErrorPipeline|Invalid request Validation failed: 
 -- : Failed to get the list of torrents: Failed to connect to qBittorrent, check your settings.
2024-05-04 23:22:30.6|Error|QBittorrent|Unable to test qBittorrent

[v4.0.4.1491] NzbDrone.Core.Download.Clients.DownloadClientException: Failed to connect to qBittorrent, please check your settings.
 ---> System.Net.WebException: Http request timed out
 ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled.
 ---> System.Net.Sockets.SocketException (125): Operation canceled
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.InitialFillAsync(Boolean async)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponseAsync(HttpRequest request, CookieContainer cookies) in ./Sonarr.Common/Http/Dispatchers/ManagedHttpDispatcher.cs:line 144
   at NzbDrone.Common.Http.HttpClient.ExecuteRequestAsync(HttpRequest request, CookieContainer cookieContainer) in ./Sonarr.Common/Http/HttpClient.cs:line 157
   at NzbDrone.Common.Http.HttpClient.ExecuteAsync(HttpRequest request) in ./Sonarr.Common/Http/HttpClient.cs:line 70
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in ./Sonarr.Common/Http/HttpClient.cs:line 128
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxyV2.ProcessRequest(HttpRequestBuilder requestBuilder, QBittorrentSettings settings) in ./Sonarr.Core/Download/Clients/QBittorrent/QBittorrentProxyV2.cs:line 399
   --- End of inner exception stack trace ---
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxyV2.ProcessRequest(HttpRequestBuilder requestBuilder, QBittorrentSettings settings) in ./Sonarr.Core/Download/Clients/QBittorrent/QBittorrentProxyV2.cs:line 399
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxyV2.GetApiVersion(QBittorrentSettings settings) in ./Sonarr.Core/Download/Clients/QBittorrent/QBittorrentProxyV2.cs:line 77
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrent.TestConnection() in ./Sonarr.Core/Download/Clients/QBittorrent/QBittorrent.cs:line 422

**Comment by rogerfar** [comment]
Do you see anything come in on the RDT side? If you put it in debug logs, then it should also show incoming requests.

**Comment by Emald000** [comment]
there is no reaction from rdt
the logs when i try testing from radarr



[20:55:22 WRN] 101: /hub
[20:55:22 WRN] 403: /Api/Authentication/IsLoggedIn
[20:55:30 DBG] Method: GET, Path: /Api/Torrents
[20:55:39 DBG] Method: GET, Path: /api/v2/app/webapiVersion
[20:55:49 DBG] Method: GET, Path: /api/v2/app/webapiVersion
[20:55:51 DBG] Method: GET, Path: /api/v2/app/webapiVersion
[20:55:54 DBG] Method: GET, Path: /api/v2/app/preferences
[20:56:03 DBG] Method: GET, Path: /api/v2/app/webapiVersion
[20:56:04 DBG] Method: GET, Path: /api/v2/app/webapiVersion
[20:56:06 DBG] Method: GET, Path: /api/v2/app/webapiVersion
[20:56:07 DBG] Method: GET, Path: /api/v2/torrents/categories
[20:56:07 WRN] 401: /api/v2/torrents/categories
[20:56:26 DBG] Method: POST, Path: /api/v2/auth/login, Form: username: xxxxxxxx password: xxxxxxxxxx
[20:56:26 DBG] Auth login
[20:56:26 DBG] Auth login
[20:56:30 DBG] Method: GET, Path: /api/v2/torrents/categories
[20:56:41 DBG] Method: GET, Path: /api/v2/app/webapiVersion
[20:56:41 DBG] Method: GET, Path: /api/v2/app/preferences
[20:56:41 DBG] Method: GET, Path: /api/v2/torrents/info, QueryString: ?category=radarr
[20:57:03 DBG] Method: GET, Path: /api/v2/torrents/info, QueryString: ?category=tv-sonarr
[20:57:10 DBG] Method: GET, Path: /api/v2/app/webapiVersion
[20:57:11 DBG] Method: GET, Path: /api/v2/app/preferences
[20:57:27 DBG] Method: GET, Path: /api/v2/torrents/info, QueryString: ?category=tv-sonarr
[20:58:11 DBG] Method: GET, Path: /api/v2/app/webapiVersion
[20:58:11 DBG] Method: GET, Path: /api/v2/app/preferences
[20:58:11 DBG] Method: GET, Path: /api/v2/torrents/info, QueryString: ?category=radarr
[20:58:17 DBG] Method: GET, Path: /api/v2/app/webapiVersion
[20:58:18 DBG] Method: GET, Path: /api/v2/app/preferences
[20:58:20 DBG] Method: GET, Path: /api/v2/torrents/info, QueryString: ?category=tv-sonarr
[20:58:28 DBG] Method: GET, Path: /api/v2/app/webapiVersion
[20:58:40 DBG] Method: GET, Path: /api/v2/app/webapiVersion
[20:58:54 DBG] Method: GET, Path: /api/v2/app/preferences
[20:58:57 DBG] Method: GET, Path: /api/v2/app/webapiVersion
[20:59:13 DBG] Method: GET, Path: /api/v2/app/webapiVersion
[20:59:17 DBG] Method: GET, Path: /api/v2/torrents/info, QueryString: ?category=tv-sonarr
[20:59:24 DBG] Method: GET, Path: /api/v2/app/webapiVersion
[20:59:41 DBG] Method: GET, Path: /api/v2/app/webapiVersion
[20:59:41 DBG] Method: GET, Path: /api/v2/app/preferences
[20:59:41 DBG] Method: GET, Path: /api/v2/torrents/info, QueryString: ?category=radarr
[21:00:05 DBG] Method: GET, Path: /api/v2/app/preferences
[21:00:07 DBG] Method: GET, Path: /api/v2/torrents/info, QueryString: ?category=tv-sonarr

**Comment by rogerfar** [comment]
Is it consistent? Or is it when for example you have a lot of torrents downloading?

**Comment by Emald000** [comment]
very consistant, no torrent downloading and server at rest (radarr works perfectly

**Comment by rogerfar** [comment]
If it gives `Http request timed out` it seems to be something like a connection error between the 2. 

If Radarr works but Sonarr not, I suspect some sort of connectivity issue?

**Comment by Emald000** [comment]
but both run on the same machine, on containers, and i just checked, same settings for both (uid gid TZ network etc)
and rdt client is on the same machine too
and it stopped working without me modifying anything on those containers nor settings

**Comment by Emald000** [comment]
now says connection reset by peer in the error


[v4.0.4.1491] System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException: Unable to read data from the transport connection: Connection reset by peer.
 ---> System.Net.Sockets.SocketException (104): Connection reset by peer
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.InitialFillAsync(Boolean async)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithNtAuthAsync(HttpRequestMessage request, Uri authUri, Boolean async, ICredentials credentials, Boolean isProxyAuth, HttpConnection connection, HttpConnectionPool connectionPool, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, Boolean async, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponseAsync(HttpRequest request, CookieContainer cookies) in ./Sonarr.Common/Http/Dispatchers/ManagedHttpDispatcher.cs:line 115
   at NzbDrone.Common.Http.HttpClient.ExecuteRequestAsync(HttpRequest request, CookieContainer cookieContainer) in ./Sonarr.Common/Http/HttpClient.cs:line 157
   at NzbDrone.Common.Http.HttpClient.ExecuteAsync(HttpRequest request) in ./Sonarr.Common/Http/HttpClient.cs:line 70
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in ./Sonarr.Common/Http/HttpClient.cs:line 128
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxyV2.IsApiSupported(QBittorrentSettings settings) in ./Sonarr.Core/Download/Clients/QBittorrent/QBittorrentProxyV2.cs:line 68
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxySelector.FetchProxy(QBittorrentSettings settings) in ./Sonarr.Core/Download/Clients/QBittorrent/QBittorrentProxySelector.cs:line 96
   at NzbDrone.Common.Cache.Cached`1.Get(String key, Func`1 function, Nullable`1 lifeTime) in ./Sonarr.Common/Cache/Cached.cs:line 99
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxySelector.GetProxyCache(QBittorrentSettings settings, Boolean force) in ./Sonarr.Core/Download/Clients/QBittorrent/QBittorrentProxySelector.cs:line 72
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxySelector.GetProxy(QBittorrentSettings settings, Boolean force) in ./Sonarr.Core/Download/Clients/QBittorrent/QBittorrentProxySelector.cs:line 62
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrent.TestConnection() in ./Sonarr.Core/Download/Clients/QBittorrent/QBittorrent.cs:line 422

2024-05-18 09:57:13.1|Warn|SonarrErrorPipeline|Invalid request Validation failed: 
 -- Host: Unable to connect to qBittorrent

**Comment by rogerfar** [comment]
If you connect to the container and try to do something like:
`wget http://ipofrdt/api/v2/torrents/info`
does it return? Or can't that connect either?

**Comment by Emald000** [comment]
it returns Connecting to 192.168.31.56:6501 (192.168.31.56:6501)
wget: server returned error: HTTP/1.1 403 Forbidden

but it can connect as when i ping the adress and port it works

**Comment by Emald000** [comment]
my bad, i checked the network settings of containers and dunno how it works again
thanks a lot
