### ISSUE TITLE
Issues with Sonarr sending download requests "Failed to connect to qbittorrent. Check your settings"

### ISSUE THREAD

**Issue by WojtekHenszke** [rogerfar/rdt-client#532]
**What version are you using?**
2.0.79
**Wat OS are you running?**
Ubuntu - rdt running in docker
**Are you using Docker or as a service?**
Docker
**Which debrid provider are you using?**
Real debrid
**Which downloader are you using?**
Internal

**Please attach a log file here with the log setting set to debug**
Sonarr version: 4.0.5.1710-ls243 (same with 4.0.5.1801-ls71)

from Sonnarr pov it looks like this:
<img width="334" alt="Screenshot 2024-07-01 at 15 19 28" src="https://github.com/rogerfar/rdt-client/assets/45307075/f9676ccf-f242-4043-8daf-bc066b3504c3">

Sonarr logs:
```
[Warn] HttpClient: HTTP Error - Res: HTTP/1.1 [POST] http://192.168.1.111:6500/api/v2/torrents/add: 500.InternalServerError (15 bytes)
infringing_file 
[Fatal] SonarrErrorPipeline: Request Failed. POST /api/v3/release 
[v4.0.5.1710] NzbDrone.Core.Download.Clients.DownloadClientException: Failed to connect to qBittorrent, check your settings.
 ---> NzbDrone.Common.Http.HttpException: HTTP request failed: [500:InternalServerError] [POST] at [http://192.168.1.111:6500/api/v2/torrents/add]
   at NzbDrone.Common.Http.HttpClient.ExecuteAsync(HttpRequest request) in ./Sonarr.Common/Http/HttpClient.cs:line 119
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in ./Sonarr.Common/Http/HttpClient.cs:line 128
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxyV2.ProcessRequest(HttpRequestBuilder requestBuilder, QBittorrentSettings settings) in ./Sonarr.Core/Download/Clients/QBittorrent/QBittorrentProxyV2.cs:line 399
infringing_file
   --- End of inner exception stack trace ---
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxyV2.ProcessRequest(HttpRequestBuilder requestBuilder, QBittorrentSettings settings) in ./Sonarr.Core/Download/Clients/QBittorrent/QBittorrentProxyV2.cs:line 399
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxyV2.AddTorrentFromFile(String fileName, Byte[] fileContent, TorrentSeedConfiguration seedConfiguration, QBittorrentSettings settings) in ./Sonarr.Core/Download/Clients/QBittorrent/QBittorrentProxyV2.cs:line 181
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrent.AddFromTorrentFile(RemoteEpisode remoteEpisode, String hash, String filename, Byte[] fileContent) in ./Sonarr.Core/Download/Clients/QBittorrent/QBittorrent.cs:line 141
   at NzbDrone.Core.Download.TorrentClientBase`1.DownloadFromWebUrl(RemoteEpisode remoteEpisode, IIndexer indexer, String torrentUrl) in ./Sonarr.Core/Download/TorrentClientBase.cs:line 215
   at NzbDrone.Core.Download.TorrentClientBase`1.Download(RemoteEpisode remoteEpisode, IIndexer indexer) in ./Sonarr.Core/Download/TorrentClientBase.cs:line 129
   at NzbDrone.Core.Download.DownloadService.DownloadReport(RemoteEpisode remoteEpisode, IDownloadClient downloadClient) in ./Sonarr.Core/Download/DownloadService.cs:line 143
   at NzbDrone.Core.Download.DownloadService.DownloadReport(RemoteEpisode remoteEpisode, Nullable`1 downloadClientId) in ./Sonarr.Core/Download/DownloadService.cs:line 64
   at Sonarr.Api.V3.Indexers.ReleaseController.DownloadRelease(ReleaseResource release) in ./Sonarr.Api.V3/Indexers/ReleaseController.cs:line 160
   at lambda_method121(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Sonarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in ./Sonarr.Http/Middleware/BufferingMiddleware.cs:line 28
   at Sonarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in ./Sonarr.Http/Middleware/IfModifiedMiddleware.cs:line 41
   at Sonarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in ./Sonarr.Http/Middleware/CacheHeaderMiddleware.cs:line 33
   at Sonarr.Http.Middleware.StartingUpMiddleware.InvokeAsync(HttpContext context) in ./Sonarr.Http/Middleware/StartingUpMiddleware.cs:line 38
   at Sonarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in ./Sonarr.Http/Middleware/UrlBaseMiddleware.cs:line 27
   at Sonarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in ./Sonarr.Http/Middleware/VersionMiddleware.cs:line 29
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
   ```

Rdt logs show this:
```
[15:09:09 ERR] An unhandled exception has occurred while executing the request.
RDNET.RealDebridException: infringing_file
   at RDNET.Requests.Request(String baseUrl, String url, String headerOutput, Boolean requireAuthentication, RequestType requestType, HttpContent data, CancellationToken cancellationToken)
   at RDNET.Requests.Request[T](String baseUrl, String url, Boolean requireAuthentication, RequestType requestType, HttpContent data, CancellationToken cancellationToken)
   at RDNET.Requests.PostRequestAsync[T](String url, IEnumerable`1 data, Boolean requireAuthentication, CancellationToken cancellationToken)
   at RDNET.TorrentsApi.AddMagnetAsync(String magnet, CancellationToken cancellationToken)
   at RdtClient.Service.Services.TorrentClients.RealDebridTorrentClient.AddMagnet(String magnetLink) in /appserver/server/RdtClient.Service/Services/TorrentClients/RealDebridTorrentClient.cs:line 128
   at RdtClient.Service.Services.Torrents.UploadMagnet(String magnetLink, Torrent torrent) in /appserver/server/RdtClient.Service/Services/Torrents.cs:line 116
   at RdtClient.Service.Services.QBittorrent.TorrentsAddMagnet(String magnetLink, String category, Nullable`1 priority) in /appserver/server/RdtClient.Service/Services/QBittorrent.cs:line 470
   at RdtClient.Web.Controllers.QBittorrentController.TorrentsAdd(QBTorrentsAddRequest request) in /appserver/server/RdtClient.Web/Controllers/QBittorrentController.cs:line 321
   at RdtClient.Web.Controllers.QBittorrentController.TorrentsAddPost(QBTorrentsAddRequest request) in /appserver/server/RdtClient.Web/Controllers/QBittorrentController.cs:line 358
   at lambda_method240(Closure, Object)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at RdtClient.Service.Middleware.RequestLoggingMiddleware.Invoke(HttpContext context) in /appserver/server/RdtClient.Service/Middleware/RequestLoggingMiddleware.cs:line 15
   at Program.<>c.<<<Main>$>b__0_13>d.MoveNext() in /appserver/server/RdtClient.Web/Program.cs:line 157
--- End of stack trace from previous location ---
   at RdtClient.Service.Middleware.AuthorizeMiddleware.Invoke(HttpContext context) in /appserver/server/RdtClient.Service/Middleware/AuthorizeMiddleware.cs:line 15
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<Invoke>g__Awaited|10_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)

```

**Comment by WojtekHenszke** [comment]
ok so it looks thats the problem with the magnetlink itself.

Maybe it could be better handled than a 500 from server

**Comment by lordbeavis** [comment]
i had the same issue, something changed in the setting for radarr and sonarr. you have to re-add your remote folders

**Comment by Muneer91** [comment]
I'm having exactly the same problem here, I've tried deleting and re-adding the remote folder path as @lordbeavis suggested but didn't have any effect for me. 
If I go to prowlarr and try adding something directly, I get the same error saying failed to connect to qbitorrent. 

Interestingly, I found the magnet link and tried to add directly into rdtclient and I got the error "infringing_file"

**Comment by shulymn** [comment]
Same issue since yesterday, same error.
It worked right before and I never had to setup any remote folders, it's on the same machine.
I still set them up and it doesn't work.

**Comment by rogerfar** [comment]
The infringing_file is a bit annoying yes.

So RDT returns an exception when trying to add this torrent to RD, so it forwards this exception back to Radarr/Sonarr. But those don't handle that very well, the mark the qBittorrent integration as broken.

**Comment by Muneer91** [comment]
> The infringing_file is a bit annoying yes.
> 
> 
> 
> So RDT returns an exception when trying to add this torrent to RD, so it forwards this exception back to Radarr/Sonarr. But those don't handle that very well, the mark the qBittorrent integration as broken. 

So is this an issue with RD or Sonarr? 
Just an update, I tried the same torrent using a normal client (qBittorrent) and it downloaded and imported fine.

**Comment by Oorweeg** [comment]
This issue is with Real Debrid

If you try and add magnet there it will fail as an 'infringing torrent'. Google suggests this is because the content owner has forced RD to stop hosting that particular torrent but this is why it works in another client.

**Comment by rogerfar** [comment]
Unfortunately this isn't easily fixed. Would be nice if Radarr and Sonarr would handle exceptions from trying to add torrents better by blacklisting them.

But what I did see is this:
https://github.com/Sonarr/Sonarr/blob/72db8099e0f4abc3176e397f8dda3b2b69026daf/src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrentProxyV2.cs#L146

I could return a "Fail." which would be a better error in Radarr/Sonarr.
