### ISSUE TITLE
Problem adding torrents with latest docker image

### ISSUE THREAD

**Issue by phirestalker** [rogerfar/rdt-client#56]
I'm not sure if this is headphones or rdtclient, but I keep getting these errors every time headphones attempts to add a torrent.

```
[14:22:48 WRN] The query uses the 'First'/'FirstOrDefault' operator without 'OrderBy' and filter operators. This may lead to unpredictable results.
[14:22:48 WRN] 401: /Api/Authentication/IsLoggedIn
[14:23:54 WRN] 404: /api/v2/torrents/files
[14:23:54 WRN] 404: /api/v2/torrents/files
[14:23:54 WRN] 404: /api/v2/torrents/files
[14:23:54 WRN] 404: /api/v2/torrents/files
[14:23:54 WRN] 404: /api/v2/torrents/files
[14:23:54 WRN] 404: /api/v2/torrents/files
[14:28:46 WRN] 101: /hub
[14:28:53 WRN] 404: /api/v2/torrents/files
[14:28:53 WRN] 404: /api/v2/torrents/files
[14:28:53 WRN] 404: /api/v2/torrents/files
[14:28:53 WRN] 404: /api/v2/torrents/files
[14:28:53 WRN] 404: /api/v2/torrents/files
[14:28:54 WRN] 404: /api/v2/torrents/files
[14:30:46 WRN] 101: /hub
[14:32:46 WRN] 101: /hub
[14:33:03 ERR] An unhandled exception has occurred while executing the request.
System.FormatException: Magnet links must start with 'magnet:'.
   at MonoTorrent.MagnetLink.FromUri(Uri uri)
   at MonoTorrent.MagnetLink.Parse(String uri)
   at RdtClient.Service.Services.Torrents.UploadMagnet(String magnetLink, String category, Boolean autoDelete) in /appserver/server/RdtClient.Service/Services/Torrents.cs:line 140
   at RdtClient.Service.Services.QBittorrent.TorrentsAddMagnet(String magnetLink, String category, Boolean autoDelete) in /appserver/server/RdtClient.Service/Services/QBittorrent.cs:line 435
   at RdtClient.Web.Controllers.QBittorrentController.TorrentsAdd(QBTorrentsAddRequest request) in /appserver/server/RdtClient.Web/Controllers/QBittorrentController.cs:line 248
   at RdtClient.Web.Controllers.QBittorrentController.TorrentsAddPost(QBTorrentsAddRequest request) in /appserver/server/RdtClient.Web/Controllers/QBittorrentController.cs:line 274
   at lambda_method933(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at RdtClient.Web.Startup.<>c__DisplayClass5_0.<<Configure>b__0>d.MoveNext() in /appserver/server/RdtClient.Web/Startup.cs:line 113
--- End of stack trace from previous location ---
   at RdtClient.Service.Middleware.AuthorizeMiddleware.Invoke(HttpContext context) in /appserver/server/RdtClient.Service/Middleware/AuthorizeMiddleware.cs:line 30
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
[14:33:53 WRN] 404: /api/v2/torrents/files
[14:33:53 WRN] 404: /api/v2/torrents/files
[14:33:53 WRN] 404: /api/v2/torrents/files
[14:33:53 WRN] 404: /api/v2/torrents/files
[14:33:53 WRN] 404: /api/v2/torrents/files
[14:33:54 WRN] 404: /api/v2/torrents/files
[14:34:13 WRN] 304: /index.html
[14:34:13 WRN] 101: /hub

```

**Comment by rogerfar** [comment]
This must have been an problem from the beginning right? 

This error:
`System.FormatException: Magnet links must start with 'magnet:'.`
Shows that Headphones isn't sending a magnet prefixed with `magnet:`.

I haven't tested with Headphones, did it perhaps have an update recently?

**Comment by phirestalker** [comment]
according to git, there hasn't been an update since last year. I wonder what could have happened?

**Comment by rogerfar** [comment]
I just installed the headphones container, setup rdt-client as a downloader and Jackett as a search indexer.

It finds a torrent just fine, and it looks like it tries to add it just fine:

![image](https://user-images.githubusercontent.com/1142915/116171952-05be6a80-a6c7-11eb-9e4b-3adf5f383153.png)

**Comment by rogerfar** [comment]
What I find odd is that your log shows a 404 for `/api/v2/torrents/files`, this endpoint was added already a while back, so it should resolve just fine.

Can you doublecheck which version of rdt-client you are using?

**Comment by phirestalker** [comment]
It shows 1.7.4
the example urls in their example [here](https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-(qBittorrent-4.1)#add-new-torrent) do not start with magnet:

**Comment by rogerfar** [comment]
Could send me a pastebin or DM with the name of the albums and which torrent to download so I can see?

**Comment by phirestalker** [comment]
https://pastebin.com/4dZFQHcY

**Comment by rogerfar** [comment]
I installed Headphones and enabled the rutracker, then added this album. When it added the torrent it sent over a file, which gets processed correctly.

I have added a little code see if that solves this issue, can  you try with the latest image?

**Comment by phirestalker** [comment]
It seems to be stuck on sending to qbittorrent and there is nothing showing up in rdtclient.

**Comment by rogerfar** [comment]
Sorry can you pull the image again now? It wasn't finished publishing just yet.

**Comment by phirestalker** [comment]
Yep, it is adding it now. I will try a few more albums.
