### ISSUE TITLE
After a download reaches 800MB, the download stops and its status changes to finished

### ISSUE THREAD

**Issue by elliotjm64** [rogerfar/rdt-client#561]
**What version are you using?**
2.0.81
**Wat OS are you running?**
UnRaid 6.12.9
**Are you using Docker or as a service?**
Docker
**Which debrid provider are you using?**
AllDebrid
**Which downloader are you using?**
Internal
**Please attach a log file here with the log setting set to debug**
   at RdtClient.Service.Middleware.AuthorizeMiddleware.Invoke(HttpContext context) in /appserver/server/RdtClient.Service/Middleware/AuthorizeMiddleware.cs:line 15
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<Invoke>g__Awaited|10_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)
2024-08-08 12:45:55.751 -04:00 [WRN] Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager: No XML encryptor configured. Key {c009c1cd-e778-4c95-92ed-b2d8a298b59d} may be persisted to storage in unencrypted form.
2024-08-08 12:45:55.928 -04:00 [WRN] RdtClient.Service.BackgroundServices.Startup: Starting host on version 2.0.81.0
2024-08-08 12:51:49.776 -04:00 [ERR] RdtClient.Service.Services.Downloaders.InternalDownloader: The operation was canceled.
System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled.
 ---> System.Net.Sockets.SocketException (125): Operation canceled
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](CancellationToken cancellationToken, Int32 estimatedSize)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](Memory`1 buffer, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at DownloaderNET.Downloader.Download(Int64 thread, Chunk chunk, CancellationToken cancellationToken)
2024-08-08 12:51:49.787 -04:00 [ERR] RdtClient.Service.Services.Downloaders.InternalDownloader: The operation was canceled.
System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at DownloaderNET.Downloader.<>c__DisplayClass20_0.<<Download>b__0>d.MoveNext()

**Comment by draiko913** [comment]
For what it's worth.  I'm see the same behavior on my RDTClient instance also stopping at 800 MB.  Running 2.0.81 on Docker through an LXC on Proxmox.

**Comment by brian-sumpter** [comment]
Same issue here - stopping at ~800 mb using AllDebrid. When I switch over to my RealDebrid account, the issue goes away and everything works fine, so this is specific to AllDebrid. Running standalone installs (no Docker) on a Raspberry Pi 4.

**Comment by rogerfar** [comment]
Try using the bezzad downloader or Aria2.

**Comment by brian-sumpter** [comment]
All downloaders behave the same; this seems to be related to AllDebrid specifically, as switching to RealDebrid resolves the issue entirely.

**Comment by rogerfar** [comment]
Thats very odd, does it also happen when you download it with the browser or something like curl?

**Comment by elliotjm64** [comment]
I use JDownloader2 linked to AllDebrid and that works normally, downloading files from AllDebrid in my browser works too.

**Comment by Eranicus30666** [comment]
Same problem here, hangs at 800M in rdt client, but goes normally with wget and alldebrid link

**Comment by kuntau** [comment]
Any update on this issue? Having this problem intermittenly with **AllDebrid** and **internal downloader**

I have no clue how to debug this
