### ISSUE TITLE
Download stuck at 50% and rdt status is waiting for download links

### ISSUE THREAD

**Issue by kirantnath** [rogerfar/rdt-client#591]
**What version are you using?** 2.0.86

**Wat OS are you running?** Synology DAS

**Are you using Docker or as a service?** Yes

**Which debrid provider are you using?** Real Debrid

**Which downloader are you using?**  Internal

**Please attach a log file here with the log setting set to debug**

Please refer to the screenshots below. The download is stuck at 50% in both RADARR and SONARR. Log is attached as well.

![image](https://github.com/user-attachments/assets/01f91cb8-e2f6-40a3-a670-16827ea6c1f5)

![image](https://github.com/user-attachments/assets/457692bd-8e33-4d5a-95f8-d446443a1508)

https://www.linuxserver.io/donate/

───────────────────────────────────────

GID/UID

───────────────────────────────────────

User UID:    1026

User GID:    100

───────────────────────────────────────

Setting permissions

[custom-init] No custom files found, skipping...

Setting permissions

Changing to /app folder

Starting rtdclient

[ls.io-init] done.

[21:36:15 WRN] Starting host on version 2.0.86.0

[21:39:24 ERR] Cannot unrestrict link: {ex.Message}

System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 10 seconds elapsing.

 ---> System.TimeoutException: A task was canceled.

 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.

   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)

   at Polly.AsyncPolicy`1.ExecuteAsync(Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)

   at Microsoft.Extensions.Http.PolicyHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)

   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.<SendCoreAsync>g__Core|5_0(HttpRequestMessage request, Boolean useAsync, CancellationToken cancellationToken)

   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)

   --- End of inner exception stack trace ---

   --- End of inner exception stack trace ---

   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)

   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)

   at RDNET.Requests.Request(String baseUrl, String url, String headerOutput, Boolean requireAuthentication, RequestType requestType, HttpContent data, CancellationToken cancellationToken)

   at RDNET.Requests.Request(String baseUrl, String url, String headerOutput, Boolean requireAuthentication, RequestType requestType, HttpContent data, CancellationToken cancellationToken)

   at RDNET.Requests.Request[T](String baseUrl, String url, Boolean requireAuthentication, RequestType requestType, HttpContent data, CancellationToken cancellationToken)

   at RDNET.Requests.PostRequestAsync[T](String url, IEnumerable`1 data, Boolean requireAuthentication, CancellationToken cancellationToken)

   at RDNET.UnrestrictApi.LinkAsync(String link, String password, Boolean remote, CancellationToken cancellationToken)

   at RdtClient.Service.Services.TorrentClients.RealDebridTorrentClient.Unrestrict(String link) in /appserver/server/RdtClient.Service/Services/TorrentClients/RealDebridTorrentClient.cs:line 271

   at RdtClient.Service.Services.Torrents.UnrestrictLink(Guid downloadId) in /appserver/server/RdtClient.Service/Services/Torrents.cs:line 364

   at RdtClient.Service.Services.TorrentRunner.Tick() in /appserver/server/RdtClient.Service/Services/TorrentRunner.cs:line 350

[21:40:42 ERR] Cannot unrestrict link: {ex.Message}

System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 10 seconds elapsing.

 ---> System.TimeoutException: A task was canceled.

 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.

   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)

   at Polly.AsyncPolicy`1.ExecuteAsync(Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)

   at Microsoft.Extensions.Http.PolicyHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)

   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.<SendCoreAsync>g__Core|5_0(HttpRequestMessage request, Boolean useAsync, CancellationToken cancellationToken)

   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)

   --- End of inner exception stack trace ---

   --- End of inner exception stack trace ---

   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)

   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)

   at RDNET.Requests.Request(String baseUrl, String url, String headerOutput, Boolean requireAuthentication, RequestType requestType, HttpContent data, CancellationToken cancellationToken)

   at RDNET.Requests.Request(String baseUrl, String url, String headerOutput, Boolean requireAuthentication, RequestType requestType, HttpContent data, CancellationToken cancellationToken)

   at RDNET.Requests.Request[T](String baseUrl, String url, Boolean requireAuthentication, RequestType requestType, HttpContent data, CancellationToken cancellationToken)

   at RDNET.Requests.PostRequestAsync[T](String url, IEnumerable`1 data, Boolean requireAuthentication, CancellationToken cancellationToken)

   at RDNET.UnrestrictApi.LinkAsync(String link, String password, Boolean remote, CancellationToken cancellationToken)

   at RdtClient.Service.Services.TorrentClients.RealDebridTorrentClient.Unrestrict(String link) in /appserver/server/RdtClient.Service/Services/TorrentClients/RealDebridTorrentClient.cs:line 271

   at RdtClient.Service.Services.Torrents.UnrestrictLink(Guid downloadId) in /appserver/server/RdtClient.Service/Services/Torrents.cs:line 364

   at RdtClient.Service.Services.TorrentRunner.Tick() in /appserver/server/RdtClient.Service/Services/TorrentRunner.cs:line 350

[21:42:01 ERR] Cannot unrestrict link: {ex.Message}

System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 10 seconds elapsing.

 ---> System.TimeoutException: A task was canceled.

 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.

   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)

   at Polly.AsyncPolicy`1.ExecuteAsync(Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)

   at Microsoft.Extensions.Http.PolicyHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)

   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.<SendCoreAsync>g__Core|5_0(HttpRequestMessage request, Boolean useAsync, CancellationToken cancellationToken)

   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)

   --- End of inner exception stack trace ---

   --- End of inner exception stack trace ---

   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)

   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)

   at RDNET.Requests.Request(String baseUrl, String url, String headerOutput, Boolean requireAuthentication, RequestType requestType, HttpContent data, CancellationToken cancellationToken)

   at RDNET.Requests.Request(String baseUrl, String url, String headerOutput, Boolean requireAuthentication, RequestType requestType, HttpContent data, CancellationToken cancellationToken)

   at RDNET.Requests.Request[T](String baseUrl, String url, Boolean requireAuthentication, RequestType requestType, HttpContent data, CancellationToken cancellationToken)

   at RDNET.Requests.PostRequestAsync[T](String url, IEnumerable`1 data, Boolean requireAuthentication, CancellationToken cancellationToken)

   at RDNET.UnrestrictApi.LinkAsync(String link, String password, Boolean remote, CancellationToken cancellationToken)

   at RdtClient.Service.Services.TorrentClients.RealDebridTorrentClient.Unrestrict(String link) in /appserver/server/RdtClient.Service/Services/TorrentClients/RealDebridTorrentClient.cs:line 271

   at RdtClient.Service.Services.Torrents.UnrestrictLink(Guid downloadId) in /appserver/server/RdtClient.Service/Services/Torrents.cs:line 364

   at RdtClient.Service.Services.TorrentRunner.Tick() in /appserver/server/RdtClient.Service/Services/TorrentRunner.cs:line 350

[21:43:20 ERR] Cannot unrestrict link: {ex.Message}

System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 10 seconds elapsing.

 ---> System.TimeoutException: A task was canceled.

 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.

   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)

   at Polly.AsyncPolicy`1.ExecuteAsync(Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)

   at Microsoft.Extensions.Http.PolicyHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)

   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.<SendCoreAsync>g__Core|5_0(HttpRequestMessage request, Boolean useAsync, CancellationToken cancellationToken)

   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)

   --- End of inner exception stack trace ---

   --- End of inner exception stack trace ---

   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)

   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)

   at RDNET.Requests.Request(String baseUrl, String url, String headerOutput, Boolean requireAuthentication, RequestType requestType, HttpContent data, CancellationToken cancellationToken)

   at RDNET.Requests.Request(String baseUrl, String url, String headerOutput, Boolean requireAuthentication, RequestType requestType, HttpContent data, CancellationToken cancellationToken)

   at RDNET.Requests.Request[T](String baseUrl, String url, Boolean requireAuthentication, RequestType requestType, HttpContent data, CancellationToken cancellationToken)

   at RDNET.Requests.PostRequestAsync[T](String url, IEnumerable`1 data, Boolean requireAuthentication, CancellationToken cancellationToken)

   at RDNET.UnrestrictApi.LinkAsync(String link, String password, Boolean remote, CancellationToken cancellationToken)

   at RdtClient.Service.Services.TorrentClients.RealDebridTorrentClient.Unrestrict(String link) in /appserver/server/RdtClient.Service/Services/TorrentClients/RealDebridTorrentClient.cs:line 271

   at RdtClient.Service.Services.Torrents.UnrestrictLink(Guid downloadId) in /appserver/server/RdtClient.Service/Services/Torrents.cs:line 364

   at RdtClient.Service.Services.TorrentRunner.Tick() in /appserver/server/RdtClient.Service/Services/TorrentRunner.cs:line 350

**Comment by kirantnath** [comment]
restarting the container seemed to fix it. Thanks
