### ISSUE TITLE
docker container permissions under dockage in truenas not working

### ISSUE THREAD

**Issue by douroudou** [rogerfar/rdt-client#629]
Hi, 
This is a repetition of issues #41 & #455 but it seems to exist in the combination of new TrueNAS SCALE 24.10 and dockge implementation. 

When I set the path /mnt/downloads in the web interface and execute a speed test I get the following:

> Test download path permissions
>    Could not test your download path
>    Access to the path '/mnt/downloads/test.txt' is denied. 

However, when I enter the bash on the container and execute the following:

`root@a11b8e9c5ff9:/app# vi test`
`root@a11b8e9c5ff9:/app# ls -l /mnt/downloads/`
`total 1`
`-rwxrwx--- 1 root root 9 Dec  5 00:37 test`
the result means I can create and edit a file in the path. 

This is my compose.yaml

version: "3.8"
services:
  rdtclient:
    image: rogerfar/rdtclient
    container_name: rdtclient
    # build:
    #     context: .
    #     dockerfile: Dockerfile
    environment:
      - PUID=1001
      - PGID=1001
      - UMASK=002
      - TZ=Europe/Minsk
    volumes:
      - ${PWD}/data/downloads:/data/downloads
      - ${PWD}/data/db:/data/db
      - /mnt/HDD_Pool/downloads:/mnt/downloads
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 10m
    ports:
      - 36500:6500
    healthcheck:
      test: curl --fail http://X.X.X.X:36500 || exit 1
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 30s
networks: {}

**What version are you using?**
rogerfar/rdtclient:latest updated 12-04-2024
**Wat OS are you running?**
Truenas SCALE 24.10.0.2
**Are you using Docker or as a service?**
I am using dockge which I run as an app under Truenas
**Which debrid provider are you using?**
Real Debrid
**Which downloader are you using?**
Radarr/Prowlarr
**Please attach a log file here with the log setting set to debug**
...

rdtclient  | User UID:    1001
rdtclient  | User GID:    1001
rdtclient  | ───────────────────────────────────────
rdtclient  | Setting permissions
rdtclient  | [custom-init] No custom files found, skipping...
rdtclient  | [ls.io-init] done.
rdtclient  | Setting permissions
rdtclient  | Changing to /app folder
rdtclient  | Starting rtdclient
rdtclient  | [01:07:03 WRN] Starting host on version 2.0.89.0
rdtclient  | [01:07:22 ERR] An unhandled exception has occurred while executing the request.
rdtclient  | System.UnauthorizedAccessException: Access to the path '/mnt/downloads/test.txt' is denied.
rdtclient  |  ---> System.IO.IOException: Permission denied
rdtclient  |    --- End of inner exception stack trace ---
rdtclient  |    at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
rdtclient  |    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
rdtclient  |    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
rdtclient  |    at System.IO.File.OpenHandle(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
rdtclient  |    at System.IO.File.WriteToFileAsync(String path, FileMode mode, ReadOnlyMemory`1 contents, Encoding encoding, CancellationToken cancellationToken)
rdtclient  |    at RdtClient.Web.Controllers.SettingsController.TestPath(SettingsControllerTestPathRequest request) in /appserver/server/RdtClient.Web/Controllers/SettingsController.cs:line 71
rdtclient  |    at lambda_method81(Closure, Object)
rdtclient  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
rdtclient  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
rdtclient  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
rdtclient  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
rdtclient  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
rdtclient  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
rdtclient  | --- End of stack trace from previous location ---
rdtclient  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
rdtclient  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
rdtclient  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
rdtclient  |    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
rdtclient  |    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
rdtclient  |    at RdtClient.Service.Middleware.RequestLoggingMiddleware.Invoke(HttpContext context) in /appserver/server/RdtClient.Service/Middleware/RequestLoggingMiddleware.cs:line 15
rdtclient  |    at Program.<>c.<<<Main>$>b__0_13>d.MoveNext() in /appserver/server/RdtClient.Web/Program.cs:line 155
rdtclient  | --- End of stack trace from previous location ---
rdtclient  |    at RdtClient.Service.Middleware.AuthorizeMiddleware.Invoke(HttpContext context) in /appserver/server/RdtClient.Service/Middleware/AuthorizeMiddleware.cs:line 15
rdtclient  |    at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<Invoke>g__Awaited|10_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)

**Comment by douroudou** [comment]
It seems that I had to map the TrueNAS folder to data/downloads and set PUID/GUID to 1000/1000 for it to work. 
Here is the working compose.yaml if anyone needs it in the future:
`
version: "3.8"
services:
  rdtclient:
    image: rogerfar/rdtclient
    container_name: rdtclient
    # build:
    #     context: .
    #     dockerfile: Dockerfile
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Minsk
    volumes:
      - ${PWD}/mnt/HDD_Pool/downloads:/data/downloads
      - ${PWD}/data/db:/data/db
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 10m
    ports:
      - 36500:6500
    healthcheck:
      test: curl --fail http://127.0.0.1:36500 || exit 1
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 30s
networks: {}
`
