### ISSUE TITLE
Torbox symlink 

### ISSUE THREAD

**Issue by cmaquerre** [rogerfar/rdt-client#630]
**2.0.89**

**Ubuntu / docker**

**Docker**

**Torbox**

**symlink**

Hello,in first thanks for your job ! 

I have a bug with tobox and symlink downloader, i have pull the latest update, but i still have the bug.

I replaced my token with MY_TOKEN because it was visible.

This is my log :

`2024-12-05 11:08:37.065 +01:00 [ERR] RdtClient.Service.Services.TorrentRunner: Unable to start download: An unexpected error occurred preparing download https://storage-zip.torbox.app/zip/bec6a4f4-3169-4fae-a6be-6dd57783bf7e?token=MY_TOKEN for torrent Aquamarine 2006.MULTi.VF2.1080p.DSNP.WEB.DDP5.1.H264-TyHD: The value cannot be an empty string. (Parameter 'oldValue') for download bec6a4f4-3169-4fae-a6be-6dd57783bf7e. Completed: 0%, avg speed: 0bytes/s (64d40462-3bbb-43b1-b55b-ab2e730ce821) remoteID:  for torrent Aquamarine 2006.MULTi.VF2.1080p.DSNP.WEB.DDP5.1.H264-TyHD (c154697bb67f2890a869cf7ee56007bbe54fa389 - cached 100%) (05925bdf-2588-482d-959d-d02a37be3c3c)
2024-12-05 11:08:38.066 +01:00 [ERR] RdtClient.Service.Services.TorrentRunner: Download reported an error: The value cannot be an empty string. (Parameter 'oldValue') for download bec6a4f4-3169-4fae-a6be-6dd57783bf7e. Completed: 0%, avg speed: 0bytes/s (64d40462-3bbb-43b1-b55b-ab2e730ce821) remoteID:  for torrent Aquamarine 2006.MULTi.VF2.1080p.DSNP.WEB.DDP5.1.H264-TyHD (c154697bb67f2890a869cf7ee56007bbe54fa389 - cached 100%) (05925bdf-2588-482d-959d-d02a37be3c3c)
2024-12-05 11:08:39.937 +01:00 [ERR] RdtClient.Service.Services.TorrentRunner: Unable to start download: An unexpected error occurred preparing download https://storage-zip.torbox.app/zip/1d012f28-28d8-45f9-bcd6-0be6688d3c5c?token=MY_TOKEN for torrent Aquamarine 2006.MULTi.VF2.1080p.DSNP.WEB.DDP5.1.H264-TyHD: The value cannot be an empty string. (Parameter 'oldValue') for download 1d012f28-28d8-45f9-bcd6-0be6688d3c5c. Completed: 0%, avg speed: 0bytes/s (64d40462-3bbb-43b1-b55b-ab2e730ce821) remoteID:  for torrent Aquamarine 2006.MULTi.VF2.1080p.DSNP.WEB.DDP5.1.H264-TyHD (c154697bb67f2890a869cf7ee56007bbe54fa389 - cached 100%) (05925bdf-2588-482d-959d-d02a37be3c3c)
2024-12-05 11:08:40.938 +01:00 [ERR] RdtClient.Service.Services.TorrentRunner: Download reported an error: The value cannot be an empty string. (Parameter 'oldValue') for download 1d012f28-28d8-45f9-bcd6-0be6688d3c5c. Completed: 0%, avg speed: 0bytes/s (64d40462-3bbb-43b1-b55b-ab2e730ce821) remoteID:  for torrent Aquamarine 2006.MULTi.VF2.1080p.DSNP.WEB.DDP5.1.H264-TyHD (c154697bb67f2890a869cf7ee56007bbe54fa389 - cached 100%) (05925bdf-2588-482d-959d-d02a37be3c3c)
2024-12-05 11:08:45.512 +01:00 [ERR] RdtClient.Service.Services.TorrentRunner: Unable to start download: An unexpected error occurred preparing download https://storage-zip.torbox.app/zip/090bf761-4469-4d2d-beea-451b5915d3dc?token=MY_TOKEN for torrent Aquamarine 2006.MULTi.VF2.1080p.DSNP.WEB.DDP5.1.H264-TyHD: The value cannot be an empty string. (Parameter 'oldValue') for download 090bf761-4469-4d2d-beea-451b5915d3dc. Completed: 0%, avg speed: 0bytes/s (64d40462-3bbb-43b1-b55b-ab2e730ce821) remoteID:  for torrent Aquamarine 2006.MULTi.VF2.1080p.DSNP.WEB.DDP5.1.H264-TyHD (c154697bb67f2890a869cf7ee56007bbe54fa389 - cached 100%) (05925bdf-2588-482d-959d-d02a37be3c3c)
2024-12-05 11:08:46.513 +01:00 [ERR] RdtClient.Service.Services.TorrentRunner: Download reported an error: The value cannot be an empty string. (Parameter 'oldValue') for download 090bf761-4469-4d2d-beea-451b5915d3dc. Completed: 0%, avg speed: 0bytes/s (64d40462-3bbb-43b1-b55b-ab2e730ce821) remoteID:  for torrent Aquamarine 2006.MULTi.VF2.1080p.DSNP.WEB.DDP5.1.H264-TyHD (c154697bb67f2890a869cf7ee56007bbe54fa389 - cached 100%) (05925bdf-2588-482d-959d-d02a37be3c3c)
`

**Comment by rogerfar** [comment]
I don't think the Symlink downloader works with Torbox, should it?

**Comment by cmaquerre** [comment]
Ho I thought it worked, do you think it is possible to make it work?

Because I use RDT but some torrents no longer work in upload because of the new rdt rules and I wanted to turn to torbox which accepts them.

However I use symlinks with RDT and with torbox I managed to mount my webdav I thought it would work the same way

**Comment by asylumexp** [comment]
I’ll have a go at fixing this next week after doing #616

**Comment by cmaquerre** [comment]
Ha ok, thanks you !

**Comment by asylumexp** [comment]
Can someone test it on latest update with flatten webdav option enabled in TorBox settings?

**Comment by cmaquerre** [comment]
Hello,


I tried and it works thank you,

However, I have a "display" problem. 

Let me explain, via Radarr no problem but via sonarr I added an episode and a season, I had in this screen : 
![image](https://github.com/user-attachments/assets/549afba0-4bf9-42a7-86d7-dbaa6ce11174)

And in sonar activity nothing was displayed.

But once downloaded to torbox the file has been created and moved

![image](https://github.com/user-attachments/assets/0d91bccc-9d3c-48f6-8c1d-603efb98a490)

`2024-12-12 11:59:10.916 +01:00 [ERR] RdtClient.Service.BackgroundServices.TaskRunner: Unexpected error occurred in ProviderUpdater: Value cannot be null. (Parameter 'source')
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at RdtClient.Service.Services.TorrentClients.TorBoxTorrentClient.Map(TorrentInfoResult torrent) in /appserver/server/RdtClient.Service/Services/TorrentClients/TorBoxTorrentClient.cs:line 64
   at System.Linq.Enumerable.ListSelectIterator`2.ToList()
   at RdtClient.Service.Services.TorrentClients.TorBoxTorrentClient.GetTorrents() in /appserver/server/RdtClient.Service/Services/TorrentClients/TorBoxTorrentClient.cs:line 107
   at RdtClient.Service.Services.Torrents.UpdateRdData() in /appserver/server/RdtClient.Service/Services/Torrents.cs:line 410
   at RdtClient.Service.BackgroundServices.ProviderUpdater.ExecuteAsync(CancellationToken stoppingToken) in /appserver/server/RdtClient.Service/BackgroundServices/ProviderUpdater.cs:line 53
2024-12-12 11:59:11.180 +01:00 [DBG] RdtClient.Service.Services.TorrentRunner: Processing 3 torrents
2024-12-12 11:59:11.180 +01:00 [DBG] RdtClient.Service.Services.TorrentRunner: Currently 0 queued downloads and 0 total active downloads for torrent  (978a7b9041f2b96ee2d9ce9a616b227e771beabc -  %) (d1780765-c1bb-409f-a3e6-f0af0e1464b7)
2024-12-12 11:59:11.180 +01:00 [DBG] RdtClient.Service.Services.TorrentRunner: Processing for torrent  (978a7b9041f2b96ee2d9ce9a616b227e771beabc -  %) (d1780765-c1bb-409f-a3e6-f0af0e1464b7)
2024-12-12 11:59:11.180 +01:00 [DBG] RdtClient.Service.Services.TorrentRunner: Currently 0 queued downloads and 0 total active downloads for torrent  (70718c622572ae135d6f9fd48de6e8f26428a944 -  %) (28148769-8e66-43da-a2f6-3c9d82cf46a4)
2024-12-12 11:59:11.180 +01:00 [DBG] RdtClient.Service.Services.TorrentRunner: Processing for torrent  (70718c622572ae135d6f9fd48de6e8f26428a944 -  %) (28148769-8e66-43da-a2f6-3c9d82cf46a4)
2024-12-12 11:59:11.180 +01:00 [DBG] RdtClient.Service.Services.TorrentRunner: Currently 0 queued downloads and 0 total active downloads for torrent  (2b077df3b7873f0149feb76e59e7b8eaa2c232ac -  %) (5fbb1795-03df-4321-be85-737aeb18682b)
2024-12-12 11:59:11.180 +01:00 [DBG] RdtClient.Service.Services.TorrentRunner: Processing for torrent  (2b077df3b7873f0149feb76e59e7b8eaa2c232ac -  %) (5fbb1795-03df-4321-be85-737aeb18682b)
2024-12-12 11:59:12.181 +01:00 [DBG] RdtClient.Service.Services.TorrentRunner: Processing 3 torrents
2024-12-12 11:59:12.181 +01:00 [DBG] RdtClient.Service.Services.TorrentRunner: Currently 0 queued downloads and 0 total active downloads for torrent  (978a7b9041f2b96ee2d9ce9a616b227e771beabc -  %) (d1780765-c1bb-409f-a3e6-f0af0e1464b7)
2024-12-12 11:59:12.181 +01:00 [DBG] RdtClient.Service.Services.TorrentRunner: Processing for torrent  (978a7b9041f2b96ee2d9ce9a616b227e771beabc -  %) (d1780765-c1bb-409f-a3e6-f0af0e1464b7)
2024-12-12 11:59:12.181 +01:00 [DBG] RdtClient.Service.Services.TorrentRunner: Currently 0 queued downloads and 0 total active downloads for torrent  (70718c622572ae135d6f9fd48de6e8f26428a944 -  %) (28148769-8e66-43da-a2f6-3c9d82cf46a4)
2024-12-12 11:59:12.181 +01:00 [DBG] RdtClient.Service.Services.TorrentRunner: Processing for torrent  (70718c622572ae135d6f9fd48de6e8f26428a944 -  %) (28148769-8e66-43da-a2f6-3c9d82cf46a4)
2024-12-12 11:59:12.181 +01:00 [DBG] RdtClient.Service.Services.TorrentRunner: Currently 0 queued downloads and 0 total active downloads for torrent  (2b077df3b7873f0149feb76e59e7b8eaa2c232ac -  %) (5fbb1795-03df-4321-be85-737aeb18682b)
2024-12-12 11:59:12.181 +01:00 [DBG] RdtClient.Service.Services.TorrentRunner: Processing for torrent  (2b077df3b7873f0149feb76e59e7b8eaa2c232ac -  %) (5fbb1795-03df-4321-be85-737aeb18682b)`

**Comment by asylumexp** [comment]
try deleting and re adding once it’s cached on torbox. Could you also close this issue as complete, since the symlink downloader itself now works.

**Comment by asylumexp** [comment]
@cmaquerre 
> However, I have a "display" problem.
> 
> Let me explain, via Radarr no problem but via sonarr I added an episode and a season, I had in this screen :

This is fixed by #637
