### ISSUE TITLE
Unable to connect to Real-debrid

### ISSUE THREAD

**Issue by no-usr-nm** [rogerfar/rdt-client#64]
Hi

First of all thanks for the hard work on this excellent project.

So I had an instance of rdt-client working but due to me messing around a bit too much with Sonarr/Radarr it got a bit messy so I decided I wanted to start clean so I deleted my docker container and started a new one. Since starting the new one I haven't been able to successfully connect to Real-debrid. All my settings are the same as the one that was previously working.

From looking at the logs I found one error and it looks like it's an error connecting to real-debrid that seems to resulting in a 500 error response.

If there is any additional info that I could give to help diagnose the issue please let me know

```
2021-05-25 20:24:13.429 +01:00 [DBG] Establishing new connection.
2021-05-25 20:24:13.439 +01:00 [DBG] OnConnectedAsync started.
2021-05-25 20:24:13.445 +01:00 [DBG] Socket opened using Sub-Protocol: 'null'.
2021-05-25 20:24:13.362 +01:00 [ERR] An unhandled exception has occurred while executing the request.
System.Net.Http.HttpRequestException: Resource temporarily unavailable (api.real-debrid.com:443)
 ---> System.Net.Sockets.SocketException (11): Resource temporarily unavailable
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|283_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.DefaultConnectAsync(SocketsHttpConnectionContext context, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at RDNET.RdNetClient.Get[T](String url, Boolean repeatRequest)
   at RDNET.RdNetClient.GetUserAsync()
   at RdtClient.Service.Services.Torrents.GetProfile() in /appserver/server/RdtClient.Service/Services/Torrents.cs:line 309
   at RdtClient.Web.Controllers.SettingsController.Profile() in /appserver/server/RdtClient.Web/Controllers/SettingsController.cs:line 59
   at lambda_method179(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at RdtClient.Web.Startup.<>c__DisplayClass5_0.<<Configure>b__0>d.MoveNext() in /appserver/server/RdtClient.Web/Startup.cs:line 107
--- End of stack trace from previous location ---
   at RdtClient.Service.Middleware.AuthorizeMiddleware.Invoke(HttpContext context) in /appserver/server/RdtClient.Service/Middleware/AuthorizeMiddleware.cs:line 24
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
2021-05-25 20:24:13.475 +01:00 [DBG] Connection id "0HM8VMAL7CP11" completed keep alive response.
2021-05-25 20:24:13.475 +01:00 [DBG] 'DataContext' disposed.
2021-05-25 20:24:13.476 +01:00 [INF] Request finished HTTP/1.1 GET http://192.168.1.227:6500/Api/Settings/Profile - - - 500 - application/json 344.3410ms
```

**Comment by rogerfar** [comment]
Are you sure your API token is correct?

**Comment by no-usr-nm** [comment]
> Are you sure your API token is correct?

99.99% sure. That was the first thing I thought when I saw the error in the logs so I've checked it a few times and copied it again and it seems to be correct

**Comment by rogerfar** [comment]
That is odd then, usually when you get the error `Resource temporarily unavailable (api.real-debrid.com:443)` it means your API token is wrong.

Are you familiar with Postman? If so you can check if a raw request to the API with your token actually works.

**Comment by no-usr-nm** [comment]
Yeah I'm fairly familiar with it
I did a quick check for the ```/user``` api and got this

```json
{
        "error": "bad_token",
        "error_code": 8
}
```

I've checked multiple times but it seems like I've copied the key correctly. I wonder is it possible that my key has been blacklisted or something because I messed up somehow when removing my previous docker container.

Do you know is there anyway I can get my key revoked/change when logged into the real-debrid site. I can't seem to find this.

ps I completely understand this is not an issue with your app so feel free to close this issue at any time

**Comment by rogerfar** [comment]
You can try the `disable_access_token` endpoint with your broken API key, see if that works.

**Comment by no-usr-nm** [comment]
> You can try the `disable_access_token` endpoint with your broken API key, see if that works.

That was the first thing I tried after running the previous request but it had the same response. 

Anyway it looks like the issue is unrelated to your client so I'll close this issue and try and get to the bottom of it myself. Thanks for the help
