### ISSUE TITLE
Downloads not getting assigned to a category from Radarr, Sonarr

### ISSUE THREAD

**Issue by mitchellcro** [rogerfar/rdt-client#641]
**What version are you using?**
2.0.91
**Wat OS are you running?**
Debian
**Are you using Docker or as a service?**
tteck script on Proxmox
**Which debrid provider are you using?**
Torbox
**Which downloader are you using?**
Internal
**Please attach a log file here with the log setting set to debug**
2024-12-20 14:19:36.244 -05:00 [ERR] Microsoft.EntityFrameworkCore.Database.Command: Failed executing DbCommand (0ms) [Parameters=[@p0='?' (DbType = Guid), @p1>
INSERT INTO "Downloads" ("DownloadId", "Added", "Completed", "DownloadFinished", "DownloadQueued", "DownloadStarted", "Error", "FileName", "Link", "Path", "Rem>
VALUES (@p0, @p1, @p2, @p3, @p4, @p5, @p6, @p7, @p8, @p9, @p10, @p11, @p12, @p13, @p14, @p15);
2024-12-20 14:19:36.245 -05:00 [ERR] Microsoft.EntityFrameworkCore.Update: An exception occurred in the database while saving changes for context type 'RdtClie>
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
 ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'FOREIGN KEY constraint failed'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellati>
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellati>
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToke>
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToke>
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToke>
   
 There is erratic behavior when assigning categories to downloads. When a category isn't assigned, the *arr services don't recognize the file is there and doesn't move it to the appropriate file path after unpacking. I'm not entirely sure why, but when a download doesn't get assigned a category, the above error is thrown.

**Comment by rogerfar** [comment]
Can you post a fuller log? The error `SQLite Error 19: 'FOREIGN KEY constraint failed'.` is very odd.

**Comment by mitchellcro** [comment]
Since creating this issue, I determined that Torbox is hot garbage and switched to a different debrid provider. Once I did that, I haven't had any issues.
