### ISSUE TITLE
RDTclient crashes on start up

### ISSUE THREAD

**Issue by malbrax** [rogerfar/rdt-client#71]
I have all the net frame work installed, 

Check if the service is running but that is not the case

If it helps I had it set up on docker but couldn't get it to work as I am not familiar with the program, 
On docker I could log in to Webui and set up on sonarr/radarr but it would not download anything so stopped using it

Site can't be reached when trying to log on 

Appsettings are below but I don't see a log being created
{
  "Logging": {
    "File": {
      "Path": "C:\\RdtClient\\db\\rdtclient.log",
      "Append": "True",
      "FileSizeLimitBytes": 5242880,
      "MaxRollingFiles": 5
    }
  },
  "Database": {
    "Path": "C:\\RdtClient\\db\\rdtclient.db"
  },
  "AllowedHosts": "*",
  "HostUrl": "http://0.0.0.0:6500"
}

**Comment by malbrax** [comment]
Ran this one from one of your earlier post says this but I have it installed :( 

C:\Users\gunth>dotnet RdtClient.Web.dll
Could not execute because the application was not found or a compatible .NET SDK is not installed.
Possible reasons for this include:
  * You intended to execute a .NET program:
      The application 'RdtClient.Web.dll' does not exist.
  * You intended to execute a .NET SDK command:
      It was not possible to find any installed .NET SDKs.
      Install a .NET SDK from:
        https://aka.ms/dotnet-download

**Comment by malbrax** [comment]
Quick update on this one, Got it working as it was indeed missing a specific framework 
ASP.NET Core 5.0 Runtime (v5.0.0)

Still does not download from Radarr/Sonarr :( 

Nothing gets pulled from Debrid from adding and setting it to download

**Comment by rogerfar** [comment]
Did you setup Sonarr/Radarr as the qBittorrent download client and if you hit "Test" does it show an OK status?

Also do you have real-debrid premium and do you see your name in the right top in Real Debrid Client?

**Comment by malbrax** [comment]
Yes and yes 

I only had the qBittorrent set without and indexers, My guess is that was causing issues?

I added rarbg as an indexer and it got rid of the errors on sonarr/radarr

On Radarr it does not auto download movie unless manually clicked, Looks like it did for sonarr 

Now the test stopped on sonarr/radarr does not pass anymore

 at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at RdtClient.Web.Startup.<>c__DisplayClass5_0.<<Configure>b__0>d.MoveNext() in C:\Projects\rdt-client\server\RdtClient.Web\Startup.cs:line 113

**Comment by malbrax** [comment]
An unhandled exception has occurred while executing the request.
System.ArgumentException: An item with the same key has already been added. Key: radarr
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](List`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at RdtClient.Service.Services.QBittorrent.TorrentsCategories() in C:\Projects\rdt-client\server\RdtClient.Service\Services\QBittorrent.cs:line 461
   at RdtClient.Web.Controllers.QBittorrentController.TorrentsCategories() in C:\Projects\rdt-client\server\RdtClient.Web\Controllers\QBittorrentController.cs:line 323
   at lambda_method294(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()

**Comment by malbrax** [comment]
An unhandled exception has occurred while executing the request.
System.ArgumentException: An item with the same key has already been added. Key: tc-sonarr

Any idea how to fix this?

Thanks

**Comment by rogerfar** [comment]
Can you delete your database file and do the setup process again.

I think that somehow you managed to add a duplicate category to the preferences.

**Comment by malbrax** [comment]
Hi,

Did that and it works for a little work but starts happening again 


1:04:26 ERR] An unhandled exception has occurred while executing the request.
System.ArgumentException: An item with the same key has already been added. Key: tc-sonarr
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](List`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at RdtClient.Service.Services.QBittorrent.TorrentsCategories() in C:\Projects\rdt-client\server\RdtClient.Service\Services\QBittorrent.cs:line 470
   at RdtClient.Web.Controllers.QBittorrentController.TorrentsCategories() in C:\Projects\rdt-client\server\RdtClient.Web\Controllers\QBittorrentController.cs:line 326
   at lambda_method474(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at RdtClient.Web.Startup.<>c__DisplayClass5_0.<<Configure>b__0>d.MoveNext() in C:\Projects\rdt-client\server\RdtClient.Web\Startup.cs:line 113
--- End of stack trace from previous location ---
   at RdtClient.Service.Middleware.AuthorizeMiddleware.Invoke(HttpContext context) in C:\Projects\rdt-client\server\RdtClient.Service\Middleware\AuthorizeMiddleware.cs:line 30
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)

**Comment by rogerfar** [comment]
Could you send me your full log file?

**Comment by malbrax** [comment]
[rdtclient_013.log](https://github.com/rogerfar/rdt-client/files/6978267/rdtclient_013.log)
[rdtclient_012.log](https://github.com/rogerfar/rdt-client/files/6978268/rdtclient_012.log)
[rdtclient_011.log](https://github.com/rogerfar/rdt-client/files/6978269/rdtclient_011.log)

**Comment by rogerfar** [comment]
Are you running the latest version? Can you perhaps stop RDT, then delete the logs and restart?

**Comment by malbrax** [comment]
Just downloaded the latest version, deleted the folder /database/logs and started over

will test

**Comment by malbrax** [comment]
[rdtclient.log](https://github.com/rogerfar/rdt-client/files/6985737/rdtclient.log)
 
latest log with issues

**Comment by rogerfar** [comment]
I had a look in the log but I don't see the issue you are describing.

It doesn't continue downloading right now, is that correct?

What I do see is this:
```
 ---> System.IO.IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..
 ---> System.Net.Sockets.SocketException (995): The I/O operation has been aborted because of either a thread exit or an application request.
```
This seems to be a connectivity issue between your host and Real-Debrid. What country are you connecting from?

**Comment by malbrax** [comment]
Just installed the new version yesterday evening so haven't seen the earlier issue yet,
Last log has this new issue where it gives that error and video downloading fails

Toronto, Canada 
Rogers

Didn't have this error before
