### ISSUE TITLE
Launch issue after update  /  sudden spike in CPU usage

### ISSUE THREAD

**Issue by IrealiTY** [rogerfar/rdt-client#84]
**What version are you using?**
1.9.4

**Wat OS are you running?**
Synology

**Are you using Docker or as a service?**
Docker

I noticed an extremely high bandwidth usage on my Synology NAS and noticed that rdt-client was using a huge amount of CPU and memory, killed the process and decided to restart. (it was running fine for a few months now)
And now it just hangs with the log below and doesn't boot up.
I also noticed the 1.9.3.0 in the logs but I did run docker-pull latest before posting here.
```
today at 23:29:54 Changing to /app folder
today at 23:29:54 Starting rtdclient
today at 23:29:54 Changing to /app folder
today at 23:29:54 Starting rtdclient
today at 23:29:57 [21:29:57 WRN] Starting host on version 1.9.3.0
today at 23:29:57 [21:29:57 WRN] Starting host on version 1.9.3.0
today at 23:29:57 [21:29:57 WRN] Using an in-memory repository. Keys will not be persisted to storage.
today at 23:29:57 [21:29:57 WRN] Using an in-memory repository. Keys will not be persisted to storage.
today at 23:29:57 [21:29:57 WRN] Neither user profile nor HKLM registry available. Using an ephemeral key repository. Protected data will be unavailable when application exits.
today at 23:29:57 [21:29:57 WRN] Neither user profile nor HKLM registry available. Using an ephemeral key repository. Protected data will be unavailable when application exits.
today at 23:29:57 [21:29:57 WRN] No XML encryptor configured. Key {bbc1ebaf-0e49-4e05-a586-59bb2409b773} may be persisted to storage in unencrypted form.
today at 23:29:57 [21:29:57 WRN] No XML encryptor configured. Key {bbc1ebaf-0e49-4e05-a586-59bb2409b773} may be persisted to storage in unencrypted form.
today at 23:29:57 [21:29:57 FTL] Host terminated unexpectedly
today at 23:29:57 System.FormatException: Input string was not in a correct format.
today at 23:29:57    at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
today at 23:29:57    at System.Number.ParseInt32(ReadOnlySpan`1 value, NumberStyles styles, NumberFormatInfo info)
today at 23:29:57    at System.Int32.Parse(String s)
today at 23:29:57    at RdtClient.Data.Data.SettingData.<ResetCache>g__GetInt32|7_1(String name, <>c__DisplayClass7_0& ) in /appserver/server/RdtClient.Data/Data/SettingData.cs:line 30
today at 23:29:57    at RdtClient.Data.Data.SettingData.ResetCache() in /appserver/server/RdtClient.Data/Data/SettingData.cs:line 32
today at 23:29:57    at RdtClient.Service.Services.Settings.ResetCache() in /appserver/server/RdtClient.Service/Services/Settings.cs:line 179
today at 23:29:57    at RdtClient.Service.Services.Startup.StartAsync(CancellationToken cancellationToken) in /appserver/server/RdtClient.Service/Services/Startup.cs:line 24
today at 23:29:57    at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
today at 23:29:57    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
today at 23:29:57    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
today at 23:29:57    at RdtClient.Web.Program.Main(String[] args) in /appserver/server/RdtClient.Web/Program.cs:line 57
today at 23:29:57 [21:29:57 FTL] Host terminated unexpectedly
today at 23:29:57 System.FormatException: Input string was not in a correct format.
today at 23:29:57    at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
today at 23:29:57    at System.Number.ParseInt32(ReadOnlySpan`1 value, NumberStyles styles, NumberFormatInfo info)
today at 23:29:57    at System.Int32.Parse(String s)
today at 23:29:57    at RdtClient.Data.Data.SettingData.<ResetCache>g__GetInt32|7_1(String name, <>c__DisplayClass7_0& ) in /appserver/server/RdtClient.Data/Data/SettingData.cs:line 30
today at 23:29:57    at RdtClient.Data.Data.SettingData.ResetCache() in /appserver/server/RdtClient.Data/Data/SettingData.cs:line 32
today at 23:29:57    at RdtClient.Service.Services.Settings.ResetCache() in /appserver/server/RdtClient.Service/Services/Settings.cs:line 179
today at 23:29:57    at RdtClient.Service.Services.Startup.StartAsync(CancellationToken cancellationToken) in /appserver/server/RdtClient.Service/Services/Startup.cs:line 24
today at 23:29:57    at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
today at 23:29:57    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
today at 23:29:57    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
today at 23:29:57    at RdtClient.Web.Program.Main(String[] args) in /appserver/server/RdtClient.Web/Program.cs:line 57
```

**Comment by rogerfar** [comment]
If you have still issues, feel free to comment on this ticket or create a new one.
