### ISSUE TITLE
Error adding magnet directly via the web interface

### ISSUE THREAD

**Issue by ravensorb** [rogerfar/rdt-client#89]
**What version are you using?** v1.7.3 (docker)
**What OS are you running?** Docker host is ubuntu
**Are you using Docker or as a service?** Docker

I am getting the following error when I add any magnet 
```
Cannot add torrent: { "error": "wrong_parameter", "error_code": 2 }
```

If it helps I am testing out using it with alldebrid.com

**Comment by rogerfar** [comment]
Can you post the magnet as a pastebin?

**Comment by ravensorb** [comment]
Sure, so far any magnet is causing the issue.

```
magnet:?xt=urn:btih:85DF3BA156090D51D53DAAADDAB69815C4560599&dn=Endeavour+S08E03+WEBRip+x264-TORRENTGALAXY%5BTGx%5D&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Fopen.stealth.si%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.tiny-vps.com%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.internetwarriors.net%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.cyberia.is%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451%2Fannounce&tr=udp%3A%2F%2Ftracker.dler.org%3A6969%2Fannounce&tr=udp%3A%2F%2Fopentor.org%3A2710%2Fannounce&tr=udp%3A%2F%2Fipv4.tracker.harry.lu%3A80%2Fannounce&tr=udp%3A%2F%2Fipv6.tracker.harry.lu%3A80%2Fannounce&tr=udp%3A%2F%2Fexplodie.org%3A6969%2Fannounce&tr=udp%3A%2F%2Fexodus.desync.com%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969%2Fannounce&tr=udp%3A%2F%2F9.rarbg.to%3A2710%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.open-internet.nl%3A6969%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.si%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.pirateparty.gr%3A6969%2Fannounce&tr=udp%3A%2F%2Fdenis.stalker.upeer.me%3A6969%2Fannounce&tr=udp%3A%2F%2Fp4p.arenabg.com%3A1337%2Fannounce
```

**Comment by rogerfar** [comment]
I just tried that torrent and it worked fine. Can you update to the latest version 1.9.8 and see if that changes anything?

**Comment by ravensorb** [comment]
Hmm, odd -- when I do a get latest and try to start it I am getting a call stack exception

```
Starting rdtclient ... 

ERROR: for rdtclient  __init__() got an unexpected keyword argument 'disable_buffering'

ERROR: for rdtclient  __init__() got an unexpected keyword argument 'disable_buffering'
Traceback (most recent call last):
  File "/home/ravenwolf.org/sanderson/.local/bin/docker-compose", line 8, in <module>
    sys.exit(main())
  File "/home/ravenwolf.org/sanderson/.local/lib/python3.9/site-packages/compose/cli/main.py", line 81, in main
    command_func()
  File "/home/ravenwolf.org/sanderson/.local/lib/python3.9/site-packages/compose/cli/main.py", line 203, in perform_command
    handler(command, command_options)
  File "/home/ravenwolf.org/sanderson/.local/lib/python3.9/site-packages/compose/metrics/decorator.py", line 18, in wrapper
    result = fn(*args, **kwargs)
  File "/home/ravenwolf.org/sanderson/.local/lib/python3.9/site-packages/compose/cli/main.py", line 1186, in up
    to_attach = up(False)
  File "/home/ravenwolf.org/sanderson/.local/lib/python3.9/site-packages/compose/cli/main.py", line 1166, in up
    return self.project.up(
  File "/home/ravenwolf.org/sanderson/.local/lib/python3.9/site-packages/compose/project.py", line 697, in up
    results, errors = parallel.parallel_execute(
  File "/home/ravenwolf.org/sanderson/.local/lib/python3.9/site-packages/compose/parallel.py", line 108, in parallel_execute
    raise error_to_reraise
  File "/home/ravenwolf.org/sanderson/.local/lib/python3.9/site-packages/compose/parallel.py", line 206, in producer
    result = func(obj)
  File "/home/ravenwolf.org/sanderson/.local/lib/python3.9/site-packages/compose/project.py", line 679, in do
    return service.execute_convergence_plan(
  File "/home/ravenwolf.org/sanderson/.local/lib/python3.9/site-packages/compose/service.py", line 585, in execute_convergence_plan
    return self._execute_convergence_start(
  File "/home/ravenwolf.org/sanderson/.local/lib/python3.9/site-packages/compose/service.py", line 520, in _execute_convergence_start
    _, errors = parallel_execute(
  File "/home/ravenwolf.org/sanderson/.local/lib/python3.9/site-packages/compose/parallel.py", line 108, in parallel_execute
    raise error_to_reraise
  File "/home/ravenwolf.org/sanderson/.local/lib/python3.9/site-packages/compose/parallel.py", line 206, in producer
    result = func(obj)
  File "/home/ravenwolf.org/sanderson/.local/lib/python3.9/site-packages/compose/service.py", line 522, in <lambda>
    lambda c: self.start_container_if_stopped(c, attach_logs=not detached, quiet=True),
  File "/home/ravenwolf.org/sanderson/.local/lib/python3.9/site-packages/compose/service.py", line 637, in start_container_if_stopped
    container.attach_log_stream()
  File "/home/ravenwolf.org/sanderson/.local/lib/python3.9/site-packages/compose/container.py", line 202, in attach_log_stream
    self.log_stream = self.attach(stdout=True, stderr=True, stream=True)
  File "/home/ravenwolf.org/sanderson/.local/lib/python3.9/site-packages/compose/container.py", line 294, in attach
    return self.client.attach(self.id, *args, **kwargs)
  File "/home/ravenwolf.org/sanderson/.local/lib/python3.9/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/home/ravenwolf.org/sanderson/.local/lib/python3.9/site-packages/docker/api/container.py", line 58, in attach
    response = self._post(u, headers=headers, params=params, stream=True)
  File "/home/ravenwolf.org/sanderson/.local/lib/python3.9/site-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/home/ravenwolf.org/sanderson/.local/lib/python3.9/site-packages/docker/api/client.py", line 233, in _post
    return self.post(url, **self._set_request_timeout(kwargs))
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.9/http/client.py", line 1341, in getresponse
    response = self.response_class(self.sock, method=self._method)
  File "/home/ravenwolf.org/sanderson/.local/lib/python3.9/site-packages/docker/transport/unixconn.py", line 43, in response_class
    return httplib.HTTPResponse(sock, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'disable_buffering'
```

**Comment by rogerfar** [comment]
Is that an error from like a docker image manager? There's no python anywhere near the docker image as far as I know.

**Comment by ravensorb** [comment]
Hmm, looking at this again it seems to be a docker-compose error.  Odd part is, this is the only container having an issue right now.  I'll dig into it tomorrow and see what I can find.

**Comment by ravensorb** [comment]
Ok, not sure what happened -- grabbed a new version of the container and it loaded.  The error I am getting is now

https://pastebin.com/BjxhA6je

**Comment by rogerfar** [comment]
Should be good now in 2.0.1

**Comment by ravensorb** [comment]
Ok, getting closer :)  Now it is automatically loading everything from alldebrid into the UI.  The next issue is, nothing actually downloads locally.  It seems they get stuck "waiting for links".

**Comment by rogerfar** [comment]
Do you have some logs?

**Comment by ravensorb** [comment]
Ok, after 2 days it actually did end up downloading files. Here is the interesting thing -- I had manually added the ubuntu iso download and it downloaded that ISO for EVERY torrent that was on Alldebrid.  It looks like rdtclient automatically added all of my torrents in Alldebrid and then set then decided to pull down the iso for each one.  Is that bug?

**Comment by rogerfar** [comment]
That's a very strange one, I'll see if I can reproduce it.

**Comment by ravensorb** [comment]
Agreed.  The steps I did was

* Start docker image
* Setup user
* Add alldebrid api key
* Manually add the ubuntu torrent
* Refresh ui

I then saw ALL of my items from alldebrid and most said "waiting for links".  Then I checked back a while later and noticed a few had finished downloading.  When I looked at the local folders -- every folder had the same iso file in it.

**Comment by ravensorb** [comment]
More info :)  I did a "force" restart of 3 torrents -- and they ALL downloaded the torrent for the 1st one I restarted.

**Comment by ravensorb** [comment]
Little more digging -- it appears that the process of "auto loading" of torrents that are already on the provider always takes the first torrent and applies it to all of the ones imported.

**Comment by rogerfar** [comment]
You're right, found a bug in the AllDebrid provider which didn't work properly when getting a single torrent. Fixed it in the next version.
